// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const listStaleSearchSync = `-- name: ListStaleSearchSync :many
SELECT id, ref_id, ref_type
FROM catalog.search_sync
WHERE (is_stale_metadata = $2 OR is_stale_embedding = $3) AND ref_type = $1
ORDER BY date_updated ASC
FOR UPDATE SKIP LOCKED
LIMIT $4
`

type ListStaleSearchSyncParams struct {
	RefType          string    `json:"ref_type"`
	IsStaleMetadata  null.Bool `json:"is_stale_metadata"`
	IsStaleEmbedding null.Bool `json:"is_stale_embedding"`
	Limit            int32     `json:"limit"`
}

type ListStaleSearchSyncRow struct {
	ID      int64     `json:"id"`
	RefID   uuid.UUID `json:"ref_id"`
	RefType string    `json:"ref_type"`
}

func (q *Queries) ListStaleSearchSync(ctx context.Context, arg ListStaleSearchSyncParams) ([]ListStaleSearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listStaleSearchSync,
		arg.RefType,
		arg.IsStaleMetadata,
		arg.IsStaleEmbedding,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSearchSyncRow{}
	for rows.Next() {
		var i ListStaleSearchSyncRow
		if err := rows.Scan(&i.ID, &i.RefID, &i.RefType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaleSearchSync = `-- name: UpdateStaleSearchSync :exec
UPDATE catalog.search_sync
SET
    is_stale_metadata = COALESCE($1, is_stale_metadata),
    is_stale_embedding = COALESCE($2, is_stale_embedding),
    date_updated = NOW()
WHERE ref_type = $3 AND ref_id = $4
`

type UpdateStaleSearchSyncParams struct {
	IsStaleMetadata  null.Bool `json:"is_stale_metadata"`
	IsStaleEmbedding null.Bool `json:"is_stale_embedding"`
	RefType          string    `json:"ref_type"`
	RefID            uuid.UUID `json:"ref_id"`
}

func (q *Queries) UpdateStaleSearchSync(ctx context.Context, arg UpdateStaleSearchSyncParams) error {
	_, err := q.db.Exec(ctx, updateStaleSearchSync,
		arg.IsStaleMetadata,
		arg.IsStaleEmbedding,
		arg.RefType,
		arg.RefID,
	)
	return err
}
