// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_profile.sql

package accountdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countAccountProfile = `-- name: CountAccountProfile :one
SELECT COUNT(*)
FROM "account"."profile"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("gender" = ANY($2) OR $2 IS NULL) AND
    ("name" = ANY($3) OR $3 IS NULL) AND
    ("date_of_birth" = ANY($4) OR $4 IS NULL) AND
    ("date_of_birth" > $5 OR $5 IS NULL) AND
    ("date_of_birth" < $6 OR $6 IS NULL) AND
    ("avatar_rs_id" = ANY($7) OR $7 IS NULL) AND
    ("email_verified" = ANY($8) OR $8 IS NULL) AND
    ("phone_verified" = ANY($9) OR $9 IS NULL) AND
    ("default_contact_id" = ANY($10) OR $10 IS NULL) AND
    ("date_created" = ANY($11) OR $11 IS NULL) AND
    ("date_created" > $12 OR $12 IS NULL) AND
    ("date_created" < $13 OR $13 IS NULL) AND
    ("date_updated" = ANY($14) OR $14 IS NULL) AND
    ("date_updated" > $15 OR $15 IS NULL) AND
    ("date_updated" < $16 OR $16 IS NULL) AND
    ("description" = ANY($17) OR $17 IS NULL)
)
`

type CountAccountProfileParams struct {
	ID               []uuid.UUID         `json:"id"`
	Gender           []NullAccountGender `json:"gender"`
	Name             []null.String       `json:"name"`
	DateOfBirth      []null.Time         `json:"date_of_birth"`
	DateOfBirthFrom  null.Time           `json:"date_of_birth_from"`
	DateOfBirthTo    null.Time           `json:"date_of_birth_to"`
	AvatarRsID       []uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    []bool              `json:"email_verified"`
	PhoneVerified    []bool              `json:"phone_verified"`
	DefaultContactID []uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      []time.Time         `json:"date_created"`
	DateCreatedFrom  null.Time           `json:"date_created_from"`
	DateCreatedTo    null.Time           `json:"date_created_to"`
	DateUpdated      []time.Time         `json:"date_updated"`
	DateUpdatedFrom  null.Time           `json:"date_updated_from"`
	DateUpdatedTo    null.Time           `json:"date_updated_to"`
	Description      []string            `json:"description"`
}

func (q *Queries) CountAccountProfile(ctx context.Context, arg CountAccountProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfBirthFrom,
		arg.DateOfBirthTo,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Description,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountProfile = `-- name: CreateAccountProfile :one
INSERT INTO "account"."profile" ("id", "gender", "name", "date_of_birth", "avatar_rs_id", "email_verified", "phone_verified", "default_contact_id", "date_created", "date_updated", "description")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, gender, name, date_of_birth, avatar_rs_id, email_verified, phone_verified, default_contact_id, date_created, date_updated, description
`

type CreateAccountProfileParams struct {
	ID               uuid.UUID         `json:"id"`
	Gender           NullAccountGender `json:"gender"`
	Name             null.String       `json:"name"`
	DateOfBirth      null.Time         `json:"date_of_birth"`
	AvatarRsID       uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    bool              `json:"email_verified"`
	PhoneVerified    bool              `json:"phone_verified"`
	DefaultContactID uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      time.Time         `json:"date_created"`
	DateUpdated      time.Time         `json:"date_updated"`
	Description      string            `json:"description"`
}

func (q *Queries) CreateAccountProfile(ctx context.Context, arg CreateAccountProfileParams) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, createAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateUpdated,
		arg.Description,
	)
	var i AccountProfile
	err := row.Scan(
		&i.ID,
		&i.Gender,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarRsID,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.DefaultContactID,
		&i.DateCreated,
		&i.DateUpdated,
		&i.Description,
	)
	return i, err
}

type CreateCopyAccountProfileParams struct {
	ID               uuid.UUID         `json:"id"`
	Gender           NullAccountGender `json:"gender"`
	Name             null.String       `json:"name"`
	DateOfBirth      null.Time         `json:"date_of_birth"`
	AvatarRsID       uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    bool              `json:"email_verified"`
	PhoneVerified    bool              `json:"phone_verified"`
	DefaultContactID uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      time.Time         `json:"date_created"`
	DateUpdated      time.Time         `json:"date_updated"`
	Description      string            `json:"description"`
}

type CreateCopyDefaultAccountProfileParams struct {
	ID               uuid.UUID         `json:"id"`
	Gender           NullAccountGender `json:"gender"`
	Name             null.String       `json:"name"`
	DateOfBirth      null.Time         `json:"date_of_birth"`
	AvatarRsID       uuid.NullUUID     `json:"avatar_rs_id"`
	DefaultContactID uuid.NullUUID     `json:"default_contact_id"`
}

const createDefaultAccountProfile = `-- name: CreateDefaultAccountProfile :one
INSERT INTO "account"."profile" ("id", "gender", "name", "date_of_birth", "avatar_rs_id", "default_contact_id")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, gender, name, date_of_birth, avatar_rs_id, email_verified, phone_verified, default_contact_id, date_created, date_updated, description
`

type CreateDefaultAccountProfileParams struct {
	ID               uuid.UUID         `json:"id"`
	Gender           NullAccountGender `json:"gender"`
	Name             null.String       `json:"name"`
	DateOfBirth      null.Time         `json:"date_of_birth"`
	AvatarRsID       uuid.NullUUID     `json:"avatar_rs_id"`
	DefaultContactID uuid.NullUUID     `json:"default_contact_id"`
}

func (q *Queries) CreateDefaultAccountProfile(ctx context.Context, arg CreateDefaultAccountProfileParams) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, createDefaultAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.AvatarRsID,
		arg.DefaultContactID,
	)
	var i AccountProfile
	err := row.Scan(
		&i.ID,
		&i.Gender,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarRsID,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.DefaultContactID,
		&i.DateCreated,
		&i.DateUpdated,
		&i.Description,
	)
	return i, err
}

const deleteAccountProfile = `-- name: DeleteAccountProfile :exec
DELETE FROM "account"."profile"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("gender" = ANY($2) OR $2 IS NULL) AND
    ("name" = ANY($3) OR $3 IS NULL) AND
    ("date_of_birth" = ANY($4) OR $4 IS NULL) AND
    ("date_of_birth" > $5 OR $5 IS NULL) AND
    ("date_of_birth" < $6 OR $6 IS NULL) AND
    ("avatar_rs_id" = ANY($7) OR $7 IS NULL) AND
    ("email_verified" = ANY($8) OR $8 IS NULL) AND
    ("phone_verified" = ANY($9) OR $9 IS NULL) AND
    ("default_contact_id" = ANY($10) OR $10 IS NULL) AND
    ("date_created" = ANY($11) OR $11 IS NULL) AND
    ("date_created" > $12 OR $12 IS NULL) AND
    ("date_created" < $13 OR $13 IS NULL) AND
    ("date_updated" = ANY($14) OR $14 IS NULL) AND
    ("date_updated" > $15 OR $15 IS NULL) AND
    ("date_updated" < $16 OR $16 IS NULL) AND
    ("description" = ANY($17) OR $17 IS NULL)
)
`

type DeleteAccountProfileParams struct {
	ID               []uuid.UUID         `json:"id"`
	Gender           []NullAccountGender `json:"gender"`
	Name             []null.String       `json:"name"`
	DateOfBirth      []null.Time         `json:"date_of_birth"`
	DateOfBirthFrom  null.Time           `json:"date_of_birth_from"`
	DateOfBirthTo    null.Time           `json:"date_of_birth_to"`
	AvatarRsID       []uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    []bool              `json:"email_verified"`
	PhoneVerified    []bool              `json:"phone_verified"`
	DefaultContactID []uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      []time.Time         `json:"date_created"`
	DateCreatedFrom  null.Time           `json:"date_created_from"`
	DateCreatedTo    null.Time           `json:"date_created_to"`
	DateUpdated      []time.Time         `json:"date_updated"`
	DateUpdatedFrom  null.Time           `json:"date_updated_from"`
	DateUpdatedTo    null.Time           `json:"date_updated_to"`
	Description      []string            `json:"description"`
}

func (q *Queries) DeleteAccountProfile(ctx context.Context, arg DeleteAccountProfileParams) error {
	_, err := q.db.Exec(ctx, deleteAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfBirthFrom,
		arg.DateOfBirthTo,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Description,
	)
	return err
}

const getAccountProfile = `-- name: GetAccountProfile :one

SELECT id, gender, name, date_of_birth, avatar_rs_id, email_verified, phone_verified, default_contact_id, date_created, date_updated, description
FROM "account"."profile"
WHERE ("id" = $1) OR ("avatar_rs_id" = $2) OR ("default_contact_id" = $3)
`

type GetAccountProfileParams struct {
	ID               uuid.NullUUID `json:"id"`
	AvatarRsID       uuid.NullUUID `json:"avatar_rs_id"`
	DefaultContactID uuid.NullUUID `json:"default_contact_id"`
}

// Code generated by pgtempl. DO NOT EDIT.
// Queries for table: account.profile
func (q *Queries) GetAccountProfile(ctx context.Context, arg GetAccountProfileParams) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, arg.ID, arg.AvatarRsID, arg.DefaultContactID)
	var i AccountProfile
	err := row.Scan(
		&i.ID,
		&i.Gender,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarRsID,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.DefaultContactID,
		&i.DateCreated,
		&i.DateUpdated,
		&i.Description,
	)
	return i, err
}

const listAccountProfile = `-- name: ListAccountProfile :many
SELECT id, gender, name, date_of_birth, avatar_rs_id, email_verified, phone_verified, default_contact_id, date_created, date_updated, description
FROM "account"."profile"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("gender" = ANY($2) OR $2 IS NULL) AND
    ("name" = ANY($3) OR $3 IS NULL) AND
    ("date_of_birth" = ANY($4) OR $4 IS NULL) AND
    ("date_of_birth" > $5 OR $5 IS NULL) AND
    ("date_of_birth" < $6 OR $6 IS NULL) AND
    ("avatar_rs_id" = ANY($7) OR $7 IS NULL) AND
    ("email_verified" = ANY($8) OR $8 IS NULL) AND
    ("phone_verified" = ANY($9) OR $9 IS NULL) AND
    ("default_contact_id" = ANY($10) OR $10 IS NULL) AND
    ("date_created" = ANY($11) OR $11 IS NULL) AND
    ("date_created" > $12 OR $12 IS NULL) AND
    ("date_created" < $13 OR $13 IS NULL) AND
    ("date_updated" = ANY($14) OR $14 IS NULL) AND
    ("date_updated" > $15 OR $15 IS NULL) AND
    ("date_updated" < $16 OR $16 IS NULL) AND
    ("description" = ANY($17) OR $17 IS NULL)
)
ORDER BY "id"
LIMIT $19::int
OFFSET $18::int
`

type ListAccountProfileParams struct {
	ID               []uuid.UUID         `json:"id"`
	Gender           []NullAccountGender `json:"gender"`
	Name             []null.String       `json:"name"`
	DateOfBirth      []null.Time         `json:"date_of_birth"`
	DateOfBirthFrom  null.Time           `json:"date_of_birth_from"`
	DateOfBirthTo    null.Time           `json:"date_of_birth_to"`
	AvatarRsID       []uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    []bool              `json:"email_verified"`
	PhoneVerified    []bool              `json:"phone_verified"`
	DefaultContactID []uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      []time.Time         `json:"date_created"`
	DateCreatedFrom  null.Time           `json:"date_created_from"`
	DateCreatedTo    null.Time           `json:"date_created_to"`
	DateUpdated      []time.Time         `json:"date_updated"`
	DateUpdatedFrom  null.Time           `json:"date_updated_from"`
	DateUpdatedTo    null.Time           `json:"date_updated_to"`
	Description      []string            `json:"description"`
	Offset           null.Int32          `json:"offset"`
	Limit            null.Int32          `json:"limit"`
}

func (q *Queries) ListAccountProfile(ctx context.Context, arg ListAccountProfileParams) ([]AccountProfile, error) {
	rows, err := q.db.Query(ctx, listAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfBirthFrom,
		arg.DateOfBirthTo,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Description,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountProfile{}
	for rows.Next() {
		var i AccountProfile
		if err := rows.Scan(
			&i.ID,
			&i.Gender,
			&i.Name,
			&i.DateOfBirth,
			&i.AvatarRsID,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.DefaultContactID,
			&i.DateCreated,
			&i.DateUpdated,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountAccountProfile = `-- name: ListCountAccountProfile :many
SELECT embed_profile.id, embed_profile.gender, embed_profile.name, embed_profile.date_of_birth, embed_profile.avatar_rs_id, embed_profile.email_verified, embed_profile.phone_verified, embed_profile.default_contact_id, embed_profile.date_created, embed_profile.date_updated, embed_profile.description, COUNT(*) OVER() as total_count
FROM "account"."profile" embed_profile
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("gender" = ANY($2) OR $2 IS NULL) AND
    ("name" = ANY($3) OR $3 IS NULL) AND
    ("date_of_birth" = ANY($4) OR $4 IS NULL) AND
    ("date_of_birth" > $5 OR $5 IS NULL) AND
    ("date_of_birth" < $6 OR $6 IS NULL) AND
    ("avatar_rs_id" = ANY($7) OR $7 IS NULL) AND
    ("email_verified" = ANY($8) OR $8 IS NULL) AND
    ("phone_verified" = ANY($9) OR $9 IS NULL) AND
    ("default_contact_id" = ANY($10) OR $10 IS NULL) AND
    ("date_created" = ANY($11) OR $11 IS NULL) AND
    ("date_created" > $12 OR $12 IS NULL) AND
    ("date_created" < $13 OR $13 IS NULL) AND
    ("date_updated" = ANY($14) OR $14 IS NULL) AND
    ("date_updated" > $15 OR $15 IS NULL) AND
    ("date_updated" < $16 OR $16 IS NULL) AND
    ("description" = ANY($17) OR $17 IS NULL)
)
ORDER BY "id"
LIMIT $19::int
OFFSET $18::int
`

type ListCountAccountProfileParams struct {
	ID               []uuid.UUID         `json:"id"`
	Gender           []NullAccountGender `json:"gender"`
	Name             []null.String       `json:"name"`
	DateOfBirth      []null.Time         `json:"date_of_birth"`
	DateOfBirthFrom  null.Time           `json:"date_of_birth_from"`
	DateOfBirthTo    null.Time           `json:"date_of_birth_to"`
	AvatarRsID       []uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified    []bool              `json:"email_verified"`
	PhoneVerified    []bool              `json:"phone_verified"`
	DefaultContactID []uuid.NullUUID     `json:"default_contact_id"`
	DateCreated      []time.Time         `json:"date_created"`
	DateCreatedFrom  null.Time           `json:"date_created_from"`
	DateCreatedTo    null.Time           `json:"date_created_to"`
	DateUpdated      []time.Time         `json:"date_updated"`
	DateUpdatedFrom  null.Time           `json:"date_updated_from"`
	DateUpdatedTo    null.Time           `json:"date_updated_to"`
	Description      []string            `json:"description"`
	Offset           null.Int32          `json:"offset"`
	Limit            null.Int32          `json:"limit"`
}

type ListCountAccountProfileRow struct {
	AccountProfile AccountProfile `json:"account_profile"`
	TotalCount     int64          `json:"total_count"`
}

func (q *Queries) ListCountAccountProfile(ctx context.Context, arg ListCountAccountProfileParams) ([]ListCountAccountProfileRow, error) {
	rows, err := q.db.Query(ctx, listCountAccountProfile,
		arg.ID,
		arg.Gender,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfBirthFrom,
		arg.DateOfBirthTo,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Description,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountAccountProfileRow{}
	for rows.Next() {
		var i ListCountAccountProfileRow
		if err := rows.Scan(
			&i.AccountProfile.ID,
			&i.AccountProfile.Gender,
			&i.AccountProfile.Name,
			&i.AccountProfile.DateOfBirth,
			&i.AccountProfile.AvatarRsID,
			&i.AccountProfile.EmailVerified,
			&i.AccountProfile.PhoneVerified,
			&i.AccountProfile.DefaultContactID,
			&i.AccountProfile.DateCreated,
			&i.AccountProfile.DateUpdated,
			&i.AccountProfile.Description,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE "account"."profile"
SET "gender" = CASE WHEN $1::bool = TRUE THEN NULL ELSE COALESCE($2, "gender") END,
    "name" = CASE WHEN $3::bool = TRUE THEN NULL ELSE COALESCE($4, "name") END,
    "date_of_birth" = CASE WHEN $5::bool = TRUE THEN NULL ELSE COALESCE($6, "date_of_birth") END,
    "avatar_rs_id" = CASE WHEN $7::bool = TRUE THEN NULL ELSE COALESCE($8, "avatar_rs_id") END,
    "email_verified" = COALESCE($9, "email_verified"),
    "phone_verified" = COALESCE($10, "phone_verified"),
    "default_contact_id" = CASE WHEN $11::bool = TRUE THEN NULL ELSE COALESCE($12, "default_contact_id") END,
    "date_created" = COALESCE($13, "date_created"),
    "date_updated" = COALESCE($14, "date_updated"),
    "description" = COALESCE($15, "description")
WHERE id = $16
RETURNING id, gender, name, date_of_birth, avatar_rs_id, email_verified, phone_verified, default_contact_id, date_created, date_updated, description
`

type UpdateAccountProfileParams struct {
	NullGender           bool              `json:"null_gender"`
	Gender               NullAccountGender `json:"gender"`
	NullName             bool              `json:"null_name"`
	Name                 null.String       `json:"name"`
	NullDateOfBirth      bool              `json:"null_date_of_birth"`
	DateOfBirth          null.Time         `json:"date_of_birth"`
	NullAvatarRsID       bool              `json:"null_avatar_rs_id"`
	AvatarRsID           uuid.NullUUID     `json:"avatar_rs_id"`
	EmailVerified        null.Bool         `json:"email_verified"`
	PhoneVerified        null.Bool         `json:"phone_verified"`
	NullDefaultContactID bool              `json:"null_default_contact_id"`
	DefaultContactID     uuid.NullUUID     `json:"default_contact_id"`
	DateCreated          null.Time         `json:"date_created"`
	DateUpdated          null.Time         `json:"date_updated"`
	Description          null.String       `json:"description"`
	ID                   uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (AccountProfile, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile,
		arg.NullGender,
		arg.Gender,
		arg.NullName,
		arg.Name,
		arg.NullDateOfBirth,
		arg.DateOfBirth,
		arg.NullAvatarRsID,
		arg.AvatarRsID,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.NullDefaultContactID,
		arg.DefaultContactID,
		arg.DateCreated,
		arg.DateUpdated,
		arg.Description,
		arg.ID,
	)
	var i AccountProfile
	err := row.Scan(
		&i.ID,
		&i.Gender,
		&i.Name,
		&i.DateOfBirth,
		&i.AvatarRsID,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.DefaultContactID,
		&i.DateCreated,
		&i.DateUpdated,
		&i.Description,
	)
	return i, err
}
