// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_payment_method.sql

package accountdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countPaymentMethod = `-- name: CountPaymentMethod :one
SELECT COUNT(*)
FROM "account"."payment_method"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("type" = ANY($3) OR $3 IS NULL) AND
    ("label" = ANY($4) OR $4 IS NULL) AND
    ("data" = ANY($5) OR $5 IS NULL) AND
    ("is_default" = ANY($6) OR $6 IS NULL) AND
    ("date_created" = ANY($7) OR $7 IS NULL) AND
    ("date_created" > $8 OR $8 IS NULL) AND
    ("date_created" < $9 OR $9 IS NULL) AND
    ("date_updated" = ANY($10) OR $10 IS NULL) AND
    ("date_updated" > $11 OR $11 IS NULL) AND
    ("date_updated" < $12 OR $12 IS NULL)
)
`

type CountPaymentMethodParams struct {
	ID              []uuid.UUID       `json:"id"`
	AccountID       []uuid.UUID       `json:"account_id"`
	Type            []string          `json:"type"`
	Label           []string          `json:"label"`
	Data            []json.RawMessage `json:"data"`
	IsDefault       []bool            `json:"is_default"`
	DateCreated     []time.Time       `json:"date_created"`
	DateCreatedFrom null.Time         `json:"date_created_from"`
	DateCreatedTo   null.Time         `json:"date_created_to"`
	DateUpdated     []time.Time       `json:"date_updated"`
	DateUpdatedFrom null.Time         `json:"date_updated_from"`
	DateUpdatedTo   null.Time         `json:"date_updated_to"`
}

func (q *Queries) CountPaymentMethod(ctx context.Context, arg CountPaymentMethodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentMethod,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCopyDefaultPaymentMethodParams struct {
	AccountID uuid.UUID       `json:"account_id"`
	Type      string          `json:"type"`
	Label     string          `json:"label"`
	Data      json.RawMessage `json:"data"`
}

type CreateCopyPaymentMethodParams struct {
	ID          uuid.UUID       `json:"id"`
	AccountID   uuid.UUID       `json:"account_id"`
	Type        string          `json:"type"`
	Label       string          `json:"label"`
	Data        json.RawMessage `json:"data"`
	IsDefault   bool            `json:"is_default"`
	DateCreated time.Time       `json:"date_created"`
	DateUpdated time.Time       `json:"date_updated"`
}

const createDefaultPaymentMethod = `-- name: CreateDefaultPaymentMethod :one
INSERT INTO "account"."payment_method" ("account_id", "type", "label", "data")
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, type, label, data, is_default, date_created, date_updated
`

type CreateDefaultPaymentMethodParams struct {
	AccountID uuid.UUID       `json:"account_id"`
	Type      string          `json:"type"`
	Label     string          `json:"label"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) CreateDefaultPaymentMethod(ctx context.Context, arg CreateDefaultPaymentMethodParams) (AccountPaymentMethod, error) {
	row := q.db.QueryRow(ctx, createDefaultPaymentMethod,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
	)
	var i AccountPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Label,
		&i.Data,
		&i.IsDefault,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO "account"."payment_method" ("id", "account_id", "type", "label", "data", "is_default", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, type, label, data, is_default, date_created, date_updated
`

type CreatePaymentMethodParams struct {
	ID          uuid.UUID       `json:"id"`
	AccountID   uuid.UUID       `json:"account_id"`
	Type        string          `json:"type"`
	Label       string          `json:"label"`
	Data        json.RawMessage `json:"data"`
	IsDefault   bool            `json:"is_default"`
	DateCreated time.Time       `json:"date_created"`
	DateUpdated time.Time       `json:"date_updated"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (AccountPaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i AccountPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Label,
		&i.Data,
		&i.IsDefault,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM "account"."payment_method"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("type" = ANY($3) OR $3 IS NULL) AND
    ("label" = ANY($4) OR $4 IS NULL) AND
    ("data" = ANY($5) OR $5 IS NULL) AND
    ("is_default" = ANY($6) OR $6 IS NULL) AND
    ("date_created" = ANY($7) OR $7 IS NULL) AND
    ("date_created" > $8 OR $8 IS NULL) AND
    ("date_created" < $9 OR $9 IS NULL) AND
    ("date_updated" = ANY($10) OR $10 IS NULL) AND
    ("date_updated" > $11 OR $11 IS NULL) AND
    ("date_updated" < $12 OR $12 IS NULL)
)
`

type DeletePaymentMethodParams struct {
	ID              []uuid.UUID       `json:"id"`
	AccountID       []uuid.UUID       `json:"account_id"`
	Type            []string          `json:"type"`
	Label           []string          `json:"label"`
	Data            []json.RawMessage `json:"data"`
	IsDefault       []bool            `json:"is_default"`
	DateCreated     []time.Time       `json:"date_created"`
	DateCreatedFrom null.Time         `json:"date_created_from"`
	DateCreatedTo   null.Time         `json:"date_created_to"`
	DateUpdated     []time.Time       `json:"date_updated"`
	DateUpdatedFrom null.Time         `json:"date_updated_from"`
	DateUpdatedTo   null.Time         `json:"date_updated_to"`
}

func (q *Queries) DeletePaymentMethod(ctx context.Context, arg DeletePaymentMethodParams) error {
	_, err := q.db.Exec(ctx, deletePaymentMethod,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one

SELECT id, account_id, type, label, data, is_default, date_created, date_updated
FROM "account"."payment_method"
WHERE ("id" = $1) OR ("account_id" = $2)
`

type GetPaymentMethodParams struct {
	ID        uuid.NullUUID `json:"id"`
	AccountID uuid.NullUUID `json:"account_id"`
}

// Code generated by pgtempl. DO NOT EDIT.
// Queries for table: account.payment_method
func (q *Queries) GetPaymentMethod(ctx context.Context, arg GetPaymentMethodParams) (AccountPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, arg.ID, arg.AccountID)
	var i AccountPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Label,
		&i.Data,
		&i.IsDefault,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const listCountPaymentMethod = `-- name: ListCountPaymentMethod :many
SELECT embed_payment_method.id, embed_payment_method.account_id, embed_payment_method.type, embed_payment_method.label, embed_payment_method.data, embed_payment_method.is_default, embed_payment_method.date_created, embed_payment_method.date_updated, COUNT(*) OVER() as total_count
FROM "account"."payment_method" embed_payment_method
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("type" = ANY($3) OR $3 IS NULL) AND
    ("label" = ANY($4) OR $4 IS NULL) AND
    ("data" = ANY($5) OR $5 IS NULL) AND
    ("is_default" = ANY($6) OR $6 IS NULL) AND
    ("date_created" = ANY($7) OR $7 IS NULL) AND
    ("date_created" > $8 OR $8 IS NULL) AND
    ("date_created" < $9 OR $9 IS NULL) AND
    ("date_updated" = ANY($10) OR $10 IS NULL) AND
    ("date_updated" > $11 OR $11 IS NULL) AND
    ("date_updated" < $12 OR $12 IS NULL)
)
ORDER BY "id"
LIMIT $14::int
OFFSET $13::int
`

type ListCountPaymentMethodParams struct {
	ID              []uuid.UUID       `json:"id"`
	AccountID       []uuid.UUID       `json:"account_id"`
	Type            []string          `json:"type"`
	Label           []string          `json:"label"`
	Data            []json.RawMessage `json:"data"`
	IsDefault       []bool            `json:"is_default"`
	DateCreated     []time.Time       `json:"date_created"`
	DateCreatedFrom null.Time         `json:"date_created_from"`
	DateCreatedTo   null.Time         `json:"date_created_to"`
	DateUpdated     []time.Time       `json:"date_updated"`
	DateUpdatedFrom null.Time         `json:"date_updated_from"`
	DateUpdatedTo   null.Time         `json:"date_updated_to"`
	Offset          null.Int32        `json:"offset"`
	Limit           null.Int32        `json:"limit"`
}

type ListCountPaymentMethodRow struct {
	AccountPaymentMethod AccountPaymentMethod `json:"account_payment_method"`
	TotalCount           int64                `json:"total_count"`
}

func (q *Queries) ListCountPaymentMethod(ctx context.Context, arg ListCountPaymentMethodParams) ([]ListCountPaymentMethodRow, error) {
	rows, err := q.db.Query(ctx, listCountPaymentMethod,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountPaymentMethodRow{}
	for rows.Next() {
		var i ListCountPaymentMethodRow
		if err := rows.Scan(
			&i.AccountPaymentMethod.ID,
			&i.AccountPaymentMethod.AccountID,
			&i.AccountPaymentMethod.Type,
			&i.AccountPaymentMethod.Label,
			&i.AccountPaymentMethod.Data,
			&i.AccountPaymentMethod.IsDefault,
			&i.AccountPaymentMethod.DateCreated,
			&i.AccountPaymentMethod.DateUpdated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethod = `-- name: ListPaymentMethod :many
SELECT id, account_id, type, label, data, is_default, date_created, date_updated
FROM "account"."payment_method"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("type" = ANY($3) OR $3 IS NULL) AND
    ("label" = ANY($4) OR $4 IS NULL) AND
    ("data" = ANY($5) OR $5 IS NULL) AND
    ("is_default" = ANY($6) OR $6 IS NULL) AND
    ("date_created" = ANY($7) OR $7 IS NULL) AND
    ("date_created" > $8 OR $8 IS NULL) AND
    ("date_created" < $9 OR $9 IS NULL) AND
    ("date_updated" = ANY($10) OR $10 IS NULL) AND
    ("date_updated" > $11 OR $11 IS NULL) AND
    ("date_updated" < $12 OR $12 IS NULL)
)
ORDER BY "id"
LIMIT $14::int
OFFSET $13::int
`

type ListPaymentMethodParams struct {
	ID              []uuid.UUID       `json:"id"`
	AccountID       []uuid.UUID       `json:"account_id"`
	Type            []string          `json:"type"`
	Label           []string          `json:"label"`
	Data            []json.RawMessage `json:"data"`
	IsDefault       []bool            `json:"is_default"`
	DateCreated     []time.Time       `json:"date_created"`
	DateCreatedFrom null.Time         `json:"date_created_from"`
	DateCreatedTo   null.Time         `json:"date_created_to"`
	DateUpdated     []time.Time       `json:"date_updated"`
	DateUpdatedFrom null.Time         `json:"date_updated_from"`
	DateUpdatedTo   null.Time         `json:"date_updated_to"`
	Offset          null.Int32        `json:"offset"`
	Limit           null.Int32        `json:"limit"`
}

func (q *Queries) ListPaymentMethod(ctx context.Context, arg ListPaymentMethodParams) ([]AccountPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethod,
		arg.ID,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountPaymentMethod{}
	for rows.Next() {
		var i AccountPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Label,
			&i.Data,
			&i.IsDefault,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE "account"."payment_method"
SET "account_id" = COALESCE($1, "account_id"),
    "type" = COALESCE($2, "type"),
    "label" = COALESCE($3, "label"),
    "data" = COALESCE($4, "data"),
    "is_default" = COALESCE($5, "is_default"),
    "date_created" = COALESCE($6, "date_created"),
    "date_updated" = COALESCE($7, "date_updated")
WHERE id = $8
RETURNING id, account_id, type, label, data, is_default, date_created, date_updated
`

type UpdatePaymentMethodParams struct {
	AccountID   uuid.NullUUID   `json:"account_id"`
	Type        null.String     `json:"type"`
	Label       null.String     `json:"label"`
	Data        json.RawMessage `json:"data"`
	IsDefault   null.Bool       `json:"is_default"`
	DateCreated null.Time       `json:"date_created"`
	DateUpdated null.Time       `json:"date_updated"`
	ID          uuid.UUID       `json:"id"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (AccountPaymentMethod, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.AccountID,
		arg.Type,
		arg.Label,
		arg.Data,
		arg.IsDefault,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i AccountPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Label,
		&i.Data,
		&i.IsDefault,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}
