// Code generated by genrestate; DO NOT EDIT.

package analyticbiz

import (
	"context"
	"github.com/google/uuid"
	restateclient "shopnexus-server/internal/infras/restate"
	analyticdb "shopnexus-server/internal/module/analytic/db/sqlc"
	analyticmodel "shopnexus-server/internal/module/analytic/model"
	sharedmodel "shopnexus-server/internal/shared/model"
)

const serviceName = "Analytic"

// AnalyticRestateClient implements AnalyticBiz via Restate HTTP ingress.
type AnalyticRestateClient struct {
	client *restateclient.Client
}

var _ AnalyticBiz = (*AnalyticRestateClient)(nil)

func NewAnalyticRestateClient(restateIngressURL string) *AnalyticRestateClient {
	return &AnalyticRestateClient{client: restateclient.NewClient(restateIngressURL)}
}

func (p *AnalyticRestateClient) CreateInteraction(ctx context.Context, params CreateInteractionParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "CreateInteraction", params)
}

func (p *AnalyticRestateClient) HandlePopularityEvent(ctx context.Context, event analyticmodel.Interaction) error {
	return restateclient.Send(ctx, p.client, serviceName, "HandlePopularityEvent", event)
}

func (p *AnalyticRestateClient) GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error) {
	return restateclient.Call[analyticdb.AnalyticProductPopularity](ctx, p.client, serviceName, "GetProductPopularity", spuID)
}

func (p *AnalyticRestateClient) ListTopProductPopularity(ctx context.Context, params sharedmodel.PaginationParams) ([]analyticdb.AnalyticProductPopularity, error) {
	return restateclient.Call[[]analyticdb.AnalyticProductPopularity](ctx, p.client, serviceName, "ListTopProductPopularity", params)
}

func (p *AnalyticRestateClient) GetSellerDashboard(ctx context.Context, params analyticmodel.GetSellerDashboardParams) (analyticmodel.SellerDashboard, error) {
	return restateclient.Call[analyticmodel.SellerDashboard](ctx, p.client, serviceName, "GetSellerDashboard", params)
}
