port: "5005"

log:
  level: debug
  format: json
  addSource: true
  timeFormat: "2006-01-02 15:04:05"

restate:
  ingressAddress: "http://localhost:8080"
  adminAddress: "http://localhost:9470"
  serviceHost: "http://host.docker.internal"
  servicePort: "8082"
