// Code generated by genrestate; DO NOT EDIT.

package accountbiz

import (
	"context"
	restateclient "shopnexus-server/internal/infras/restate"
	accountdb "shopnexus-server/internal/module/account/db/sqlc"
	accountmodel "shopnexus-server/internal/module/account/model"
	sharedmodel "shopnexus-server/internal/shared/model"

	"github.com/google/uuid"
)

const serviceName = "AccountBiz"

// AccountBizProxy implements AccountClient via Restate HTTP ingress.
type AccountBizProxy struct {
	client *restateclient.Client
}

var _ AccountClient = (*AccountBizProxy)(nil)

func NewAccountBizProxy(restateIngressURL string) *AccountBizProxy {
	return &AccountBizProxy{client: restateclient.NewClient(restateIngressURL)}
}

func (p *AccountBizProxy) Login(ctx context.Context, params LoginParams) (LoginResult, error) {
	return restateclient.Call[LoginResult](ctx, p.client, serviceName, "Login", params)
}

func (p *AccountBizProxy) Register(ctx context.Context, params RegisterParams) (RegisterResult, error) {
	return restateclient.Call[RegisterResult](ctx, p.client, serviceName, "Register", params)
}

func (p *AccountBizProxy) Refresh(ctx context.Context, refreshToken string) (RefreshResult, error) {
	return restateclient.Call[RefreshResult](ctx, p.client, serviceName, "Refresh", refreshToken)
}

func (p *AccountBizProxy) GetProfile(ctx context.Context, params GetProfileParams) (accountmodel.Profile, error) {
	return restateclient.Call[accountmodel.Profile](ctx, p.client, serviceName, "GetProfile", params)
}

func (p *AccountBizProxy) ListProfile(ctx context.Context, params ListProfileParams) (sharedmodel.PaginateResult[accountmodel.Profile], error) {
	return restateclient.Call[sharedmodel.PaginateResult[accountmodel.Profile]](ctx, p.client, serviceName, "ListProfile", params)
}

func (p *AccountBizProxy) UpdateProfile(ctx context.Context, params UpdateProfileParams) (accountmodel.Profile, error) {
	return restateclient.Call[accountmodel.Profile](ctx, p.client, serviceName, "UpdateProfile", params)
}

func (p *AccountBizProxy) DeleteAccount(ctx context.Context, params DeleteAccountParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeleteAccount", params)
}

func (p *AccountBizProxy) ListContact(ctx context.Context, params ListContactParams) ([]accountdb.AccountContact, error) {
	return restateclient.Call[[]accountdb.AccountContact](ctx, p.client, serviceName, "ListContact", params)
}

func (p *AccountBizProxy) GetContact(ctx context.Context, params GetContactParams) (accountdb.AccountContact, error) {
	return restateclient.Call[accountdb.AccountContact](ctx, p.client, serviceName, "GetContact", params)
}

func (p *AccountBizProxy) CreateContact(ctx context.Context, params CreateContactParams) (accountdb.AccountContact, error) {
	return restateclient.Call[accountdb.AccountContact](ctx, p.client, serviceName, "CreateContact", params)
}

func (p *AccountBizProxy) UpdateContact(ctx context.Context, params UpdateContactParams) (accountdb.AccountContact, error) {
	return restateclient.Call[accountdb.AccountContact](ctx, p.client, serviceName, "UpdateContact", params)
}

func (p *AccountBizProxy) DeleteContact(ctx context.Context, params DeleteContactParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeleteContact", params)
}

func (p *AccountBizProxy) GetDefaultContact(ctx context.Context, accountIDs []uuid.UUID) (map[uuid.UUID]accountdb.AccountContact, error) {
	return restateclient.Call[map[uuid.UUID]accountdb.AccountContact](ctx, p.client, serviceName, "GetDefaultContact", accountIDs)
}

func (p *AccountBizProxy) AddFavorite(ctx context.Context, params AddFavoriteParams) (accountdb.AccountFavorite, error) {
	return restateclient.Call[accountdb.AccountFavorite](ctx, p.client, serviceName, "AddFavorite", params)
}

func (p *AccountBizProxy) RemoveFavorite(ctx context.Context, params RemoveFavoriteParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "RemoveFavorite", params)
}

func (p *AccountBizProxy) ListFavorite(ctx context.Context, params ListFavoriteParams) (sharedmodel.PaginateResult[accountdb.AccountFavorite], error) {
	return restateclient.Call[sharedmodel.PaginateResult[accountdb.AccountFavorite]](ctx, p.client, serviceName, "ListFavorite", params)
}

func (p *AccountBizProxy) CreatePaymentMethod(ctx context.Context, params CreatePaymentMethodParams) (accountdb.AccountPaymentMethod, error) {
	return restateclient.Call[accountdb.AccountPaymentMethod](ctx, p.client, serviceName, "CreatePaymentMethod", params)
}

func (p *AccountBizProxy) ListPaymentMethod(ctx context.Context, params ListPaymentMethodParams) (sharedmodel.PaginateResult[accountdb.AccountPaymentMethod], error) {
	return restateclient.Call[sharedmodel.PaginateResult[accountdb.AccountPaymentMethod]](ctx, p.client, serviceName, "ListPaymentMethod", params)
}

func (p *AccountBizProxy) UpdatePaymentMethod(ctx context.Context, params UpdatePaymentMethodParams) (accountdb.AccountPaymentMethod, error) {
	return restateclient.Call[accountdb.AccountPaymentMethod](ctx, p.client, serviceName, "UpdatePaymentMethod", params)
}

func (p *AccountBizProxy) DeletePaymentMethod(ctx context.Context, params DeletePaymentMethodParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeletePaymentMethod", params)
}

func (p *AccountBizProxy) SetDefaultPaymentMethod(ctx context.Context, params SetDefaultPaymentMethodParams) (accountdb.AccountPaymentMethod, error) {
	return restateclient.Call[accountdb.AccountPaymentMethod](ctx, p.client, serviceName, "SetDefaultPaymentMethod", params)
}
