postgres:
  host: localhost
  port: 5432
  username: shopnexus
  password: peakshopnexuspassword
  database: shopnexus
  maxConnections: 50
  maxIdleConnections: 10
  maxConnIdleTime: 300
  logQuery: true
  allowNestedTransactions: true

redis:
  host: localhost
  port: "6379"
  password: "peaksehopnexuspassword"
  db: 0

log:
  level: debug
  format: json
  addSource: true
  timeFormat: "2006-01-02 15:04:05"

restate:
  ingressAddress: "http://localhost:8080"
  adminAddress: "http://localhost:9470"
  serviceHost: "http://host.docker.internal"
  servicePort: "8082"
