// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate.sql

package commondb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExchangeRatesByBase = `-- name: GetExchangeRatesByBase :many
SELECT "base", "target", "rate", "fetched_at"
FROM "common"."exchange_rate"
WHERE "base" = $1
ORDER BY "target"
`

type GetExchangeRatesByBaseRow struct {
	Base      string         `json:"base"`
	Target    string         `json:"target"`
	Rate      pgtype.Numeric `json:"rate"`
	FetchedAt time.Time      `json:"fetched_at"`
}

func (q *Queries) GetExchangeRatesByBase(ctx context.Context, base string) ([]GetExchangeRatesByBaseRow, error) {
	rows, err := q.db.Query(ctx, getExchangeRatesByBase, base)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExchangeRatesByBaseRow{}
	for rows.Next() {
		var i GetExchangeRatesByBaseRow
		if err := rows.Scan(
			&i.Base,
			&i.Target,
			&i.Rate,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO "common"."exchange_rate" ("base", "target", "rate", "fetched_at")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("base", "target") DO UPDATE
SET "rate" = EXCLUDED."rate",
    "fetched_at" = EXCLUDED."fetched_at",
    "date_updated" = CURRENT_TIMESTAMP
`

type UpsertExchangeRateParams struct {
	Base      string         `json:"base"`
	Target    string         `json:"target"`
	Rate      pgtype.Numeric `json:"rate"`
	FetchedAt time.Time      `json:"fetched_at"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.Base,
		arg.Target,
		arg.Rate,
		arg.FetchedAt,
	)
	return err
}
