// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package commondb

import (
	"context"

	null "github.com/guregu/null/v6"
)

type Querier interface {
	CountOption(ctx context.Context, arg CountOptionParams) (int64, error)
	CountResource(ctx context.Context, arg CountResourceParams) (int64, error)
	CountResourceReference(ctx context.Context, arg CountResourceReferenceParams) (int64, error)
	CreateBatchOption(ctx context.Context, arg []CreateBatchOptionParams) *CreateBatchOptionBatchResults
	CreateBatchResource(ctx context.Context, arg []CreateBatchResourceParams) *CreateBatchResourceBatchResults
	CreateBatchResourceReference(ctx context.Context, arg []CreateBatchResourceReferenceParams) *CreateBatchResourceReferenceBatchResults
	CreateCopyDefaultOption(ctx context.Context, arg []CreateCopyDefaultOptionParams) (int64, error)
	CreateCopyDefaultResource(ctx context.Context, arg []CreateCopyDefaultResourceParams) (int64, error)
	CreateCopyDefaultResourceReference(ctx context.Context, arg []CreateCopyDefaultResourceReferenceParams) (int64, error)
	CreateCopyOption(ctx context.Context, arg []CreateCopyOptionParams) (int64, error)
	CreateCopyResource(ctx context.Context, arg []CreateCopyResourceParams) (int64, error)
	CreateCopyResourceReference(ctx context.Context, arg []CreateCopyResourceReferenceParams) (int64, error)
	CreateDefaultOption(ctx context.Context, arg CreateDefaultOptionParams) (CommonOption, error)
	CreateDefaultResource(ctx context.Context, arg CreateDefaultResourceParams) (CommonResource, error)
	CreateDefaultResourceReference(ctx context.Context, arg CreateDefaultResourceReferenceParams) (CommonResourceReference, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (CommonOption, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (CommonResource, error)
	CreateResourceReference(ctx context.Context, arg CreateResourceReferenceParams) (CommonResourceReference, error)
	DeleteOption(ctx context.Context, arg DeleteOptionParams) error
	DeleteResource(ctx context.Context, arg DeleteResourceParams) error
	DeleteResourceReference(ctx context.Context, arg DeleteResourceReferenceParams) error
	// ========================================
	// Queries for table: common.option
	// ========================================
	GetOption(ctx context.Context, id null.String) (CommonOption, error)
	// Code generated by pgtempl. DO NOT EDIT.
	// This file contains all queries for the database schema.
	// ========================================
	// Queries for table: common.resource
	// ========================================
	GetResource(ctx context.Context, arg GetResourceParams) (CommonResource, error)
	// ========================================
	// Queries for table: common.resource_reference
	// ========================================
	GetResourceReference(ctx context.Context, id null.Int) (CommonResourceReference, error)
	ListCountOption(ctx context.Context, arg ListCountOptionParams) ([]ListCountOptionRow, error)
	ListCountResource(ctx context.Context, arg ListCountResourceParams) ([]ListCountResourceRow, error)
	ListCountResourceReference(ctx context.Context, arg ListCountResourceReferenceParams) ([]ListCountResourceReferenceRow, error)
	ListOption(ctx context.Context, arg ListOptionParams) ([]CommonOption, error)
	ListResource(ctx context.Context, arg ListResourceParams) ([]CommonResource, error)
	ListResourceReference(ctx context.Context, arg ListResourceReferenceParams) ([]CommonResourceReference, error)
	ListSortedOption(ctx context.Context, arg ListSortedOptionParams) ([]CommonOption, error)
	ListSortedResources(ctx context.Context, arg ListSortedResourcesParams) ([]ListSortedResourcesRow, error)
	UpdateOption(ctx context.Context, arg UpdateOptionParams) (CommonOption, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (CommonResource, error)
	UpdateResourceReference(ctx context.Context, arg UpdateResourceReferenceParams) (CommonResourceReference, error)
	UpsertOption(ctx context.Context, arg UpsertOptionParams) error
}

var _ Querier = (*Queries)(nil)
