// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package systemdb

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createBatchOutboxEvent = `-- name: CreateBatchOutboxEvent :batchone
INSERT INTO "system"."outbox_event" ("topic", "data", "processed", "date_processed", "date_created")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, topic, data, processed, date_processed, date_created
`

type CreateBatchOutboxEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchOutboxEventParams struct {
	Topic         string          `json:"topic"`
	Data          json.RawMessage `json:"data"`
	Processed     bool            `json:"processed"`
	DateProcessed null.Time       `json:"date_processed"`
	DateCreated   time.Time       `json:"date_created"`
}

func (q *Queries) CreateBatchOutboxEvent(ctx context.Context, arg []CreateBatchOutboxEventParams) *CreateBatchOutboxEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Topic,
			a.Data,
			a.Processed,
			a.DateProcessed,
			a.DateCreated,
		}
		batch.Queue(createBatchOutboxEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchOutboxEventBatchResults{br, len(arg), false}
}

func (b *CreateBatchOutboxEventBatchResults) QueryRow(f func(int, SystemOutboxEvent, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i SystemOutboxEvent
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Topic,
			&i.Data,
			&i.Processed,
			&i.DateProcessed,
			&i.DateCreated,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchOutboxEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
