// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package systemdb

import (
	"context"
)

// iteratorForCreateCopyDefaultOutboxEvent implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOutboxEvent struct {
	rows                 []CreateCopyDefaultOutboxEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOutboxEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOutboxEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Topic,
		r.rows[0].Data,
		r.rows[0].DateProcessed,
	}, nil
}

func (r iteratorForCreateCopyDefaultOutboxEvent) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOutboxEvent(ctx context.Context, arg []CreateCopyDefaultOutboxEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "outbox_event"}, []string{"topic", "data", "date_processed"}, &iteratorForCreateCopyDefaultOutboxEvent{rows: arg})
}

// iteratorForCreateCopyOutboxEvent implements pgx.CopyFromSource.
type iteratorForCreateCopyOutboxEvent struct {
	rows                 []CreateCopyOutboxEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOutboxEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOutboxEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Topic,
		r.rows[0].Data,
		r.rows[0].Processed,
		r.rows[0].DateProcessed,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyOutboxEvent) Err() error {
	return nil
}

func (q *Queries) CreateCopyOutboxEvent(ctx context.Context, arg []CreateCopyOutboxEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "outbox_event"}, []string{"topic", "data", "processed", "date_processed", "date_created"}, &iteratorForCreateCopyOutboxEvent{rows: arg})
}
