-- Code generated by pgtempl. DO NOT EDIT.
-- Queries for table: catalog.tag

-- name: GetTag :one
SELECT *
FROM "catalog"."tag"
WHERE ("id" = sqlc.narg('id'));

-- name: CountTag :one
SELECT COUNT(*)
FROM "catalog"."tag"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL)
);

-- name: ListTag :many
SELECT *
FROM "catalog"."tag"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountTag :many
SELECT sqlc.embed(embed_tag), COUNT(*) OVER() as total_count
FROM "catalog"."tag" embed_tag
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateTag :one
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2)
RETURNING *;

-- name: CreateBatchTag :batchone
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2)
RETURNING *;

-- name: CreateCopyTag :copyfrom
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2);

-- name: CreateDefaultTag :one
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2)
RETURNING *;

-- name: CreateCopyDefaultTag :copyfrom
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2);

-- name: UpdateTag :one
UPDATE "catalog"."tag"
SET "description" = CASE WHEN sqlc.arg('null_description')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('description'), "description") END
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteTag :exec
DELETE FROM "catalog"."tag"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL)
);