// Code generated by genrestate; DO NOT EDIT.

package catalogbiz

import (
	"context"
	restateclient "shopnexus-server/internal/infras/restate"
	catalogdb "shopnexus-server/internal/module/catalog/db/sqlc"
	catalogmodel "shopnexus-server/internal/module/catalog/model"
	sharedmodel "shopnexus-server/internal/shared/model"
)

const serviceName = "CatalogBiz"

// CatalogBizProxy implements CatalogClient via Restate HTTP ingress.
type CatalogBizProxy struct {
	client *restateclient.Client
}

var _ CatalogClient = (*CatalogBizProxy)(nil)

func NewCatalogBizProxy(restateIngressURL string) *CatalogBizProxy {
	return &CatalogBizProxy{client: restateclient.NewClient(restateIngressURL)}
}

func (p *CatalogBizProxy) GetProductDetail(ctx context.Context, params GetProductDetailParams) (catalogmodel.ProductDetail, error) {
	return restateclient.Call[catalogmodel.ProductDetail](ctx, p.client, serviceName, "GetProductDetail", params)
}

func (p *CatalogBizProxy) GetProductCard(ctx context.Context, params GetProductCardParams) (*catalogmodel.ProductCard, error) {
	return restateclient.Call[*catalogmodel.ProductCard](ctx, p.client, serviceName, "GetProductCard", params)
}

func (p *CatalogBizProxy) ListProductCard(ctx context.Context, params ListProductCardParams) (sharedmodel.PaginateResult[catalogmodel.ProductCard], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogmodel.ProductCard]](ctx, p.client, serviceName, "ListProductCard", params)
}

func (p *CatalogBizProxy) ListRecommendedProductCard(ctx context.Context, params ListRecommendedProductCardParams) ([]catalogmodel.ProductCard, error) {
	return restateclient.Call[[]catalogmodel.ProductCard](ctx, p.client, serviceName, "ListRecommendedProductCard", params)
}

func (p *CatalogBizProxy) GetProductSpu(ctx context.Context, params GetProductSpuParams) (catalogmodel.ProductSpu, error) {
	return restateclient.Call[catalogmodel.ProductSpu](ctx, p.client, serviceName, "GetProductSpu", params)
}

func (p *CatalogBizProxy) ListProductSpu(ctx context.Context, params ListProductSpuParams) (sharedmodel.PaginateResult[catalogmodel.ProductSpu], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogmodel.ProductSpu]](ctx, p.client, serviceName, "ListProductSpu", params)
}

func (p *CatalogBizProxy) CreateProductSpu(ctx context.Context, params CreateProductSpuParams) (catalogmodel.ProductSpu, error) {
	return restateclient.Call[catalogmodel.ProductSpu](ctx, p.client, serviceName, "CreateProductSpu", params)
}

func (p *CatalogBizProxy) UpdateProductSpu(ctx context.Context, params UpdateProductSpuParams) (catalogmodel.ProductSpu, error) {
	return restateclient.Call[catalogmodel.ProductSpu](ctx, p.client, serviceName, "UpdateProductSpu", params)
}

func (p *CatalogBizProxy) DeleteProductSpu(ctx context.Context, params DeleteProductSpuParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeleteProductSpu", params)
}

func (p *CatalogBizProxy) ListProductSku(ctx context.Context, params ListProductSkuParams) ([]catalogmodel.ProductSku, error) {
	return restateclient.Call[[]catalogmodel.ProductSku](ctx, p.client, serviceName, "ListProductSku", params)
}

func (p *CatalogBizProxy) CreateProductSku(ctx context.Context, params CreateProductSkuParams) (catalogmodel.ProductSku, error) {
	return restateclient.Call[catalogmodel.ProductSku](ctx, p.client, serviceName, "CreateProductSku", params)
}

func (p *CatalogBizProxy) UpdateProductSku(ctx context.Context, params UpdateProductSkuParams) (catalogmodel.ProductSku, error) {
	return restateclient.Call[catalogmodel.ProductSku](ctx, p.client, serviceName, "UpdateProductSku", params)
}

func (p *CatalogBizProxy) DeleteProductSku(ctx context.Context, params DeleteProductSkuParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeleteProductSku", params)
}

func (p *CatalogBizProxy) ListComment(ctx context.Context, params ListCommentParams) (sharedmodel.PaginateResult[catalogmodel.Comment], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogmodel.Comment]](ctx, p.client, serviceName, "ListComment", params)
}

func (p *CatalogBizProxy) CreateComment(ctx context.Context, params CreateCommentParams) (catalogmodel.Comment, error) {
	return restateclient.Call[catalogmodel.Comment](ctx, p.client, serviceName, "CreateComment", params)
}

func (p *CatalogBizProxy) UpdateComment(ctx context.Context, params UpdateCommentParams) (catalogmodel.Comment, error) {
	return restateclient.Call[catalogmodel.Comment](ctx, p.client, serviceName, "UpdateComment", params)
}

func (p *CatalogBizProxy) DeleteComment(ctx context.Context, params DeleteCommentParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeleteComment", params)
}

func (p *CatalogBizProxy) ListTag(ctx context.Context, params ListTagParams) (sharedmodel.PaginateResult[catalogdb.CatalogTag], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogdb.CatalogTag]](ctx, p.client, serviceName, "ListTag", params)
}

func (p *CatalogBizProxy) GetTag(ctx context.Context, params GetTagParams) (catalogdb.CatalogTag, error) {
	return restateclient.Call[catalogdb.CatalogTag](ctx, p.client, serviceName, "GetTag", params)
}

func (p *CatalogBizProxy) ListBrand(ctx context.Context, params ListBrandParams) (sharedmodel.PaginateResult[catalogdb.CatalogBrand], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogdb.CatalogBrand]](ctx, p.client, serviceName, "ListBrand", params)
}

func (p *CatalogBizProxy) ListCategory(ctx context.Context, params ListCategoryParams) (sharedmodel.PaginateResult[catalogdb.CatalogCategory], error) {
	return restateclient.Call[sharedmodel.PaginateResult[catalogdb.CatalogCategory]](ctx, p.client, serviceName, "ListCategory", params)
}

func (p *CatalogBizProxy) Search(ctx context.Context, params SearchParams) ([]catalogmodel.ProductRecommend, error) {
	return restateclient.Call[[]catalogmodel.ProductRecommend](ctx, p.client, serviceName, "Search", params)
}

func (p *CatalogBizProxy) GetRecommendations(ctx context.Context, params GetRecommendationsParams) ([]catalogmodel.ProductRecommend, error) {
	return restateclient.Call[[]catalogmodel.ProductRecommend](ctx, p.client, serviceName, "GetRecommendations", params)
}
