// Code generated by genrestate; DO NOT EDIT.

package inventorybiz

import (
	"context"
	restateclient "shopnexus-server/internal/infras/restate"
	inventorydb "shopnexus-server/internal/module/inventory/db/sqlc"
	sharedmodel "shopnexus-server/internal/shared/model"
)

const serviceName = "Inventory"

// InventoryRestateClient implements InventoryBiz via Restate HTTP ingress.
type InventoryRestateClient struct {
	client *restateclient.Client
}

var _ InventoryBiz = (*InventoryRestateClient)(nil)

func NewInventoryRestateClient(restateIngressURL string) *InventoryRestateClient {
	return &InventoryRestateClient{client: restateclient.NewClient(restateIngressURL)}
}

func (p *InventoryRestateClient) GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error) {
	return restateclient.Call[inventorydb.InventoryStock](ctx, p.client, serviceName, "GetStock", params)
}

func (p *InventoryRestateClient) ListStock(ctx context.Context, params ListStockParams) (sharedmodel.PaginateResult[inventorydb.InventoryStock], error) {
	return restateclient.Call[sharedmodel.PaginateResult[inventorydb.InventoryStock]](ctx, p.client, serviceName, "ListStock", params)
}

func (p *InventoryRestateClient) CreateStock(ctx context.Context, params CreateStockParams) (inventorydb.InventoryStock, error) {
	return restateclient.Call[inventorydb.InventoryStock](ctx, p.client, serviceName, "CreateStock", params)
}

func (p *InventoryRestateClient) ListStockHistory(ctx context.Context, params ListStockHistoryParams) (sharedmodel.PaginateResult[inventorydb.InventoryStockHistory], error) {
	return restateclient.Call[sharedmodel.PaginateResult[inventorydb.InventoryStockHistory]](ctx, p.client, serviceName, "ListStockHistory", params)
}

func (p *InventoryRestateClient) ImportStock(ctx context.Context, params ImportStockParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "ImportStock", params)
}

func (p *InventoryRestateClient) ReserveInventory(ctx context.Context, params ReserveInventoryParams) ([]ReserveInventoryResult, error) {
	return restateclient.Call[[]ReserveInventoryResult](ctx, p.client, serviceName, "ReserveInventory", params)
}

func (p *InventoryRestateClient) ReleaseInventory(ctx context.Context, params ReleaseInventoryParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "ReleaseInventory", params)
}

func (p *InventoryRestateClient) UpdateSerial(ctx context.Context, params UpdateSerialParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "UpdateSerial", params)
}

func (p *InventoryRestateClient) ListSerial(ctx context.Context, params ListSerialParams) (sharedmodel.PaginateResult[inventorydb.InventorySerial], error) {
	return restateclient.Call[sharedmodel.PaginateResult[inventorydb.InventorySerial]](ctx, p.client, serviceName, "ListSerial", params)
}

func (p *InventoryRestateClient) ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error) {
	return restateclient.Call[[]inventorydb.InventoryStock](ctx, p.client, serviceName, "ListMostTakenSku", params)
}
