log:
  level: debug
  format: json
  addSource: true
  timeFormat: "2006-01-02 15:04:05"

restate:
  ingressAddress: "http://localhost:8080"
  adminAddress: "http://localhost:9470"
  serviceHost: "http://host.docker.internal"
  servicePort: "8082"

postgres:
  host: localhost
  port: 5432
  username: shopnexus
  password: peakshopnexuspassword
  database: shopnexus
  maxConnections: 50
  maxIdleConnections: 10
  maxConnIdleTime: 300
  logQuery: true
  allowNestedTransactions: true

redis:
  host: localhost
  port: "6379"
  password: "peaksehopnexuspassword"
  db: 0

exchange:
  base: USD
  supported:
    [USD, VND, JPY, KRW, EUR, GBP, CNY, SGD, THB, AUD, IDR, MXN, COP, CLP]
  refreshInterval: 6h
  httpTimeout: 5s
  defaultUserCurrency: VND
  upstreamURL: https://api.currencyapi.com/v3
  apiKey: ""

filestore:
  type: s3
  presignedDefaultTTL: 1800
  placeholder404Url: ""
  s3:
    accessKeyID: ""
    secretAccessKey: ""
    region: ""
    bucket: ""
    cloudfrontUrl: ""
