// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package inventorydb

import (
	"context"
)

// iteratorForCreateCopyDefaultSerial implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultSerial struct {
	rows                 []CreateCopyDefaultSerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultSerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultSerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RefType,
		r.rows[0].RefID,
	}, nil
}

func (r iteratorForCreateCopyDefaultSerial) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultSerial(ctx context.Context, arg []CreateCopyDefaultSerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "serial"}, []string{"id", "ref_type", "ref_id"}, &iteratorForCreateCopyDefaultSerial{rows: arg})
}

// iteratorForCreateCopyDefaultStock implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultStock struct {
	rows                 []CreateCopyDefaultStockParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultStock) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultStock) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Stock,
	}, nil
}

func (r iteratorForCreateCopyDefaultStock) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultStock(ctx context.Context, arg []CreateCopyDefaultStockParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock"}, []string{"ref_type", "ref_id", "stock"}, &iteratorForCreateCopyDefaultStock{rows: arg})
}

// iteratorForCreateCopyDefaultStockHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultStockHistory struct {
	rows                 []CreateCopyDefaultStockHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultStockHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultStockHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StockID,
		r.rows[0].Change,
	}, nil
}

func (r iteratorForCreateCopyDefaultStockHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultStockHistory(ctx context.Context, arg []CreateCopyDefaultStockHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock_history"}, []string{"stock_id", "change"}, &iteratorForCreateCopyDefaultStockHistory{rows: arg})
}

// iteratorForCreateCopySerial implements pgx.CopyFromSource.
type iteratorForCreateCopySerial struct {
	rows                 []CreateCopySerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopySerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopySerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Status,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopySerial) Err() error {
	return nil
}

func (q *Queries) CreateCopySerial(ctx context.Context, arg []CreateCopySerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "serial"}, []string{"id", "ref_type", "ref_id", "status", "date_created"}, &iteratorForCreateCopySerial{rows: arg})
}

// iteratorForCreateCopyStock implements pgx.CopyFromSource.
type iteratorForCreateCopyStock struct {
	rows                 []CreateCopyStockParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyStock) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyStock) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Stock,
		r.rows[0].Taken,
		r.rows[0].SerialRequired,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyStock) Err() error {
	return nil
}

func (q *Queries) CreateCopyStock(ctx context.Context, arg []CreateCopyStockParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock"}, []string{"ref_type", "ref_id", "stock", "taken", "serial_required", "date_created"}, &iteratorForCreateCopyStock{rows: arg})
}

// iteratorForCreateCopyStockHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyStockHistory struct {
	rows                 []CreateCopyStockHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyStockHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyStockHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StockID,
		r.rows[0].Change,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyStockHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyStockHistory(ctx context.Context, arg []CreateCopyStockHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock_history"}, []string{"stock_id", "change", "date_created"}, &iteratorForCreateCopyStockHistory{rows: arg})
}
