// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package inventorydb

import (
	"context"

	null "github.com/guregu/null/v6"
)

const adjustInventory = `-- name: AdjustInventory :execrows
UPDATE inventory.stock
SET stock = stock - $1,
    taken = taken + $1
WHERE id = $2
  AND stock >= $1
`

type AdjustInventoryParams struct {
	Amount  int64 `json:"amount"`
	StockID int64 `json:"stock_id"`
}

func (q *Queries) AdjustInventory(ctx context.Context, arg AdjustInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, adjustInventory, arg.Amount, arg.StockID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailableSerials = `-- name: GetAvailableSerials :many
SELECT id, stock_id
FROM "inventory"."serial"
WHERE stock_id = $1 AND "status" = 'Active'
ORDER BY date_created DESC
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type GetAvailableSerialsParams struct {
	StockID int64 `json:"stock_id"`
	Amount  int32 `json:"amount"`
}

type GetAvailableSerialsRow struct {
	ID      string `json:"id"`
	StockID int64  `json:"stock_id"`
}

func (q *Queries) GetAvailableSerials(ctx context.Context, arg GetAvailableSerialsParams) ([]GetAvailableSerialsRow, error) {
	rows, err := q.db.Query(ctx, getAvailableSerials, arg.StockID, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableSerialsRow{}
	for rows.Next() {
		var i GetAvailableSerialsRow
		if err := rows.Scan(&i.ID, &i.StockID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMostTakenSku = `-- name: ListMostTakenSku :many
SELECT id, ref_type, ref_id, stock, taken, serial_required, date_created
FROM "inventory"."stock"
WHERE ref_type = $1
ORDER BY taken DESC
LIMIT $3::int
OFFSET $2::int
`

type ListMostTakenSkuParams struct {
	RefType InventoryStockRefType `json:"ref_type"`
	Offset  null.Int32            `json:"offset"`
	Limit   null.Int32            `json:"limit"`
}

func (q *Queries) ListMostTakenSku(ctx context.Context, arg ListMostTakenSkuParams) ([]InventoryStock, error) {
	rows, err := q.db.Query(ctx, listMostTakenSku, arg.RefType, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryStock{}
	for rows.Next() {
		var i InventoryStock
		if err := rows.Scan(
			&i.ID,
			&i.RefType,
			&i.RefID,
			&i.Stock,
			&i.Taken,
			&i.SerialRequired,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrentStock = `-- name: UpdateCurrentStock :exec
UPDATE "inventory"."stock"
SET "stock" = stock + $1
WHERE id = $2
`

type UpdateCurrentStockParams struct {
	Change int64 `json:"change"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateCurrentStock(ctx context.Context, arg UpdateCurrentStockParams) error {
	_, err := q.db.Exec(ctx, updateCurrentStock, arg.Change, arg.ID)
	return err
}

const updateSerialStatus = `-- name: UpdateSerialStatus :exec
UPDATE inventory.serial
SET status = $1
WHERE id = ANY($2)
`

type UpdateSerialStatusParams struct {
	Status InventoryStatus `json:"status"`
	ID     []string        `json:"id"`
}

func (q *Queries) UpdateSerialStatus(ctx context.Context, arg UpdateSerialStatusParams) error {
	_, err := q.db.Exec(ctx, updateSerialStatus, arg.Status, arg.ID)
	return err
}
