// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package inventorydb

import (
	"context"

	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustInventory(ctx context.Context, arg AdjustInventoryParams) (int64, error)
	CreateCopyDefaultSerial(ctx context.Context, arg []CreateCopyDefaultSerialParams) (int64, error)
	CreateDefaultStock(ctx context.Context, arg CreateDefaultStockParams) (InventoryStock, error)
	CreateDefaultStockHistory(ctx context.Context, arg CreateDefaultStockHistoryParams) (InventoryStockHistory, error)
	DeleteSerial(ctx context.Context, id []string) error
	DeleteStock(ctx context.Context, id []int64) error
	DeleteStockHistory(ctx context.Context, id []int64) error
	GetAvailableSerials(ctx context.Context, arg GetAvailableSerialsParams) ([]GetAvailableSerialsRow, error)
	GetSerial(ctx context.Context, id null.String) (InventorySerial, error)
	GetStock(ctx context.Context, arg GetStockParams) (InventoryStock, error)
	GetStockHistory(ctx context.Context, id pgtype.Int8) (InventoryStockHistory, error)
	ListCountSerial(ctx context.Context, arg ListCountSerialParams) ([]ListCountSerialRow, error)
	ListCountStock(ctx context.Context, arg ListCountStockParams) ([]ListCountStockRow, error)
	ListCountStockHistory(ctx context.Context, arg ListCountStockHistoryParams) ([]ListCountStockHistoryRow, error)
	ListMostTakenSku(ctx context.Context, arg ListMostTakenSkuParams) ([]InventoryStock, error)
	UpdateCurrentStock(ctx context.Context, arg UpdateCurrentStockParams) error
	UpdateSerial(ctx context.Context, arg UpdateSerialParams) (InventorySerial, error)
	UpdateSerialStatus(ctx context.Context, arg UpdateSerialStatusParams) error
	UpdateStock(ctx context.Context, arg UpdateStockParams) (InventoryStock, error)
}

var _ Querier = (*Queries)(nil)
