// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytic_interaction.sql

package analyticdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInteraction = `-- name: CountInteraction :one
SELECT COUNT(*)
FROM "analytic"."interaction"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("session_id" = ANY($3) OR $3 IS NULL) AND
    ("event_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_type" = ANY($5) OR $5 IS NULL) AND
    ("ref_type" > $6 OR $6 IS NULL) AND
    ("ref_type" < $7 OR $7 IS NULL) AND
    ("ref_id" = ANY($8) OR $8 IS NULL) AND
    ("metadata" = ANY($9) OR $9 IS NULL) AND
    ("user_agent" = ANY($10) OR $10 IS NULL) AND
    ("ip_address" = ANY($11) OR $11 IS NULL) AND
    ("date_created" = ANY($12) OR $12 IS NULL) AND
    ("date_created" > $13 OR $13 IS NULL) AND
    ("date_created" < $14 OR $14 IS NULL)
)
`

type CountInteractionParams struct {
	ID              []int64                        `json:"id"`
	AccountID       []uuid.NullUUID                `json:"account_id"`
	SessionID       []null.String                  `json:"session_id"`
	EventType       []string                       `json:"event_type"`
	RefType         []AnalyticInteractionRefType   `json:"ref_type"`
	RefTypeFrom     NullAnalyticInteractionRefType `json:"ref_type_from"`
	RefTypeTo       NullAnalyticInteractionRefType `json:"ref_type_to"`
	RefID           []string                       `json:"ref_id"`
	Metadata        []json.RawMessage              `json:"metadata"`
	UserAgent       []null.String                  `json:"user_agent"`
	IpAddress       []null.String                  `json:"ip_address"`
	DateCreated     []time.Time                    `json:"date_created"`
	DateCreatedFrom null.Time                      `json:"date_created_from"`
	DateCreatedTo   null.Time                      `json:"date_created_to"`
}

func (q *Queries) CountInteraction(ctx context.Context, arg CountInteractionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInteraction,
		arg.ID,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefTypeFrom,
		arg.RefTypeTo,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCopyDefaultInteractionParams struct {
	AccountID uuid.NullUUID              `json:"account_id"`
	SessionID null.String                `json:"session_id"`
	EventType string                     `json:"event_type"`
	RefType   AnalyticInteractionRefType `json:"ref_type"`
	RefID     string                     `json:"ref_id"`
	Metadata  json.RawMessage            `json:"metadata"`
	UserAgent null.String                `json:"user_agent"`
	IpAddress null.String                `json:"ip_address"`
}

type CreateCopyInteractionParams struct {
	AccountID   uuid.NullUUID              `json:"account_id"`
	SessionID   null.String                `json:"session_id"`
	EventType   string                     `json:"event_type"`
	RefType     AnalyticInteractionRefType `json:"ref_type"`
	RefID       string                     `json:"ref_id"`
	Metadata    json.RawMessage            `json:"metadata"`
	UserAgent   null.String                `json:"user_agent"`
	IpAddress   null.String                `json:"ip_address"`
	DateCreated time.Time                  `json:"date_created"`
}

const createDefaultInteraction = `-- name: CreateDefaultInteraction :one
INSERT INTO "analytic"."interaction" ("account_id", "session_id", "event_type", "ref_type", "ref_id", "metadata", "user_agent", "ip_address")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created, account_number
`

type CreateDefaultInteractionParams struct {
	AccountID uuid.NullUUID              `json:"account_id"`
	SessionID null.String                `json:"session_id"`
	EventType string                     `json:"event_type"`
	RefType   AnalyticInteractionRefType `json:"ref_type"`
	RefID     string                     `json:"ref_id"`
	Metadata  json.RawMessage            `json:"metadata"`
	UserAgent null.String                `json:"user_agent"`
	IpAddress null.String                `json:"ip_address"`
}

func (q *Queries) CreateDefaultInteraction(ctx context.Context, arg CreateDefaultInteractionParams) (AnalyticInteraction, error) {
	row := q.db.QueryRow(ctx, createDefaultInteraction,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AnalyticInteraction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionID,
		&i.EventType,
		&i.RefType,
		&i.RefID,
		&i.Metadata,
		&i.UserAgent,
		&i.IpAddress,
		&i.DateCreated,
		&i.AccountNumber,
	)
	return i, err
}

const createInteraction = `-- name: CreateInteraction :one
INSERT INTO "analytic"."interaction" ("account_id", "session_id", "event_type", "ref_type", "ref_id", "metadata", "user_agent", "ip_address", "date_created")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created, account_number
`

type CreateInteractionParams struct {
	AccountID   uuid.NullUUID              `json:"account_id"`
	SessionID   null.String                `json:"session_id"`
	EventType   string                     `json:"event_type"`
	RefType     AnalyticInteractionRefType `json:"ref_type"`
	RefID       string                     `json:"ref_id"`
	Metadata    json.RawMessage            `json:"metadata"`
	UserAgent   null.String                `json:"user_agent"`
	IpAddress   null.String                `json:"ip_address"`
	DateCreated time.Time                  `json:"date_created"`
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) (AnalyticInteraction, error) {
	row := q.db.QueryRow(ctx, createInteraction,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.DateCreated,
	)
	var i AnalyticInteraction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionID,
		&i.EventType,
		&i.RefType,
		&i.RefID,
		&i.Metadata,
		&i.UserAgent,
		&i.IpAddress,
		&i.DateCreated,
		&i.AccountNumber,
	)
	return i, err
}

const deleteInteraction = `-- name: DeleteInteraction :exec
DELETE FROM "analytic"."interaction"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("session_id" = ANY($3) OR $3 IS NULL) AND
    ("event_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_type" = ANY($5) OR $5 IS NULL) AND
    ("ref_type" > $6 OR $6 IS NULL) AND
    ("ref_type" < $7 OR $7 IS NULL) AND
    ("ref_id" = ANY($8) OR $8 IS NULL) AND
    ("metadata" = ANY($9) OR $9 IS NULL) AND
    ("user_agent" = ANY($10) OR $10 IS NULL) AND
    ("ip_address" = ANY($11) OR $11 IS NULL) AND
    ("date_created" = ANY($12) OR $12 IS NULL) AND
    ("date_created" > $13 OR $13 IS NULL) AND
    ("date_created" < $14 OR $14 IS NULL)
)
`

type DeleteInteractionParams struct {
	ID              []int64                        `json:"id"`
	AccountID       []uuid.NullUUID                `json:"account_id"`
	SessionID       []null.String                  `json:"session_id"`
	EventType       []string                       `json:"event_type"`
	RefType         []AnalyticInteractionRefType   `json:"ref_type"`
	RefTypeFrom     NullAnalyticInteractionRefType `json:"ref_type_from"`
	RefTypeTo       NullAnalyticInteractionRefType `json:"ref_type_to"`
	RefID           []string                       `json:"ref_id"`
	Metadata        []json.RawMessage              `json:"metadata"`
	UserAgent       []null.String                  `json:"user_agent"`
	IpAddress       []null.String                  `json:"ip_address"`
	DateCreated     []time.Time                    `json:"date_created"`
	DateCreatedFrom null.Time                      `json:"date_created_from"`
	DateCreatedTo   null.Time                      `json:"date_created_to"`
}

func (q *Queries) DeleteInteraction(ctx context.Context, arg DeleteInteractionParams) error {
	_, err := q.db.Exec(ctx, deleteInteraction,
		arg.ID,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefTypeFrom,
		arg.RefTypeTo,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
	)
	return err
}

const getInteraction = `-- name: GetInteraction :one
SELECT id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created, account_number
FROM "analytic"."interaction"
WHERE ("id" = $1)
`

func (q *Queries) GetInteraction(ctx context.Context, id pgtype.Int8) (AnalyticInteraction, error) {
	row := q.db.QueryRow(ctx, getInteraction, id)
	var i AnalyticInteraction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionID,
		&i.EventType,
		&i.RefType,
		&i.RefID,
		&i.Metadata,
		&i.UserAgent,
		&i.IpAddress,
		&i.DateCreated,
		&i.AccountNumber,
	)
	return i, err
}

const listCountInteraction = `-- name: ListCountInteraction :many
SELECT embed_interaction.id, embed_interaction.account_id, embed_interaction.session_id, embed_interaction.event_type, embed_interaction.ref_type, embed_interaction.ref_id, embed_interaction.metadata, embed_interaction.user_agent, embed_interaction.ip_address, embed_interaction.date_created, embed_interaction.account_number, COUNT(*) OVER() as total_count
FROM "analytic"."interaction" embed_interaction
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("session_id" = ANY($3) OR $3 IS NULL) AND
    ("event_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_type" = ANY($5) OR $5 IS NULL) AND
    ("ref_type" > $6 OR $6 IS NULL) AND
    ("ref_type" < $7 OR $7 IS NULL) AND
    ("ref_id" = ANY($8) OR $8 IS NULL) AND
    ("metadata" = ANY($9) OR $9 IS NULL) AND
    ("user_agent" = ANY($10) OR $10 IS NULL) AND
    ("ip_address" = ANY($11) OR $11 IS NULL) AND
    ("date_created" = ANY($12) OR $12 IS NULL) AND
    ("date_created" > $13 OR $13 IS NULL) AND
    ("date_created" < $14 OR $14 IS NULL)
)
ORDER BY "id"
LIMIT $16::int
OFFSET $15::int
`

type ListCountInteractionParams struct {
	ID              []int64                        `json:"id"`
	AccountID       []uuid.NullUUID                `json:"account_id"`
	SessionID       []null.String                  `json:"session_id"`
	EventType       []string                       `json:"event_type"`
	RefType         []AnalyticInteractionRefType   `json:"ref_type"`
	RefTypeFrom     NullAnalyticInteractionRefType `json:"ref_type_from"`
	RefTypeTo       NullAnalyticInteractionRefType `json:"ref_type_to"`
	RefID           []string                       `json:"ref_id"`
	Metadata        []json.RawMessage              `json:"metadata"`
	UserAgent       []null.String                  `json:"user_agent"`
	IpAddress       []null.String                  `json:"ip_address"`
	DateCreated     []time.Time                    `json:"date_created"`
	DateCreatedFrom null.Time                      `json:"date_created_from"`
	DateCreatedTo   null.Time                      `json:"date_created_to"`
	Offset          null.Int32                     `json:"offset"`
	Limit           null.Int32                     `json:"limit"`
}

type ListCountInteractionRow struct {
	AnalyticInteraction AnalyticInteraction `json:"analytic_interaction"`
	TotalCount          int64               `json:"total_count"`
}

func (q *Queries) ListCountInteraction(ctx context.Context, arg ListCountInteractionParams) ([]ListCountInteractionRow, error) {
	rows, err := q.db.Query(ctx, listCountInteraction,
		arg.ID,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefTypeFrom,
		arg.RefTypeTo,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountInteractionRow{}
	for rows.Next() {
		var i ListCountInteractionRow
		if err := rows.Scan(
			&i.AnalyticInteraction.ID,
			&i.AnalyticInteraction.AccountID,
			&i.AnalyticInteraction.SessionID,
			&i.AnalyticInteraction.EventType,
			&i.AnalyticInteraction.RefType,
			&i.AnalyticInteraction.RefID,
			&i.AnalyticInteraction.Metadata,
			&i.AnalyticInteraction.UserAgent,
			&i.AnalyticInteraction.IpAddress,
			&i.AnalyticInteraction.DateCreated,
			&i.AnalyticInteraction.AccountNumber,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInteraction = `-- name: ListInteraction :many
SELECT id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created, account_number
FROM "analytic"."interaction"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("session_id" = ANY($3) OR $3 IS NULL) AND
    ("event_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_type" = ANY($5) OR $5 IS NULL) AND
    ("ref_type" > $6 OR $6 IS NULL) AND
    ("ref_type" < $7 OR $7 IS NULL) AND
    ("ref_id" = ANY($8) OR $8 IS NULL) AND
    ("metadata" = ANY($9) OR $9 IS NULL) AND
    ("user_agent" = ANY($10) OR $10 IS NULL) AND
    ("ip_address" = ANY($11) OR $11 IS NULL) AND
    ("date_created" = ANY($12) OR $12 IS NULL) AND
    ("date_created" > $13 OR $13 IS NULL) AND
    ("date_created" < $14 OR $14 IS NULL)
)
ORDER BY "id"
LIMIT $16::int
OFFSET $15::int
`

type ListInteractionParams struct {
	ID              []int64                        `json:"id"`
	AccountID       []uuid.NullUUID                `json:"account_id"`
	SessionID       []null.String                  `json:"session_id"`
	EventType       []string                       `json:"event_type"`
	RefType         []AnalyticInteractionRefType   `json:"ref_type"`
	RefTypeFrom     NullAnalyticInteractionRefType `json:"ref_type_from"`
	RefTypeTo       NullAnalyticInteractionRefType `json:"ref_type_to"`
	RefID           []string                       `json:"ref_id"`
	Metadata        []json.RawMessage              `json:"metadata"`
	UserAgent       []null.String                  `json:"user_agent"`
	IpAddress       []null.String                  `json:"ip_address"`
	DateCreated     []time.Time                    `json:"date_created"`
	DateCreatedFrom null.Time                      `json:"date_created_from"`
	DateCreatedTo   null.Time                      `json:"date_created_to"`
	Offset          null.Int32                     `json:"offset"`
	Limit           null.Int32                     `json:"limit"`
}

func (q *Queries) ListInteraction(ctx context.Context, arg ListInteractionParams) ([]AnalyticInteraction, error) {
	rows, err := q.db.Query(ctx, listInteraction,
		arg.ID,
		arg.AccountID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefTypeFrom,
		arg.RefTypeTo,
		arg.RefID,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticInteraction{}
	for rows.Next() {
		var i AnalyticInteraction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SessionID,
			&i.EventType,
			&i.RefType,
			&i.RefID,
			&i.Metadata,
			&i.UserAgent,
			&i.IpAddress,
			&i.DateCreated,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInteraction = `-- name: UpdateInteraction :one
UPDATE "analytic"."interaction"
SET "account_id" = CASE WHEN $1::bool = TRUE THEN NULL ELSE COALESCE($2, "account_id") END,
    "session_id" = CASE WHEN $3::bool = TRUE THEN NULL ELSE COALESCE($4, "session_id") END,
    "event_type" = COALESCE($5, "event_type"),
    "ref_type" = COALESCE($6, "ref_type"),
    "ref_id" = COALESCE($7, "ref_id"),
    "metadata" = CASE WHEN $8::bool = TRUE THEN NULL ELSE COALESCE($9, "metadata") END,
    "user_agent" = CASE WHEN $10::bool = TRUE THEN NULL ELSE COALESCE($11, "user_agent") END,
    "ip_address" = CASE WHEN $12::bool = TRUE THEN NULL ELSE COALESCE($13, "ip_address") END,
    "date_created" = COALESCE($14, "date_created")
WHERE id = $15
RETURNING id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created, account_number
`

type UpdateInteractionParams struct {
	NullAccountID bool                           `json:"null_account_id"`
	AccountID     uuid.NullUUID                  `json:"account_id"`
	NullSessionID bool                           `json:"null_session_id"`
	SessionID     null.String                    `json:"session_id"`
	EventType     null.String                    `json:"event_type"`
	RefType       NullAnalyticInteractionRefType `json:"ref_type"`
	RefID         null.String                    `json:"ref_id"`
	NullMetadata  bool                           `json:"null_metadata"`
	Metadata      json.RawMessage                `json:"metadata"`
	NullUserAgent bool                           `json:"null_user_agent"`
	UserAgent     null.String                    `json:"user_agent"`
	NullIpAddress bool                           `json:"null_ip_address"`
	IpAddress     null.String                    `json:"ip_address"`
	DateCreated   null.Time                      `json:"date_created"`
	ID            int64                          `json:"id"`
}

func (q *Queries) UpdateInteraction(ctx context.Context, arg UpdateInteractionParams) (AnalyticInteraction, error) {
	row := q.db.QueryRow(ctx, updateInteraction,
		arg.NullAccountID,
		arg.AccountID,
		arg.NullSessionID,
		arg.SessionID,
		arg.EventType,
		arg.RefType,
		arg.RefID,
		arg.NullMetadata,
		arg.Metadata,
		arg.NullUserAgent,
		arg.UserAgent,
		arg.NullIpAddress,
		arg.IpAddress,
		arg.DateCreated,
		arg.ID,
	)
	var i AnalyticInteraction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionID,
		&i.EventType,
		&i.RefType,
		&i.RefID,
		&i.Metadata,
		&i.UserAgent,
		&i.IpAddress,
		&i.DateCreated,
		&i.AccountNumber,
	)
	return i, err
}
