// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package analyticdb

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createBatchInteraction = `-- name: CreateBatchInteraction :batchone
INSERT INTO "analytic"."interaction" ("account_id", "session_id", "event_type", "ref_type", "ref_id", "metadata", "user_agent", "ip_address", "date_created")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, session_id, event_type, ref_type, ref_id, metadata, user_agent, ip_address, date_created
`

type CreateBatchInteractionBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchInteractionParams struct {
	AccountID   uuid.NullUUID              `json:"account_id"`
	SessionID   null.String                `json:"session_id"`
	EventType   string                     `json:"event_type"`
	RefType     AnalyticInteractionRefType `json:"ref_type"`
	RefID       string                     `json:"ref_id"`
	Metadata    json.RawMessage            `json:"metadata"`
	UserAgent   null.String                `json:"user_agent"`
	IpAddress   null.String                `json:"ip_address"`
	DateCreated time.Time                  `json:"date_created"`
}

func (q *Queries) CreateBatchInteraction(ctx context.Context, arg []CreateBatchInteractionParams) *CreateBatchInteractionBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AccountID,
			a.SessionID,
			a.EventType,
			a.RefType,
			a.RefID,
			a.Metadata,
			a.UserAgent,
			a.IpAddress,
			a.DateCreated,
		}
		batch.Queue(createBatchInteraction, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchInteractionBatchResults{br, len(arg), false}
}

func (b *CreateBatchInteractionBatchResults) QueryRow(f func(int, AnalyticInteraction, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i AnalyticInteraction
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.AccountID,
			&i.SessionID,
			&i.EventType,
			&i.RefType,
			&i.RefID,
			&i.Metadata,
			&i.UserAgent,
			&i.IpAddress,
			&i.DateCreated,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchInteractionBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
