// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package analyticdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type AnalyticInteractionRefType string

const (
	AnalyticInteractionRefTypeProduct  AnalyticInteractionRefType = "Product"
	AnalyticInteractionRefTypeCategory AnalyticInteractionRefType = "Category"
	AnalyticInteractionRefTypeBrand    AnalyticInteractionRefType = "Brand"
)

func (e *AnalyticInteractionRefType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticInteractionRefType(s)
	case string:
		*e = AnalyticInteractionRefType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticInteractionRefType: %T", src)
	}
	return nil
}

type NullAnalyticInteractionRefType struct {
	AnalyticInteractionRefType AnalyticInteractionRefType `json:"analytic_interaction_ref_type"`
	Valid                      bool                       `json:"valid"` // Valid is true if AnalyticInteractionRefType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticInteractionRefType) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticInteractionRefType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticInteractionRefType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticInteractionRefType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticInteractionRefType), nil
}

func (e AnalyticInteractionRefType) Valid() bool {
	switch e {
	case AnalyticInteractionRefTypeProduct,
		AnalyticInteractionRefTypeCategory,
		AnalyticInteractionRefTypeBrand:
		return true
	}
	return false
}

func AllAnalyticInteractionRefTypeValues() []AnalyticInteractionRefType {
	return []AnalyticInteractionRefType{
		AnalyticInteractionRefTypeProduct,
		AnalyticInteractionRefTypeCategory,
		AnalyticInteractionRefTypeBrand,
	}
}

type AnalyticInteraction struct {
	ID            int64                      `json:"id"`
	AccountID     uuid.NullUUID              `json:"account_id"`
	SessionID     null.String                `json:"session_id"`
	EventType     string                     `json:"event_type"`
	RefType       AnalyticInteractionRefType `json:"ref_type"`
	RefID         string                     `json:"ref_id"`
	Metadata      json.RawMessage            `json:"metadata"`
	UserAgent     null.String                `json:"user_agent"`
	IpAddress     null.String                `json:"ip_address"`
	DateCreated   time.Time                  `json:"date_created"`
	AccountNumber int64                      `json:"account_number"`
}

type AnalyticProductPopularity struct {
	SpuID         uuid.UUID `json:"spu_id"`
	Score         float64   `json:"score"`
	ViewCount     int64     `json:"view_count"`
	PurchaseCount int64     `json:"purchase_count"`
	FavoriteCount int64     `json:"favorite_count"`
	CartCount     int64     `json:"cart_count"`
	ReviewCount   int64     `json:"review_count"`
	DateUpdated   time.Time `json:"date_updated"`
}
