// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_popularity.sql

package analyticdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const getProductPopularityByID = `-- name: GetProductPopularityByID :one
SELECT id, score, view_count, purchase_count, favorite_count, cart_count, review_count, date_updated FROM "analytic"."product_popularity"
WHERE "id" = $1
`

func (q *Queries) GetProductPopularityByID(ctx context.Context, id uuid.UUID) (AnalyticProductPopularity, error) {
	row := q.db.QueryRow(ctx, getProductPopularityByID, id)
	var i AnalyticProductPopularity
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.ViewCount,
		&i.PurchaseCount,
		&i.FavoriteCount,
		&i.CartCount,
		&i.ReviewCount,
		&i.DateUpdated,
	)
	return i, err
}

const listTopProductPopularity = `-- name: ListTopProductPopularity :many
SELECT id, score, view_count, purchase_count, favorite_count, cart_count, review_count, date_updated FROM "analytic"."product_popularity"
ORDER BY "score" DESC
LIMIT $2::int
OFFSET $1::int
`

type ListTopProductPopularityParams struct {
	Offset null.Int32 `json:"offset"`
	Limit  null.Int32 `json:"limit"`
}

func (q *Queries) ListTopProductPopularity(ctx context.Context, arg ListTopProductPopularityParams) ([]AnalyticProductPopularity, error) {
	rows, err := q.db.Query(ctx, listTopProductPopularity, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticProductPopularity{}
	for rows.Next() {
		var i AnalyticProductPopularity
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.ViewCount,
			&i.PurchaseCount,
			&i.FavoriteCount,
			&i.CartCount,
			&i.ReviewCount,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductPopularity = `-- name: UpsertProductPopularity :one
INSERT INTO "analytic"."product_popularity" ("id", "score", "view_count", "purchase_count", "favorite_count", "cart_count", "review_count")
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT ("id") DO UPDATE SET
    "score" = "analytic"."product_popularity"."score" + EXCLUDED."score",
    "view_count" = "analytic"."product_popularity"."view_count" + EXCLUDED."view_count",
    "purchase_count" = "analytic"."product_popularity"."purchase_count" + EXCLUDED."purchase_count",
    "favorite_count" = "analytic"."product_popularity"."favorite_count" + EXCLUDED."favorite_count",
    "cart_count" = "analytic"."product_popularity"."cart_count" + EXCLUDED."cart_count",
    "review_count" = "analytic"."product_popularity"."review_count" + EXCLUDED."review_count",
    "date_updated" = CURRENT_TIMESTAMP
RETURNING id, score, view_count, purchase_count, favorite_count, cart_count, review_count, date_updated
`

type UpsertProductPopularityParams struct {
	ID            uuid.UUID `json:"id"`
	Score         float64   `json:"score"`
	ViewCount     int64     `json:"view_count"`
	PurchaseCount int64     `json:"purchase_count"`
	FavoriteCount int64     `json:"favorite_count"`
	CartCount     int64     `json:"cart_count"`
	ReviewCount   int64     `json:"review_count"`
}

func (q *Queries) UpsertProductPopularity(ctx context.Context, arg UpsertProductPopularityParams) (AnalyticProductPopularity, error) {
	row := q.db.QueryRow(ctx, upsertProductPopularity,
		arg.ID,
		arg.Score,
		arg.ViewCount,
		arg.PurchaseCount,
		arg.FavoriteCount,
		arg.CartCount,
		arg.ReviewCount,
	)
	var i AnalyticProductPopularity
	err := row.Scan(
		&i.ID,
		&i.Score,
		&i.ViewCount,
		&i.PurchaseCount,
		&i.FavoriteCount,
		&i.CartCount,
		&i.ReviewCount,
		&i.DateUpdated,
	)
	return i, err
}
