// Code generated by genrestate; DO NOT EDIT.

package promotionbiz

import (
	"context"
	"github.com/google/uuid"
	restateclient "shopnexus-server/internal/infras/restate"
	catalogmodel "shopnexus-server/internal/module/catalog/model"
	promotionmodel "shopnexus-server/internal/module/promotion/model"
	sharedmodel "shopnexus-server/internal/shared/model"
)

const serviceName = "Promotion"

// PromotionRestateClient implements PromotionBiz via Restate HTTP ingress.
type PromotionRestateClient struct {
	client *restateclient.Client
}

var _ PromotionBiz = (*PromotionRestateClient)(nil)

func NewPromotionRestateClient(restateIngressURL string) *PromotionRestateClient {
	return &PromotionRestateClient{client: restateclient.NewClient(restateIngressURL)}
}

func (p *PromotionRestateClient) GetPromotion(ctx context.Context, params GetPromotionParams) (promotionmodel.Promotion, error) {
	return restateclient.Call[promotionmodel.Promotion](ctx, p.client, serviceName, "GetPromotion", params)
}

func (p *PromotionRestateClient) ListPromotion(ctx context.Context, params ListPromotionParams) (sharedmodel.PaginateResult[promotionmodel.Promotion], error) {
	return restateclient.Call[sharedmodel.PaginateResult[promotionmodel.Promotion]](ctx, p.client, serviceName, "ListPromotion", params)
}

func (p *PromotionRestateClient) CreatePromotion(ctx context.Context, params CreatePromotionParams) (promotionmodel.Promotion, error) {
	return restateclient.Call[promotionmodel.Promotion](ctx, p.client, serviceName, "CreatePromotion", params)
}

func (p *PromotionRestateClient) UpdatePromotion(ctx context.Context, params UpdatePromotionParams) (promotionmodel.Promotion, error) {
	return restateclient.Call[promotionmodel.Promotion](ctx, p.client, serviceName, "UpdatePromotion", params)
}

func (p *PromotionRestateClient) DeletePromotion(ctx context.Context, params DeletePromotionParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "DeletePromotion", params)
}

func (p *PromotionRestateClient) CalculatePromotedPrices(ctx context.Context, params CalculatePromotedPricesParams) (map[uuid.UUID]*catalogmodel.OrderPrice, error) {
	return restateclient.Call[map[uuid.UUID]*catalogmodel.OrderPrice](ctx, p.client, serviceName, "CalculatePromotedPrices", params)
}
