env: dev

log:
  level: debug
  format: json
  addSource: true
  timeFormat: "2006-01-02 15:04:05"

app:
  name: shopnexus
  publicUrl: "http://localhost:5004"
  jwt:
    secret: supersecretkey123
    accessTokenDuration: 3600
    refreshSecret: superrefreshsecret456
    refreshTokenDuration: 1209600
  vnpay:
    tmnCode: ""
    hashSecret: ""
    returnUrl: "http://localhost:3000/payment/vnpay_return"
  sepay:
    merchantId: ""
    secretKey: ""
    ipnSecretKey: ""
    successUrl: "http://localhost:3000/payment/sepay_return"
    errorUrl: "http://localhost:3000/payment/sepay_error"
    cancelUrl: "http://localhost:3000/payment/sepay_cancel"
    sandbox: true
  cardPayment:
    provider: ""
    secretKey: ""
    publicKey: ""
  search:
    url: "http://localhost:8000"
    denseWeight: 0.75
    sparseWeight: 0.25
    interactionBatchSize: 1
    metadataSyncInterval: 1s
    embeddingSyncInterval: 1s
  order:
    paymentExpiryDays: 30

filestore:
  type: s3 # Options: Local, S3, Cloudinary, Remote
  presignedDefaultTTL: 1800 # in seconds
  s3:
    accessKeyID: ""
    secretAccessKey: ""
    region: ""
    bucket: ""
    cloudfrontUrl: ""
  placeholder404Url: ""

postgres:
  # Option 1: Using connection URL
  # url: postgres://user:password@localhost:5432/mydb?sslmode=disable

  # Option 2: Using separate fields (required if URL is not provided)
  host: localhost
  port: 5432
  username: shopnexus
  password: peakshopnexuspassword
  database: shopnexus
  maxConnections: 50
  maxIdleConnections: 10
  maxConnIdleTime: 300
  logQuery: true
  allowNestedTransactions: true

redis:
  host: localhost
  port: "6379"
  password: "peaksehopnexuspassword"
  db: 0

nats:
  host: localhost
  port: 4222

milvus:
  address: "localhost:19530"

llm:
  provider: python
  python:
    url: "http://localhost:5007"
  openai:
    apiKey: ""
    baseURL: ""
    embedModel: "text-embedding-3-small"
    chatModel: "gpt-4o"
  bedrock:
    region: "us-east-1"
    embedModelId: "amazon.titan-embed-text-v2:0"
    chatModelId: "anthropic.claude-3-haiku-20240307-v1:0"

restate:
  ingressAddress: "http://localhost:8080"
  adminAddress: "http://localhost:9470"
  serviceHost: "http://host.docker.internal"
  servicePort: "8082"
