// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package analyticdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountInteraction(ctx context.Context, arg CountInteractionParams) (int64, error)
	CreateBatchInteraction(ctx context.Context, arg []CreateBatchInteractionParams) *CreateBatchInteractionBatchResults
	CreateCopyDefaultInteraction(ctx context.Context, arg []CreateCopyDefaultInteractionParams) (int64, error)
	CreateCopyInteraction(ctx context.Context, arg []CreateCopyInteractionParams) (int64, error)
	CreateDefaultInteraction(ctx context.Context, arg CreateDefaultInteractionParams) (AnalyticInteraction, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (AnalyticInteraction, error)
	DeleteInteraction(ctx context.Context, arg DeleteInteractionParams) error
	GetInteraction(ctx context.Context, id pgtype.Int8) (AnalyticInteraction, error)
	ListCountInteraction(ctx context.Context, arg ListCountInteractionParams) ([]ListCountInteractionRow, error)
	ListInteraction(ctx context.Context, arg ListInteractionParams) ([]AnalyticInteraction, error)
	UpdateInteraction(ctx context.Context, arg UpdateInteractionParams) (AnalyticInteraction, error)
}

var _ Querier = (*Queries)(nil)
