// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package catalogdb

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createBatchBrand = `-- name: CreateBatchBrand :batchone
INSERT INTO "catalog"."brand" ("id", "code", "name", "description")
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description
`

type CreateBatchBrandBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchBrandParams struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateBatchBrand(ctx context.Context, arg []CreateBatchBrandParams) *CreateBatchBrandBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Code,
			a.Name,
			a.Description,
		}
		batch.Queue(createBatchBrand, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchBrandBatchResults{br, len(arg), false}
}

func (b *CreateBatchBrandBatchResults) QueryRow(f func(int, CatalogBrand, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogBrand
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchBrandBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchCategory = `-- name: CreateBatchCategory :batchone
INSERT INTO "catalog"."category" ("id", "name", "description", "parent_id")
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, parent_id
`

type CreateBatchCategoryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchCategoryParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ParentID    null.Int  `json:"parent_id"`
}

func (q *Queries) CreateBatchCategory(ctx context.Context, arg []CreateBatchCategoryParams) *CreateBatchCategoryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Name,
			a.Description,
			a.ParentID,
		}
		batch.Queue(createBatchCategory, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchCategoryBatchResults{br, len(arg), false}
}

func (b *CreateBatchCategoryBatchResults) QueryRow(f func(int, CatalogCategory, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogCategory
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchCategoryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchComment = `-- name: CreateBatchComment :batchone
INSERT INTO "catalog"."comment" ("id", "account_id", "ref_type", "ref_id", "body", "upvote", "downvote", "score", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, account_id, ref_type, ref_id, body, upvote, downvote, score, date_created, date_updated
`

type CreateBatchCommentBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchCommentParams struct {
	ID          uuid.UUID             `json:"id"`
	AccountID   uuid.UUID             `json:"account_id"`
	RefType     CatalogCommentRefType `json:"ref_type"`
	RefID       uuid.UUID             `json:"ref_id"`
	Body        string                `json:"body"`
	Upvote      int64                 `json:"upvote"`
	Downvote    int64                 `json:"downvote"`
	Score       float64               `json:"score"`
	DateCreated time.Time             `json:"date_created"`
	DateUpdated time.Time             `json:"date_updated"`
}

func (q *Queries) CreateBatchComment(ctx context.Context, arg []CreateBatchCommentParams) *CreateBatchCommentBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.AccountID,
			a.RefType,
			a.RefID,
			a.Body,
			a.Upvote,
			a.Downvote,
			a.Score,
			a.DateCreated,
			a.DateUpdated,
		}
		batch.Queue(createBatchComment, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchCommentBatchResults{br, len(arg), false}
}

func (b *CreateBatchCommentBatchResults) QueryRow(f func(int, CatalogComment, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogComment
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.AccountID,
			&i.RefType,
			&i.RefID,
			&i.Body,
			&i.Upvote,
			&i.Downvote,
			&i.Score,
			&i.DateCreated,
			&i.DateUpdated,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchCommentBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchProductSku = `-- name: CreateBatchProductSku :batchone
INSERT INTO "catalog"."product_sku" ("id", "spu_id", "price", "can_combine", "attributes", "package_details", "date_created", "date_deleted")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, spu_id, price, can_combine, attributes, package_details, date_created, date_deleted
`

type CreateBatchProductSkuBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchProductSkuParams struct {
	ID             uuid.UUID       `json:"id"`
	SpuID          uuid.UUID       `json:"spu_id"`
	Price          int64           `json:"price"`
	CanCombine     bool            `json:"can_combine"`
	Attributes     json.RawMessage `json:"attributes"`
	PackageDetails json.RawMessage `json:"package_details"`
	DateCreated    time.Time       `json:"date_created"`
	DateDeleted    null.Time       `json:"date_deleted"`
}

func (q *Queries) CreateBatchProductSku(ctx context.Context, arg []CreateBatchProductSkuParams) *CreateBatchProductSkuBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.SpuID,
			a.Price,
			a.CanCombine,
			a.Attributes,
			a.PackageDetails,
			a.DateCreated,
			a.DateDeleted,
		}
		batch.Queue(createBatchProductSku, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchProductSkuBatchResults{br, len(arg), false}
}

func (b *CreateBatchProductSkuBatchResults) QueryRow(f func(int, CatalogProductSku, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogProductSku
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.SpuID,
			&i.Price,
			&i.CanCombine,
			&i.Attributes,
			&i.PackageDetails,
			&i.DateCreated,
			&i.DateDeleted,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchProductSkuBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchProductSpu = `-- name: CreateBatchProductSpu :batchone
INSERT INTO "catalog"."product_spu" ("id", "slug", "account_id", "category_id", "brand_id", "featured_sku_id", "name", "description", "is_active", "specifications", "date_created", "date_updated", "date_deleted")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, slug, account_id, category_id, brand_id, featured_sku_id, name, description, is_active, specifications, date_created, date_updated, date_deleted
`

type CreateBatchProductSpuBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchProductSpuParams struct {
	ID             uuid.UUID       `json:"id"`
	Slug           string          `json:"slug"`
	AccountID      uuid.UUID       `json:"account_id"`
	CategoryID     uuid.UUID       `json:"category_id"`
	BrandID        uuid.UUID       `json:"brand_id"`
	FeaturedSkuID  uuid.NullUUID   `json:"featured_sku_id"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	IsActive       bool            `json:"is_active"`
	Specifications json.RawMessage `json:"specifications"`
	DateCreated    time.Time       `json:"date_created"`
	DateUpdated    time.Time       `json:"date_updated"`
	DateDeleted    null.Time       `json:"date_deleted"`
}

func (q *Queries) CreateBatchProductSpu(ctx context.Context, arg []CreateBatchProductSpuParams) *CreateBatchProductSpuBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Slug,
			a.AccountID,
			a.CategoryID,
			a.BrandID,
			a.FeaturedSkuID,
			a.Name,
			a.Description,
			a.IsActive,
			a.Specifications,
			a.DateCreated,
			a.DateUpdated,
			a.DateDeleted,
		}
		batch.Queue(createBatchProductSpu, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchProductSpuBatchResults{br, len(arg), false}
}

func (b *CreateBatchProductSpuBatchResults) QueryRow(f func(int, CatalogProductSpu, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogProductSpu
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Slug,
			&i.AccountID,
			&i.CategoryID,
			&i.BrandID,
			&i.FeaturedSkuID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Specifications,
			&i.DateCreated,
			&i.DateUpdated,
			&i.DateDeleted,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchProductSpuBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchProductSpuTag = `-- name: CreateBatchProductSpuTag :batchone
INSERT INTO "catalog"."product_spu_tag" ("spu_id", "tag")
VALUES ($1, $2)
RETURNING id, spu_id, tag
`

type CreateBatchProductSpuTagBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchProductSpuTagParams struct {
	SpuID uuid.UUID `json:"spu_id"`
	Tag   string    `json:"tag"`
}

func (q *Queries) CreateBatchProductSpuTag(ctx context.Context, arg []CreateBatchProductSpuTagParams) *CreateBatchProductSpuTagBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SpuID,
			a.Tag,
		}
		batch.Queue(createBatchProductSpuTag, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchProductSpuTagBatchResults{br, len(arg), false}
}

func (b *CreateBatchProductSpuTagBatchResults) QueryRow(f func(int, CatalogProductSpuTag, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogProductSpuTag
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.ID, &i.SpuID, &i.Tag)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchProductSpuTagBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchSearchSync = `-- name: CreateBatchSearchSync :batchone
INSERT INTO "catalog"."search_sync" ("ref_type", "ref_id", "is_stale_embedding", "is_stale_metadata", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
`

type CreateBatchSearchSyncBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchSearchSyncParams struct {
	RefType          CatalogSearchSyncRefType `json:"ref_type"`
	RefID            uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  bool                     `json:"is_stale_metadata"`
	DateCreated      time.Time                `json:"date_created"`
	DateUpdated      time.Time                `json:"date_updated"`
}

func (q *Queries) CreateBatchSearchSync(ctx context.Context, arg []CreateBatchSearchSyncParams) *CreateBatchSearchSyncBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RefType,
			a.RefID,
			a.IsStaleEmbedding,
			a.IsStaleMetadata,
			a.DateCreated,
			a.DateUpdated,
		}
		batch.Queue(createBatchSearchSync, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchSearchSyncBatchResults{br, len(arg), false}
}

func (b *CreateBatchSearchSyncBatchResults) QueryRow(f func(int, CatalogSearchSync, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogSearchSync
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.RefType,
			&i.RefID,
			&i.IsStaleEmbedding,
			&i.IsStaleMetadata,
			&i.DateCreated,
			&i.DateUpdated,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchSearchSyncBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchTag = `-- name: CreateBatchTag :batchone
INSERT INTO "catalog"."tag" ("id", "description")
VALUES ($1, $2)
RETURNING id, description
`

type CreateBatchTagBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchTagParams struct {
	ID          string      `json:"id"`
	Description null.String `json:"description"`
}

func (q *Queries) CreateBatchTag(ctx context.Context, arg []CreateBatchTagParams) *CreateBatchTagBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Description,
		}
		batch.Queue(createBatchTag, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchTagBatchResults{br, len(arg), false}
}

func (b *CreateBatchTagBatchResults) QueryRow(f func(int, CatalogTag, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i CatalogTag
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.ID, &i.Description)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateBatchTagBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const updateBatchStaleSearchSync = `-- name: UpdateBatchStaleSearchSync :batchexec
UPDATE catalog.search_sync
SET
    is_stale_metadata = COALESCE($1, is_stale_metadata),
    is_stale_embedding = COALESCE($2, is_stale_embedding),
    date_updated = NOW()
WHERE ref_type = $3 AND ref_id = $4
`

type UpdateBatchStaleSearchSyncBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateBatchStaleSearchSyncParams struct {
	IsStaleMetadata  null.Bool                `json:"is_stale_metadata"`
	IsStaleEmbedding null.Bool                `json:"is_stale_embedding"`
	RefType          CatalogSearchSyncRefType `json:"ref_type"`
	RefID            uuid.UUID                `json:"ref_id"`
}

func (q *Queries) UpdateBatchStaleSearchSync(ctx context.Context, arg []UpdateBatchStaleSearchSyncParams) *UpdateBatchStaleSearchSyncBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.IsStaleMetadata,
			a.IsStaleEmbedding,
			a.RefType,
			a.RefID,
		}
		batch.Queue(updateBatchStaleSearchSync, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateBatchStaleSearchSyncBatchResults{br, len(arg), false}
}

func (b *UpdateBatchStaleSearchSyncBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateBatchStaleSearchSyncBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
