// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_search_sync.sql

package catalogdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchSync = `-- name: CountSearchSync :one
SELECT COUNT(*)
FROM "catalog"."search_sync"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("is_stale_metadata" = ANY($5) OR $5 IS NULL) AND
    ("date_created" = ANY($6) OR $6 IS NULL) AND
    ("date_created" > $7 OR $7 IS NULL) AND
    ("date_created" < $8 OR $8 IS NULL) AND
    ("date_updated" = ANY($9) OR $9 IS NULL) AND
    ("date_updated" > $10 OR $10 IS NULL) AND
    ("date_updated" < $11 OR $11 IS NULL)
)
`

type CountSearchSyncParams struct {
	ID               []int64                    `json:"id"`
	RefType          []CatalogSearchSyncRefType `json:"ref_type"`
	RefID            []uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding []bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  []bool                     `json:"is_stale_metadata"`
	DateCreated      []time.Time                `json:"date_created"`
	DateCreatedFrom  null.Time                  `json:"date_created_from"`
	DateCreatedTo    null.Time                  `json:"date_created_to"`
	DateUpdated      []time.Time                `json:"date_updated"`
	DateUpdatedFrom  null.Time                  `json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `json:"date_updated_to"`
}

func (q *Queries) CountSearchSync(ctx context.Context, arg CountSearchSyncParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCopyDefaultSearchSyncParams struct {
	RefType CatalogSearchSyncRefType `json:"ref_type"`
	RefID   uuid.UUID                `json:"ref_id"`
}

type CreateCopySearchSyncParams struct {
	RefType          CatalogSearchSyncRefType `json:"ref_type"`
	RefID            uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  bool                     `json:"is_stale_metadata"`
	DateCreated      time.Time                `json:"date_created"`
	DateUpdated      time.Time                `json:"date_updated"`
}

const createDefaultSearchSync = `-- name: CreateDefaultSearchSync :one
INSERT INTO "catalog"."search_sync" ("ref_type", "ref_id")
VALUES ($1, $2)
RETURNING id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
`

type CreateDefaultSearchSyncParams struct {
	RefType CatalogSearchSyncRefType `json:"ref_type"`
	RefID   uuid.UUID                `json:"ref_id"`
}

func (q *Queries) CreateDefaultSearchSync(ctx context.Context, arg CreateDefaultSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, createDefaultSearchSync, arg.RefType, arg.RefID)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.IsStaleMetadata,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createSearchSync = `-- name: CreateSearchSync :one
INSERT INTO "catalog"."search_sync" ("ref_type", "ref_id", "is_stale_embedding", "is_stale_metadata", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
`

type CreateSearchSyncParams struct {
	RefType          CatalogSearchSyncRefType `json:"ref_type"`
	RefID            uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  bool                     `json:"is_stale_metadata"`
	DateCreated      time.Time                `json:"date_created"`
	DateUpdated      time.Time                `json:"date_updated"`
}

func (q *Queries) CreateSearchSync(ctx context.Context, arg CreateSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, createSearchSync,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.IsStaleMetadata,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const deleteSearchSync = `-- name: DeleteSearchSync :exec
DELETE FROM "catalog"."search_sync"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("is_stale_metadata" = ANY($5) OR $5 IS NULL) AND
    ("date_created" = ANY($6) OR $6 IS NULL) AND
    ("date_created" > $7 OR $7 IS NULL) AND
    ("date_created" < $8 OR $8 IS NULL) AND
    ("date_updated" = ANY($9) OR $9 IS NULL) AND
    ("date_updated" > $10 OR $10 IS NULL) AND
    ("date_updated" < $11 OR $11 IS NULL)
)
`

type DeleteSearchSyncParams struct {
	ID               []int64                    `json:"id"`
	RefType          []CatalogSearchSyncRefType `json:"ref_type"`
	RefID            []uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding []bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  []bool                     `json:"is_stale_metadata"`
	DateCreated      []time.Time                `json:"date_created"`
	DateCreatedFrom  null.Time                  `json:"date_created_from"`
	DateCreatedTo    null.Time                  `json:"date_created_to"`
	DateUpdated      []time.Time                `json:"date_updated"`
	DateUpdatedFrom  null.Time                  `json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `json:"date_updated_to"`
}

func (q *Queries) DeleteSearchSync(ctx context.Context, arg DeleteSearchSyncParams) error {
	_, err := q.db.Exec(ctx, deleteSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const getSearchSync = `-- name: GetSearchSync :one
SELECT id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
FROM "catalog"."search_sync"
WHERE ("id" = $1) OR ("ref_type" = $2 AND "ref_id" = $3)
`

type GetSearchSyncParams struct {
	ID      pgtype.Int8                  `json:"id"`
	RefType NullCatalogSearchSyncRefType `json:"ref_type"`
	RefID   uuid.NullUUID                `json:"ref_id"`
}

func (q *Queries) GetSearchSync(ctx context.Context, arg GetSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, getSearchSync, arg.ID, arg.RefType, arg.RefID)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.IsStaleMetadata,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const listCountSearchSync = `-- name: ListCountSearchSync :many
SELECT embed_search_sync.id, embed_search_sync.ref_type, embed_search_sync.ref_id, embed_search_sync.is_stale_embedding, embed_search_sync.is_stale_metadata, embed_search_sync.date_created, embed_search_sync.date_updated, COUNT(*) OVER() as total_count
FROM "catalog"."search_sync" embed_search_sync
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("is_stale_metadata" = ANY($5) OR $5 IS NULL) AND
    ("date_created" = ANY($6) OR $6 IS NULL) AND
    ("date_created" > $7 OR $7 IS NULL) AND
    ("date_created" < $8 OR $8 IS NULL) AND
    ("date_updated" = ANY($9) OR $9 IS NULL) AND
    ("date_updated" > $10 OR $10 IS NULL) AND
    ("date_updated" < $11 OR $11 IS NULL)
)
ORDER BY "id"
LIMIT $13::int
OFFSET $12::int
`

type ListCountSearchSyncParams struct {
	ID               []int64                    `json:"id"`
	RefType          []CatalogSearchSyncRefType `json:"ref_type"`
	RefID            []uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding []bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  []bool                     `json:"is_stale_metadata"`
	DateCreated      []time.Time                `json:"date_created"`
	DateCreatedFrom  null.Time                  `json:"date_created_from"`
	DateCreatedTo    null.Time                  `json:"date_created_to"`
	DateUpdated      []time.Time                `json:"date_updated"`
	DateUpdatedFrom  null.Time                  `json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `json:"date_updated_to"`
	Offset           null.Int32                 `json:"offset"`
	Limit            null.Int32                 `json:"limit"`
}

type ListCountSearchSyncRow struct {
	CatalogSearchSync CatalogSearchSync `json:"catalog_search_sync"`
	TotalCount        int64             `json:"total_count"`
}

func (q *Queries) ListCountSearchSync(ctx context.Context, arg ListCountSearchSyncParams) ([]ListCountSearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listCountSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountSearchSyncRow{}
	for rows.Next() {
		var i ListCountSearchSyncRow
		if err := rows.Scan(
			&i.CatalogSearchSync.ID,
			&i.CatalogSearchSync.RefType,
			&i.CatalogSearchSync.RefID,
			&i.CatalogSearchSync.IsStaleEmbedding,
			&i.CatalogSearchSync.IsStaleMetadata,
			&i.CatalogSearchSync.DateCreated,
			&i.CatalogSearchSync.DateUpdated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchSync = `-- name: ListSearchSync :many
SELECT id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
FROM "catalog"."search_sync"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("is_stale_metadata" = ANY($5) OR $5 IS NULL) AND
    ("date_created" = ANY($6) OR $6 IS NULL) AND
    ("date_created" > $7 OR $7 IS NULL) AND
    ("date_created" < $8 OR $8 IS NULL) AND
    ("date_updated" = ANY($9) OR $9 IS NULL) AND
    ("date_updated" > $10 OR $10 IS NULL) AND
    ("date_updated" < $11 OR $11 IS NULL)
)
ORDER BY "id"
LIMIT $13::int
OFFSET $12::int
`

type ListSearchSyncParams struct {
	ID               []int64                    `json:"id"`
	RefType          []CatalogSearchSyncRefType `json:"ref_type"`
	RefID            []uuid.UUID                `json:"ref_id"`
	IsStaleEmbedding []bool                     `json:"is_stale_embedding"`
	IsStaleMetadata  []bool                     `json:"is_stale_metadata"`
	DateCreated      []time.Time                `json:"date_created"`
	DateCreatedFrom  null.Time                  `json:"date_created_from"`
	DateCreatedTo    null.Time                  `json:"date_created_to"`
	DateUpdated      []time.Time                `json:"date_updated"`
	DateUpdatedFrom  null.Time                  `json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `json:"date_updated_to"`
	Offset           null.Int32                 `json:"offset"`
	Limit            null.Int32                 `json:"limit"`
}

func (q *Queries) ListSearchSync(ctx context.Context, arg ListSearchSyncParams) ([]CatalogSearchSync, error) {
	rows, err := q.db.Query(ctx, listSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogSearchSync{}
	for rows.Next() {
		var i CatalogSearchSync
		if err := rows.Scan(
			&i.ID,
			&i.RefType,
			&i.RefID,
			&i.IsStaleEmbedding,
			&i.IsStaleMetadata,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSearchSync = `-- name: UpdateSearchSync :one
UPDATE "catalog"."search_sync"
SET "ref_type" = COALESCE($1, "ref_type"),
    "ref_id" = COALESCE($2, "ref_id"),
    "is_stale_embedding" = COALESCE($3, "is_stale_embedding"),
    "is_stale_metadata" = COALESCE($4, "is_stale_metadata"),
    "date_created" = COALESCE($5, "date_created"),
    "date_updated" = COALESCE($6, "date_updated")
WHERE id = $7
RETURNING id, ref_type, ref_id, is_stale_embedding, is_stale_metadata, date_created, date_updated
`

type UpdateSearchSyncParams struct {
	RefType          NullCatalogSearchSyncRefType `json:"ref_type"`
	RefID            uuid.NullUUID                `json:"ref_id"`
	IsStaleEmbedding null.Bool                    `json:"is_stale_embedding"`
	IsStaleMetadata  null.Bool                    `json:"is_stale_metadata"`
	DateCreated      null.Time                    `json:"date_created"`
	DateUpdated      null.Time                    `json:"date_updated"`
	ID               int64                        `json:"id"`
}

func (q *Queries) UpdateSearchSync(ctx context.Context, arg UpdateSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, updateSearchSync,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.IsStaleMetadata,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.IsStaleMetadata,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}
