// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_custom.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const searchCountProductSpuByTags = `-- name: SearchCountProductSpuByTags :many

SELECT DISTINCT p.id, COUNT(*) OVER() as total_count
FROM "catalog"."product_spu" p
INNER JOIN "catalog"."product_spu_tag" t ON t.spu_id = p.id
WHERE p.date_deleted IS NULL
  AND t.tag = ANY($1)
GROUP BY p.id
HAVING COUNT(DISTINCT t.tag) = $2::int
ORDER BY p.id
LIMIT $4::int
OFFSET $3::int
`

type SearchCountProductSpuByTagsParams struct {
	Tags     []string   `json:"tags"`
	TagCount int32      `json:"tag_count"`
	Offset   null.Int32 `json:"offset"`
	Limit    null.Int32 `json:"limit"`
}

type SearchCountProductSpuByTagsRow struct {
	ID         uuid.UUID `json:"id"`
	TotalCount int64     `json:"total_count"`
}

// Custom product queries
// Returns SPU IDs that have ALL of the specified tags (AND logic).
func (q *Queries) SearchCountProductSpuByTags(ctx context.Context, arg SearchCountProductSpuByTagsParams) ([]SearchCountProductSpuByTagsRow, error) {
	rows, err := q.db.Query(ctx, searchCountProductSpuByTags,
		arg.Tags,
		arg.TagCount,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCountProductSpuByTagsRow{}
	for rows.Next() {
		var i SearchCountProductSpuByTagsRow
		if err := rows.Scan(&i.ID, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
