// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: promotion_promotion.sql

package promotiondb

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countPromotion = `-- name: CountPromotion :one
SELECT COUNT(*)
FROM "promotion"."promotion"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("code" = ANY($2) OR $2 IS NULL) AND
    ("owner_id" = ANY($3) OR $3 IS NULL) AND
    ("type" = ANY($4) OR $4 IS NULL) AND
    ("title" = ANY($5) OR $5 IS NULL) AND
    ("description" = ANY($6) OR $6 IS NULL) AND
    ("is_active" = ANY($7) OR $7 IS NULL) AND
    ("auto_apply" = ANY($8) OR $8 IS NULL) AND
    ("date_started" = ANY($9) OR $9 IS NULL) AND
    ("date_started" > $10 OR $10 IS NULL) AND
    ("date_started" < $11 OR $11 IS NULL) AND
    ("date_ended" = ANY($12) OR $12 IS NULL) AND
    ("date_ended" > $13 OR $13 IS NULL) AND
    ("date_ended" < $14 OR $14 IS NULL) AND
    ("date_created" = ANY($15) OR $15 IS NULL) AND
    ("date_created" > $16 OR $16 IS NULL) AND
    ("date_created" < $17 OR $17 IS NULL) AND
    ("date_updated" = ANY($18) OR $18 IS NULL) AND
    ("date_updated" > $19 OR $19 IS NULL) AND
    ("date_updated" < $20 OR $20 IS NULL)
)
`

type CountPromotionParams struct {
	ID              []uuid.UUID     `json:"id"`
	Code            []string        `json:"code"`
	OwnerID         []uuid.NullUUID `json:"owner_id"`
	Type            []PromotionType `json:"type"`
	Title           []string        `json:"title"`
	Description     []null.String   `json:"description"`
	IsActive        []bool          `json:"is_active"`
	AutoApply       []bool          `json:"auto_apply"`
	DateStarted     []time.Time     `json:"date_started"`
	DateStartedFrom null.Time       `json:"date_started_from"`
	DateStartedTo   null.Time       `json:"date_started_to"`
	DateEnded       []null.Time     `json:"date_ended"`
	DateEndedFrom   null.Time       `json:"date_ended_from"`
	DateEndedTo     null.Time       `json:"date_ended_to"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
}

func (q *Queries) CountPromotion(ctx context.Context, arg CountPromotionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPromotion,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateStartedFrom,
		arg.DateStartedTo,
		arg.DateEnded,
		arg.DateEndedFrom,
		arg.DateEndedTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCopyDefaultPromotionParams struct {
	Code        string        `json:"code"`
	OwnerID     uuid.NullUUID `json:"owner_id"`
	Type        PromotionType `json:"type"`
	Title       string        `json:"title"`
	Description null.String   `json:"description"`
	IsActive    bool          `json:"is_active"`
	AutoApply   bool          `json:"auto_apply"`
	DateStarted time.Time     `json:"date_started"`
	DateEnded   null.Time     `json:"date_ended"`
}

type CreateCopyPromotionParams struct {
	ID          uuid.UUID     `json:"id"`
	Code        string        `json:"code"`
	OwnerID     uuid.NullUUID `json:"owner_id"`
	Type        PromotionType `json:"type"`
	Title       string        `json:"title"`
	Description null.String   `json:"description"`
	IsActive    bool          `json:"is_active"`
	AutoApply   bool          `json:"auto_apply"`
	DateStarted time.Time     `json:"date_started"`
	DateEnded   null.Time     `json:"date_ended"`
	DateCreated time.Time     `json:"date_created"`
	DateUpdated time.Time     `json:"date_updated"`
}

const createDefaultPromotion = `-- name: CreateDefaultPromotion :one
INSERT INTO "promotion"."promotion" ("code", "owner_id", "type", "title", "description", "is_active", "auto_apply", "date_started", "date_ended")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, owner_id, type, title, description, is_active, auto_apply, date_started, date_ended, date_created, date_updated
`

type CreateDefaultPromotionParams struct {
	Code        string        `json:"code"`
	OwnerID     uuid.NullUUID `json:"owner_id"`
	Type        PromotionType `json:"type"`
	Title       string        `json:"title"`
	Description null.String   `json:"description"`
	IsActive    bool          `json:"is_active"`
	AutoApply   bool          `json:"auto_apply"`
	DateStarted time.Time     `json:"date_started"`
	DateEnded   null.Time     `json:"date_ended"`
}

func (q *Queries) CreateDefaultPromotion(ctx context.Context, arg CreateDefaultPromotionParams) (PromotionPromotion, error) {
	row := q.db.QueryRow(ctx, createDefaultPromotion,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateEnded,
	)
	var i PromotionPromotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.AutoApply,
		&i.DateStarted,
		&i.DateEnded,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createPromotion = `-- name: CreatePromotion :one
INSERT INTO "promotion"."promotion" ("id", "code", "owner_id", "type", "title", "description", "is_active", "auto_apply", "date_started", "date_ended", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, code, owner_id, type, title, description, is_active, auto_apply, date_started, date_ended, date_created, date_updated
`

type CreatePromotionParams struct {
	ID          uuid.UUID     `json:"id"`
	Code        string        `json:"code"`
	OwnerID     uuid.NullUUID `json:"owner_id"`
	Type        PromotionType `json:"type"`
	Title       string        `json:"title"`
	Description null.String   `json:"description"`
	IsActive    bool          `json:"is_active"`
	AutoApply   bool          `json:"auto_apply"`
	DateStarted time.Time     `json:"date_started"`
	DateEnded   null.Time     `json:"date_ended"`
	DateCreated time.Time     `json:"date_created"`
	DateUpdated time.Time     `json:"date_updated"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (PromotionPromotion, error) {
	row := q.db.QueryRow(ctx, createPromotion,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateEnded,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i PromotionPromotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.AutoApply,
		&i.DateStarted,
		&i.DateEnded,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const deletePromotion = `-- name: DeletePromotion :exec
DELETE FROM "promotion"."promotion"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("code" = ANY($2) OR $2 IS NULL) AND
    ("owner_id" = ANY($3) OR $3 IS NULL) AND
    ("type" = ANY($4) OR $4 IS NULL) AND
    ("title" = ANY($5) OR $5 IS NULL) AND
    ("description" = ANY($6) OR $6 IS NULL) AND
    ("is_active" = ANY($7) OR $7 IS NULL) AND
    ("auto_apply" = ANY($8) OR $8 IS NULL) AND
    ("date_started" = ANY($9) OR $9 IS NULL) AND
    ("date_started" > $10 OR $10 IS NULL) AND
    ("date_started" < $11 OR $11 IS NULL) AND
    ("date_ended" = ANY($12) OR $12 IS NULL) AND
    ("date_ended" > $13 OR $13 IS NULL) AND
    ("date_ended" < $14 OR $14 IS NULL) AND
    ("date_created" = ANY($15) OR $15 IS NULL) AND
    ("date_created" > $16 OR $16 IS NULL) AND
    ("date_created" < $17 OR $17 IS NULL) AND
    ("date_updated" = ANY($18) OR $18 IS NULL) AND
    ("date_updated" > $19 OR $19 IS NULL) AND
    ("date_updated" < $20 OR $20 IS NULL)
)
`

type DeletePromotionParams struct {
	ID              []uuid.UUID     `json:"id"`
	Code            []string        `json:"code"`
	OwnerID         []uuid.NullUUID `json:"owner_id"`
	Type            []PromotionType `json:"type"`
	Title           []string        `json:"title"`
	Description     []null.String   `json:"description"`
	IsActive        []bool          `json:"is_active"`
	AutoApply       []bool          `json:"auto_apply"`
	DateStarted     []time.Time     `json:"date_started"`
	DateStartedFrom null.Time       `json:"date_started_from"`
	DateStartedTo   null.Time       `json:"date_started_to"`
	DateEnded       []null.Time     `json:"date_ended"`
	DateEndedFrom   null.Time       `json:"date_ended_from"`
	DateEndedTo     null.Time       `json:"date_ended_to"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
}

func (q *Queries) DeletePromotion(ctx context.Context, arg DeletePromotionParams) error {
	_, err := q.db.Exec(ctx, deletePromotion,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateStartedFrom,
		arg.DateStartedTo,
		arg.DateEnded,
		arg.DateEndedFrom,
		arg.DateEndedTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const getPromotion = `-- name: GetPromotion :one
SELECT id, code, owner_id, type, title, description, is_active, auto_apply, date_started, date_ended, date_created, date_updated
FROM "promotion"."promotion"
WHERE ("id" = $1) OR ("code" = $2)
`

type GetPromotionParams struct {
	ID   uuid.NullUUID `json:"id"`
	Code null.String   `json:"code"`
}

func (q *Queries) GetPromotion(ctx context.Context, arg GetPromotionParams) (PromotionPromotion, error) {
	row := q.db.QueryRow(ctx, getPromotion, arg.ID, arg.Code)
	var i PromotionPromotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.AutoApply,
		&i.DateStarted,
		&i.DateEnded,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const listCountPromotion = `-- name: ListCountPromotion :many
SELECT embed_promotion.id, embed_promotion.code, embed_promotion.owner_id, embed_promotion.type, embed_promotion.title, embed_promotion.description, embed_promotion.is_active, embed_promotion.auto_apply, embed_promotion.date_started, embed_promotion.date_ended, embed_promotion.date_created, embed_promotion.date_updated, COUNT(*) OVER() as total_count
FROM "promotion"."promotion" embed_promotion
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("code" = ANY($2) OR $2 IS NULL) AND
    ("owner_id" = ANY($3) OR $3 IS NULL) AND
    ("type" = ANY($4) OR $4 IS NULL) AND
    ("title" = ANY($5) OR $5 IS NULL) AND
    ("description" = ANY($6) OR $6 IS NULL) AND
    ("is_active" = ANY($7) OR $7 IS NULL) AND
    ("auto_apply" = ANY($8) OR $8 IS NULL) AND
    ("date_started" = ANY($9) OR $9 IS NULL) AND
    ("date_started" > $10 OR $10 IS NULL) AND
    ("date_started" < $11 OR $11 IS NULL) AND
    ("date_ended" = ANY($12) OR $12 IS NULL) AND
    ("date_ended" > $13 OR $13 IS NULL) AND
    ("date_ended" < $14 OR $14 IS NULL) AND
    ("date_created" = ANY($15) OR $15 IS NULL) AND
    ("date_created" > $16 OR $16 IS NULL) AND
    ("date_created" < $17 OR $17 IS NULL) AND
    ("date_updated" = ANY($18) OR $18 IS NULL) AND
    ("date_updated" > $19 OR $19 IS NULL) AND
    ("date_updated" < $20 OR $20 IS NULL)
)
ORDER BY "id"
LIMIT $22::int
OFFSET $21::int
`

type ListCountPromotionParams struct {
	ID              []uuid.UUID     `json:"id"`
	Code            []string        `json:"code"`
	OwnerID         []uuid.NullUUID `json:"owner_id"`
	Type            []PromotionType `json:"type"`
	Title           []string        `json:"title"`
	Description     []null.String   `json:"description"`
	IsActive        []bool          `json:"is_active"`
	AutoApply       []bool          `json:"auto_apply"`
	DateStarted     []time.Time     `json:"date_started"`
	DateStartedFrom null.Time       `json:"date_started_from"`
	DateStartedTo   null.Time       `json:"date_started_to"`
	DateEnded       []null.Time     `json:"date_ended"`
	DateEndedFrom   null.Time       `json:"date_ended_from"`
	DateEndedTo     null.Time       `json:"date_ended_to"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
	Offset          null.Int32      `json:"offset"`
	Limit           null.Int32      `json:"limit"`
}

type ListCountPromotionRow struct {
	PromotionPromotion PromotionPromotion `json:"promotion_promotion"`
	TotalCount         int64              `json:"total_count"`
}

func (q *Queries) ListCountPromotion(ctx context.Context, arg ListCountPromotionParams) ([]ListCountPromotionRow, error) {
	rows, err := q.db.Query(ctx, listCountPromotion,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateStartedFrom,
		arg.DateStartedTo,
		arg.DateEnded,
		arg.DateEndedFrom,
		arg.DateEndedTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountPromotionRow{}
	for rows.Next() {
		var i ListCountPromotionRow
		if err := rows.Scan(
			&i.PromotionPromotion.ID,
			&i.PromotionPromotion.Code,
			&i.PromotionPromotion.OwnerID,
			&i.PromotionPromotion.Type,
			&i.PromotionPromotion.Title,
			&i.PromotionPromotion.Description,
			&i.PromotionPromotion.IsActive,
			&i.PromotionPromotion.AutoApply,
			&i.PromotionPromotion.DateStarted,
			&i.PromotionPromotion.DateEnded,
			&i.PromotionPromotion.DateCreated,
			&i.PromotionPromotion.DateUpdated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotion = `-- name: ListPromotion :many
SELECT id, code, owner_id, type, title, description, is_active, auto_apply, date_started, date_ended, date_created, date_updated
FROM "promotion"."promotion"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("code" = ANY($2) OR $2 IS NULL) AND
    ("owner_id" = ANY($3) OR $3 IS NULL) AND
    ("type" = ANY($4) OR $4 IS NULL) AND
    ("title" = ANY($5) OR $5 IS NULL) AND
    ("description" = ANY($6) OR $6 IS NULL) AND
    ("is_active" = ANY($7) OR $7 IS NULL) AND
    ("auto_apply" = ANY($8) OR $8 IS NULL) AND
    ("date_started" = ANY($9) OR $9 IS NULL) AND
    ("date_started" > $10 OR $10 IS NULL) AND
    ("date_started" < $11 OR $11 IS NULL) AND
    ("date_ended" = ANY($12) OR $12 IS NULL) AND
    ("date_ended" > $13 OR $13 IS NULL) AND
    ("date_ended" < $14 OR $14 IS NULL) AND
    ("date_created" = ANY($15) OR $15 IS NULL) AND
    ("date_created" > $16 OR $16 IS NULL) AND
    ("date_created" < $17 OR $17 IS NULL) AND
    ("date_updated" = ANY($18) OR $18 IS NULL) AND
    ("date_updated" > $19 OR $19 IS NULL) AND
    ("date_updated" < $20 OR $20 IS NULL)
)
ORDER BY "id"
LIMIT $22::int
OFFSET $21::int
`

type ListPromotionParams struct {
	ID              []uuid.UUID     `json:"id"`
	Code            []string        `json:"code"`
	OwnerID         []uuid.NullUUID `json:"owner_id"`
	Type            []PromotionType `json:"type"`
	Title           []string        `json:"title"`
	Description     []null.String   `json:"description"`
	IsActive        []bool          `json:"is_active"`
	AutoApply       []bool          `json:"auto_apply"`
	DateStarted     []time.Time     `json:"date_started"`
	DateStartedFrom null.Time       `json:"date_started_from"`
	DateStartedTo   null.Time       `json:"date_started_to"`
	DateEnded       []null.Time     `json:"date_ended"`
	DateEndedFrom   null.Time       `json:"date_ended_from"`
	DateEndedTo     null.Time       `json:"date_ended_to"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
	Offset          null.Int32      `json:"offset"`
	Limit           null.Int32      `json:"limit"`
}

func (q *Queries) ListPromotion(ctx context.Context, arg ListPromotionParams) ([]PromotionPromotion, error) {
	rows, err := q.db.Query(ctx, listPromotion,
		arg.ID,
		arg.Code,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.DateStartedFrom,
		arg.DateStartedTo,
		arg.DateEnded,
		arg.DateEndedFrom,
		arg.DateEndedTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromotionPromotion{}
	for rows.Next() {
		var i PromotionPromotion
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.OwnerID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.AutoApply,
			&i.DateStarted,
			&i.DateEnded,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromotion = `-- name: UpdatePromotion :one
UPDATE "promotion"."promotion"
SET "code" = COALESCE($1, "code"),
    "owner_id" = CASE WHEN $2::bool = TRUE THEN NULL ELSE COALESCE($3, "owner_id") END,
    "type" = COALESCE($4, "type"),
    "title" = COALESCE($5, "title"),
    "description" = CASE WHEN $6::bool = TRUE THEN NULL ELSE COALESCE($7, "description") END,
    "is_active" = COALESCE($8, "is_active"),
    "auto_apply" = COALESCE($9, "auto_apply"),
    "date_started" = COALESCE($10, "date_started"),
    "date_ended" = CASE WHEN $11::bool = TRUE THEN NULL ELSE COALESCE($12, "date_ended") END,
    "date_created" = COALESCE($13, "date_created"),
    "date_updated" = COALESCE($14, "date_updated")
WHERE id = $15
RETURNING id, code, owner_id, type, title, description, is_active, auto_apply, date_started, date_ended, date_created, date_updated
`

type UpdatePromotionParams struct {
	Code            null.String       `json:"code"`
	NullOwnerID     bool              `json:"null_owner_id"`
	OwnerID         uuid.NullUUID     `json:"owner_id"`
	Type            NullPromotionType `json:"type"`
	Title           null.String       `json:"title"`
	NullDescription bool              `json:"null_description"`
	Description     null.String       `json:"description"`
	IsActive        null.Bool         `json:"is_active"`
	AutoApply       null.Bool         `json:"auto_apply"`
	DateStarted     null.Time         `json:"date_started"`
	NullDateEnded   bool              `json:"null_date_ended"`
	DateEnded       null.Time         `json:"date_ended"`
	DateCreated     null.Time         `json:"date_created"`
	DateUpdated     null.Time         `json:"date_updated"`
	ID              uuid.UUID         `json:"id"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (PromotionPromotion, error) {
	row := q.db.QueryRow(ctx, updatePromotion,
		arg.Code,
		arg.NullOwnerID,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.NullDescription,
		arg.Description,
		arg.IsActive,
		arg.AutoApply,
		arg.DateStarted,
		arg.NullDateEnded,
		arg.DateEnded,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i PromotionPromotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.AutoApply,
		&i.DateStarted,
		&i.DateEnded,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}
