// Code generated by genrestate; DO NOT EDIT.

package orderbiz

import (
	"context"
	"github.com/google/uuid"
	restateclient "shopnexus-server/internal/infras/restate"
	ordermodel "shopnexus-server/internal/module/order/model"
	sharedmodel "shopnexus-server/internal/shared/model"
)

const serviceName = "Order"

// OrderRestateClient implements OrderBiz via Restate HTTP ingress.
type OrderRestateClient struct {
	client *restateclient.Client
}

var _ OrderBiz = (*OrderRestateClient)(nil)

func NewOrderRestateClient(restateIngressURL string) *OrderRestateClient {
	return &OrderRestateClient{client: restateclient.NewClient(restateIngressURL)}
}

func (p *OrderRestateClient) Checkout(ctx context.Context, params CheckoutParams) (CheckoutResult, error) {
	return restateclient.Call[CheckoutResult](ctx, p.client, serviceName, "Checkout", params)
}

func (p *OrderRestateClient) ListPendingItems(ctx context.Context, params ListPendingItemsParams) (sharedmodel.PaginateResult[ordermodel.OrderItem], error) {
	return restateclient.Call[sharedmodel.PaginateResult[ordermodel.OrderItem]](ctx, p.client, serviceName, "ListPendingItems", params)
}

func (p *OrderRestateClient) CancelPendingItem(ctx context.Context, params CancelPendingItemParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "CancelPendingItem", params)
}

func (p *OrderRestateClient) ListIncomingItems(ctx context.Context, params ListIncomingItemsParams) (sharedmodel.PaginateResult[ordermodel.OrderItem], error) {
	return restateclient.Call[sharedmodel.PaginateResult[ordermodel.OrderItem]](ctx, p.client, serviceName, "ListIncomingItems", params)
}

func (p *OrderRestateClient) ConfirmItems(ctx context.Context, params ConfirmItemsParams) (ordermodel.Order, error) {
	return restateclient.Call[ordermodel.Order](ctx, p.client, serviceName, "ConfirmItems", params)
}

func (p *OrderRestateClient) RejectItems(ctx context.Context, params RejectItemsParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "RejectItems", params)
}

func (p *OrderRestateClient) GetOrder(ctx context.Context, orderID uuid.UUID) (ordermodel.Order, error) {
	return restateclient.Call[ordermodel.Order](ctx, p.client, serviceName, "GetOrder", orderID)
}

func (p *OrderRestateClient) ListOrders(ctx context.Context, params ListOrdersParams) (sharedmodel.PaginateResult[ordermodel.Order], error) {
	return restateclient.Call[sharedmodel.PaginateResult[ordermodel.Order]](ctx, p.client, serviceName, "ListOrders", params)
}

func (p *OrderRestateClient) ListSellerOrders(ctx context.Context, params ListSellerOrdersParams) (sharedmodel.PaginateResult[ordermodel.Order], error) {
	return restateclient.Call[sharedmodel.PaginateResult[ordermodel.Order]](ctx, p.client, serviceName, "ListSellerOrders", params)
}

func (p *OrderRestateClient) CancelOrder(ctx context.Context, params CancelOrderParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "CancelOrder", params)
}

func (p *OrderRestateClient) PayOrders(ctx context.Context, params PayOrdersParams) (PayOrdersResult, error) {
	return restateclient.Call[PayOrdersResult](ctx, p.client, serviceName, "PayOrders", params)
}

func (p *OrderRestateClient) ConfirmPayment(ctx context.Context, params ConfirmPaymentParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "ConfirmPayment", params)
}

func (p *OrderRestateClient) GetCart(ctx context.Context, params GetCartParams) ([]ordermodel.CartItem, error) {
	return restateclient.Call[[]ordermodel.CartItem](ctx, p.client, serviceName, "GetCart", params)
}

func (p *OrderRestateClient) UpdateCart(ctx context.Context, params UpdateCartParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "UpdateCart", params)
}

func (p *OrderRestateClient) ClearCart(ctx context.Context, params ClearCartParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "ClearCart", params)
}

func (p *OrderRestateClient) ListRefunds(ctx context.Context, params ListRefundsParams) (sharedmodel.PaginateResult[ordermodel.Refund], error) {
	return restateclient.Call[sharedmodel.PaginateResult[ordermodel.Refund]](ctx, p.client, serviceName, "ListRefunds", params)
}

func (p *OrderRestateClient) CreateRefund(ctx context.Context, params CreateRefundParams) (ordermodel.Refund, error) {
	return restateclient.Call[ordermodel.Refund](ctx, p.client, serviceName, "CreateRefund", params)
}

func (p *OrderRestateClient) UpdateRefund(ctx context.Context, params UpdateRefundParams) (ordermodel.Refund, error) {
	return restateclient.Call[ordermodel.Refund](ctx, p.client, serviceName, "UpdateRefund", params)
}

func (p *OrderRestateClient) CancelRefund(ctx context.Context, params CancelRefundParams) error {
	return restateclient.Send(ctx, p.client, serviceName, "CancelRefund", params)
}

func (p *OrderRestateClient) ConfirmRefund(ctx context.Context, params ConfirmRefundParams) (ordermodel.Refund, error) {
	return restateclient.Call[ordermodel.Refund](ctx, p.client, serviceName, "ConfirmRefund", params)
}
