// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_account.sql

package accountdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countAccount = `-- name: CountAccount :one
SELECT COUNT(*)
FROM "account"."account"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("type" = ANY($2) OR $2 IS NULL) AND
    ("status" = ANY($3) OR $3 IS NULL) AND
    ("phone" = ANY($4) OR $4 IS NULL) AND
    ("email" = ANY($5) OR $5 IS NULL) AND
    ("username" = ANY($6) OR $6 IS NULL) AND
    ("password" = ANY($7) OR $7 IS NULL) AND
    ("date_created" = ANY($8) OR $8 IS NULL) AND
    ("date_created" > $9 OR $9 IS NULL) AND
    ("date_created" < $10 OR $10 IS NULL) AND
    ("date_updated" = ANY($11) OR $11 IS NULL) AND
    ("date_updated" > $12 OR $12 IS NULL) AND
    ("date_updated" < $13 OR $13 IS NULL)
)
`

type CountAccountParams struct {
	ID              []uuid.UUID     `json:"id"`
	Type            []AccountType   `json:"type"`
	Status          []AccountStatus `json:"status"`
	Phone           []null.String   `json:"phone"`
	Email           []null.String   `json:"email"`
	Username        []null.String   `json:"username"`
	Password        []null.String   `json:"password"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
}

func (q *Queries) CountAccount(ctx context.Context, arg CountAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccount,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO "account"."account" ("id", "type", "status", "phone", "email", "username", "password", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, type, status, phone, email, username, password, date_created, date_updated
`

type CreateAccountParams struct {
	ID          uuid.UUID     `json:"id"`
	Type        AccountType   `json:"type"`
	Status      AccountStatus `json:"status"`
	Phone       null.String   `json:"phone"`
	Email       null.String   `json:"email"`
	Username    null.String   `json:"username"`
	Password    null.String   `json:"password"`
	DateCreated time.Time     `json:"date_created"`
	DateUpdated time.Time     `json:"date_updated"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AccountAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i AccountAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

type CreateCopyAccountParams struct {
	ID          uuid.UUID     `json:"id"`
	Type        AccountType   `json:"type"`
	Status      AccountStatus `json:"status"`
	Phone       null.String   `json:"phone"`
	Email       null.String   `json:"email"`
	Username    null.String   `json:"username"`
	Password    null.String   `json:"password"`
	DateCreated time.Time     `json:"date_created"`
	DateUpdated time.Time     `json:"date_updated"`
}

type CreateCopyDefaultAccountParams struct {
	Type     AccountType `json:"type"`
	Phone    null.String `json:"phone"`
	Email    null.String `json:"email"`
	Username null.String `json:"username"`
	Password null.String `json:"password"`
}

const createDefaultAccount = `-- name: CreateDefaultAccount :one
INSERT INTO "account"."account" ("type", "phone", "email", "username", "password")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, status, phone, email, username, password, date_created, date_updated
`

type CreateDefaultAccountParams struct {
	Type     AccountType `json:"type"`
	Phone    null.String `json:"phone"`
	Email    null.String `json:"email"`
	Username null.String `json:"username"`
	Password null.String `json:"password"`
}

func (q *Queries) CreateDefaultAccount(ctx context.Context, arg CreateDefaultAccountParams) (AccountAccount, error) {
	row := q.db.QueryRow(ctx, createDefaultAccount,
		arg.Type,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	var i AccountAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM "account"."account"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("type" = ANY($2) OR $2 IS NULL) AND
    ("status" = ANY($3) OR $3 IS NULL) AND
    ("phone" = ANY($4) OR $4 IS NULL) AND
    ("email" = ANY($5) OR $5 IS NULL) AND
    ("username" = ANY($6) OR $6 IS NULL) AND
    ("password" = ANY($7) OR $7 IS NULL) AND
    ("date_created" = ANY($8) OR $8 IS NULL) AND
    ("date_created" > $9 OR $9 IS NULL) AND
    ("date_created" < $10 OR $10 IS NULL) AND
    ("date_updated" = ANY($11) OR $11 IS NULL) AND
    ("date_updated" > $12 OR $12 IS NULL) AND
    ("date_updated" < $13 OR $13 IS NULL)
)
`

type DeleteAccountParams struct {
	ID              []uuid.UUID     `json:"id"`
	Type            []AccountType   `json:"type"`
	Status          []AccountStatus `json:"status"`
	Phone           []null.String   `json:"phone"`
	Email           []null.String   `json:"email"`
	Username        []null.String   `json:"username"`
	Password        []null.String   `json:"password"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, type, status, phone, email, username, password, date_created, date_updated
FROM "account"."account"
WHERE ("id" = $1) OR ("phone" = $2) OR ("email" = $3) OR ("username" = $4)
`

type GetAccountParams struct {
	ID       uuid.NullUUID `json:"id"`
	Phone    null.String   `json:"phone"`
	Email    null.String   `json:"email"`
	Username null.String   `json:"username"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (AccountAccount, error) {
	row := q.db.QueryRow(ctx, getAccount,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Username,
	)
	var i AccountAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const listAccount = `-- name: ListAccount :many
SELECT id, type, status, phone, email, username, password, date_created, date_updated
FROM "account"."account"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("type" = ANY($2) OR $2 IS NULL) AND
    ("status" = ANY($3) OR $3 IS NULL) AND
    ("phone" = ANY($4) OR $4 IS NULL) AND
    ("email" = ANY($5) OR $5 IS NULL) AND
    ("username" = ANY($6) OR $6 IS NULL) AND
    ("password" = ANY($7) OR $7 IS NULL) AND
    ("date_created" = ANY($8) OR $8 IS NULL) AND
    ("date_created" > $9 OR $9 IS NULL) AND
    ("date_created" < $10 OR $10 IS NULL) AND
    ("date_updated" = ANY($11) OR $11 IS NULL) AND
    ("date_updated" > $12 OR $12 IS NULL) AND
    ("date_updated" < $13 OR $13 IS NULL)
)
ORDER BY "id"
LIMIT $15::int
OFFSET $14::int
`

type ListAccountParams struct {
	ID              []uuid.UUID     `json:"id"`
	Type            []AccountType   `json:"type"`
	Status          []AccountStatus `json:"status"`
	Phone           []null.String   `json:"phone"`
	Email           []null.String   `json:"email"`
	Username        []null.String   `json:"username"`
	Password        []null.String   `json:"password"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
	Offset          null.Int32      `json:"offset"`
	Limit           null.Int32      `json:"limit"`
}

func (q *Queries) ListAccount(ctx context.Context, arg ListAccountParams) ([]AccountAccount, error) {
	rows, err := q.db.Query(ctx, listAccount,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAccount{}
	for rows.Next() {
		var i AccountAccount
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Phone,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.DateCreated,
			&i.DateUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountAccount = `-- name: ListCountAccount :many
SELECT embed_account.id, embed_account.type, embed_account.status, embed_account.phone, embed_account.email, embed_account.username, embed_account.password, embed_account.date_created, embed_account.date_updated, COUNT(*) OVER() as total_count
FROM "account"."account" embed_account
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("type" = ANY($2) OR $2 IS NULL) AND
    ("status" = ANY($3) OR $3 IS NULL) AND
    ("phone" = ANY($4) OR $4 IS NULL) AND
    ("email" = ANY($5) OR $5 IS NULL) AND
    ("username" = ANY($6) OR $6 IS NULL) AND
    ("password" = ANY($7) OR $7 IS NULL) AND
    ("date_created" = ANY($8) OR $8 IS NULL) AND
    ("date_created" > $9 OR $9 IS NULL) AND
    ("date_created" < $10 OR $10 IS NULL) AND
    ("date_updated" = ANY($11) OR $11 IS NULL) AND
    ("date_updated" > $12 OR $12 IS NULL) AND
    ("date_updated" < $13 OR $13 IS NULL)
)
ORDER BY "id"
LIMIT $15::int
OFFSET $14::int
`

type ListCountAccountParams struct {
	ID              []uuid.UUID     `json:"id"`
	Type            []AccountType   `json:"type"`
	Status          []AccountStatus `json:"status"`
	Phone           []null.String   `json:"phone"`
	Email           []null.String   `json:"email"`
	Username        []null.String   `json:"username"`
	Password        []null.String   `json:"password"`
	DateCreated     []time.Time     `json:"date_created"`
	DateCreatedFrom null.Time       `json:"date_created_from"`
	DateCreatedTo   null.Time       `json:"date_created_to"`
	DateUpdated     []time.Time     `json:"date_updated"`
	DateUpdatedFrom null.Time       `json:"date_updated_from"`
	DateUpdatedTo   null.Time       `json:"date_updated_to"`
	Offset          null.Int32      `json:"offset"`
	Limit           null.Int32      `json:"limit"`
}

type ListCountAccountRow struct {
	AccountAccount AccountAccount `json:"account_account"`
	TotalCount     int64          `json:"total_count"`
}

func (q *Queries) ListCountAccount(ctx context.Context, arg ListCountAccountParams) ([]ListCountAccountRow, error) {
	rows, err := q.db.Query(ctx, listCountAccount,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Phone,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountAccountRow{}
	for rows.Next() {
		var i ListCountAccountRow
		if err := rows.Scan(
			&i.AccountAccount.ID,
			&i.AccountAccount.Type,
			&i.AccountAccount.Status,
			&i.AccountAccount.Phone,
			&i.AccountAccount.Email,
			&i.AccountAccount.Username,
			&i.AccountAccount.Password,
			&i.AccountAccount.DateCreated,
			&i.AccountAccount.DateUpdated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE "account"."account"
SET "type" = COALESCE($1, "type"),
    "status" = COALESCE($2, "status"),
    "phone" = CASE WHEN $3::bool = TRUE THEN NULL ELSE COALESCE($4, "phone") END,
    "email" = CASE WHEN $5::bool = TRUE THEN NULL ELSE COALESCE($6, "email") END,
    "username" = CASE WHEN $7::bool = TRUE THEN NULL ELSE COALESCE($8, "username") END,
    "password" = CASE WHEN $9::bool = TRUE THEN NULL ELSE COALESCE($10, "password") END,
    "date_created" = COALESCE($11, "date_created"),
    "date_updated" = COALESCE($12, "date_updated")
WHERE id = $13
RETURNING id, type, status, phone, email, username, password, date_created, date_updated
`

type UpdateAccountParams struct {
	Type         NullAccountType   `json:"type"`
	Status       NullAccountStatus `json:"status"`
	NullPhone    bool              `json:"null_phone"`
	Phone        null.String       `json:"phone"`
	NullEmail    bool              `json:"null_email"`
	Email        null.String       `json:"email"`
	NullUsername bool              `json:"null_username"`
	Username     null.String       `json:"username"`
	NullPassword bool              `json:"null_password"`
	Password     null.String       `json:"password"`
	DateCreated  null.Time         `json:"date_created"`
	DateUpdated  null.Time         `json:"date_updated"`
	ID           uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (AccountAccount, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Type,
		arg.Status,
		arg.NullPhone,
		arg.Phone,
		arg.NullEmail,
		arg.Email,
		arg.NullUsername,
		arg.Username,
		arg.NullPassword,
		arg.Password,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i AccountAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Phone,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}
