// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package chatdb

import (
	"context"
)

// iteratorForCreateCopyConversation implements pgx.CopyFromSource.
type iteratorForCreateCopyConversation struct {
	rows                 []CreateCopyConversationParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyConversation) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyConversation) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].BuyerID,
		r.rows[0].SellerID,
		r.rows[0].LastMessageAt,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyConversation) Err() error {
	return nil
}

func (q *Queries) CreateCopyConversation(ctx context.Context, arg []CreateCopyConversationParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chat", "conversation"}, []string{"id", "buyer_id", "seller_id", "last_message_at", "date_created"}, &iteratorForCreateCopyConversation{rows: arg})
}

// iteratorForCreateCopyDefaultConversation implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultConversation struct {
	rows                 []CreateCopyDefaultConversationParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultConversation) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultConversation) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BuyerID,
		r.rows[0].SellerID,
		r.rows[0].LastMessageAt,
	}, nil
}

func (r iteratorForCreateCopyDefaultConversation) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultConversation(ctx context.Context, arg []CreateCopyDefaultConversationParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chat", "conversation"}, []string{"buyer_id", "seller_id", "last_message_at"}, &iteratorForCreateCopyDefaultConversation{rows: arg})
}

// iteratorForCreateCopyDefaultMessage implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultMessage struct {
	rows                 []CreateCopyDefaultMessageParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultMessage) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultMessage) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ConversationID,
		r.rows[0].SenderID,
		r.rows[0].Type,
		r.rows[0].Content,
		r.rows[0].Data,
	}, nil
}

func (r iteratorForCreateCopyDefaultMessage) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultMessage(ctx context.Context, arg []CreateCopyDefaultMessageParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chat", "message"}, []string{"conversation_id", "sender_id", "type", "content", "data"}, &iteratorForCreateCopyDefaultMessage{rows: arg})
}

// iteratorForCreateCopyMessage implements pgx.CopyFromSource.
type iteratorForCreateCopyMessage struct {
	rows                 []CreateCopyMessageParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyMessage) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyMessage) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ConversationID,
		r.rows[0].SenderID,
		r.rows[0].Type,
		r.rows[0].Content,
		r.rows[0].Status,
		r.rows[0].Data,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyMessage) Err() error {
	return nil
}

func (q *Queries) CreateCopyMessage(ctx context.Context, arg []CreateCopyMessageParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"chat", "message"}, []string{"conversation_id", "sender_id", "type", "content", "status", "data", "date_created"}, &iteratorForCreateCopyMessage{rows: arg})
}
