// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type Querier interface {
	CountConversation(ctx context.Context, arg CountConversationParams) (int64, error)
	CountConversationByAccount(ctx context.Context, accountID uuid.UUID) (int64, error)
	CountMessage(ctx context.Context, arg CountMessageParams) (int64, error)
	CountMessageByConversation(ctx context.Context, conversationID uuid.UUID) (int64, error)
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	CreateBatchConversation(ctx context.Context, arg []CreateBatchConversationParams) *CreateBatchConversationBatchResults
	CreateBatchMessage(ctx context.Context, arg []CreateBatchMessageParams) *CreateBatchMessageBatchResults
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (ChatConversation, error)
	CreateCopyConversation(ctx context.Context, arg []CreateCopyConversationParams) (int64, error)
	CreateCopyDefaultConversation(ctx context.Context, arg []CreateCopyDefaultConversationParams) (int64, error)
	CreateCopyDefaultMessage(ctx context.Context, arg []CreateCopyDefaultMessageParams) (int64, error)
	CreateCopyMessage(ctx context.Context, arg []CreateCopyMessageParams) (int64, error)
	CreateDefaultConversation(ctx context.Context, arg CreateDefaultConversationParams) (ChatConversation, error)
	CreateDefaultMessage(ctx context.Context, arg CreateDefaultMessageParams) (ChatMessage, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error)
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	// Code generated by pgtempl. DO NOT EDIT.
	// Queries for table: chat.conversation
	GetConversation(ctx context.Context, arg GetConversationParams) (ChatConversation, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (ChatConversation, error)
	GetConversationByParticipants(ctx context.Context, arg GetConversationByParticipantsParams) (ChatConversation, error)
	// Code generated by pgtempl. DO NOT EDIT.
	// Queries for table: chat.message
	GetMessage(ctx context.Context, id null.Int) (ChatMessage, error)
	ListConversation(ctx context.Context, arg ListConversationParams) ([]ChatConversation, error)
	ListConversationByAccount(ctx context.Context, arg ListConversationByAccountParams) ([]ChatConversation, error)
	ListCountConversation(ctx context.Context, arg ListCountConversationParams) ([]ListCountConversationRow, error)
	ListCountMessage(ctx context.Context, arg ListCountMessageParams) ([]ListCountMessageRow, error)
	ListMessage(ctx context.Context, arg ListMessageParams) ([]ChatMessage, error)
	ListMessageByConversation(ctx context.Context, arg ListMessageByConversationParams) ([]ChatMessage, error)
	MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (ChatConversation, error)
	UpdateConversationLastMessage(ctx context.Context, id uuid.UUID) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (ChatMessage, error)
}

var _ Querier = (*Queries)(nil)
