-- Code generated by pgtempl. DO NOT EDIT.
-- This file contains all queries for the database schema.


-- ========================================
-- Queries for table: account.account
-- ========================================

-- name: GetAccount :one
SELECT *
FROM "account"."account"
WHERE ("id" = sqlc.narg('id')) OR ("phone" = sqlc.narg('phone')) OR ("email" = sqlc.narg('email')) OR ("username" = sqlc.narg('username'));

-- name: CountAccount :one
SELECT COUNT(*)
FROM "account"."account"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("number" = ANY(sqlc.slice('number')) OR sqlc.slice('number') IS NULL) AND
    ("number" >= sqlc.narg('number_from') OR sqlc.narg('number_from') IS NULL) AND
    ("number" <= sqlc.narg('number_to') OR sqlc.narg('number_to') IS NULL) AND
    ("status" = ANY(sqlc.slice('status')) OR sqlc.slice('status') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("email" = ANY(sqlc.slice('email')) OR sqlc.slice('email') IS NULL) AND
    ("username" = ANY(sqlc.slice('username')) OR sqlc.slice('username') IS NULL) AND
    ("password" = ANY(sqlc.slice('password')) OR sqlc.slice('password') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("default_contact_id" = ANY(sqlc.slice('default_contact_id')) OR sqlc.slice('default_contact_id') IS NULL) AND
    ("default_wallet_id" = ANY(sqlc.slice('default_wallet_id')) OR sqlc.slice('default_wallet_id') IS NULL)
);

-- name: ListAccount :many
SELECT *
FROM "account"."account"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("number" = ANY(sqlc.slice('number')) OR sqlc.slice('number') IS NULL) AND
    ("number" >= sqlc.narg('number_from') OR sqlc.narg('number_from') IS NULL) AND
    ("number" <= sqlc.narg('number_to') OR sqlc.narg('number_to') IS NULL) AND
    ("status" = ANY(sqlc.slice('status')) OR sqlc.slice('status') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("email" = ANY(sqlc.slice('email')) OR sqlc.slice('email') IS NULL) AND
    ("username" = ANY(sqlc.slice('username')) OR sqlc.slice('username') IS NULL) AND
    ("password" = ANY(sqlc.slice('password')) OR sqlc.slice('password') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("default_contact_id" = ANY(sqlc.slice('default_contact_id')) OR sqlc.slice('default_contact_id') IS NULL) AND
    ("default_wallet_id" = ANY(sqlc.slice('default_wallet_id')) OR sqlc.slice('default_wallet_id') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountAccount :many
SELECT sqlc.embed(embed_account), COUNT(*) OVER() as total_count
FROM "account"."account" embed_account
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("number" = ANY(sqlc.slice('number')) OR sqlc.slice('number') IS NULL) AND
    ("number" >= sqlc.narg('number_from') OR sqlc.narg('number_from') IS NULL) AND
    ("number" <= sqlc.narg('number_to') OR sqlc.narg('number_to') IS NULL) AND
    ("status" = ANY(sqlc.slice('status')) OR sqlc.slice('status') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("email" = ANY(sqlc.slice('email')) OR sqlc.slice('email') IS NULL) AND
    ("username" = ANY(sqlc.slice('username')) OR sqlc.slice('username') IS NULL) AND
    ("password" = ANY(sqlc.slice('password')) OR sqlc.slice('password') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("default_contact_id" = ANY(sqlc.slice('default_contact_id')) OR sqlc.slice('default_contact_id') IS NULL) AND
    ("default_wallet_id" = ANY(sqlc.slice('default_wallet_id')) OR sqlc.slice('default_wallet_id') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateAccount :one
INSERT INTO "account"."account" ("id", "status", "phone", "email", "username", "password", "date_created", "default_contact_id", "default_wallet_id")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING *;

-- name: CreateBatchAccount :batchone
INSERT INTO "account"."account" ("id", "status", "phone", "email", "username", "password", "date_created", "default_contact_id", "default_wallet_id")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING *;

-- name: CreateCopyAccount :copyfrom
INSERT INTO "account"."account" ("id", "status", "phone", "email", "username", "password", "date_created", "default_contact_id", "default_wallet_id")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9);

-- name: CreateDefaultAccount :one
INSERT INTO "account"."account" ("phone", "email", "username", "password", "default_contact_id", "default_wallet_id")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: CreateCopyDefaultAccount :copyfrom
INSERT INTO "account"."account" ("phone", "email", "username", "password", "default_contact_id", "default_wallet_id")
VALUES ($1, $2, $3, $4, $5, $6);

-- name: UpdateAccount :one
UPDATE "account"."account"
SET "status" = COALESCE(sqlc.narg('status'), "status"),
    "phone" = CASE WHEN sqlc.arg('null_phone')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('phone'), "phone") END,
    "email" = CASE WHEN sqlc.arg('null_email')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('email'), "email") END,
    "username" = CASE WHEN sqlc.arg('null_username')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('username'), "username") END,
    "password" = CASE WHEN sqlc.arg('null_password')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('password'), "password") END,
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created"),
    "default_contact_id" = CASE WHEN sqlc.arg('null_default_contact_id')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('default_contact_id'), "default_contact_id") END,
    "default_wallet_id" = CASE WHEN sqlc.arg('null_default_wallet_id')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('default_wallet_id'), "default_wallet_id") END
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteAccount :exec
DELETE FROM "account"."account"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("number" = ANY(sqlc.slice('number')) OR sqlc.slice('number') IS NULL) AND
    ("number" >= sqlc.narg('number_from') OR sqlc.narg('number_from') IS NULL) AND
    ("number" <= sqlc.narg('number_to') OR sqlc.narg('number_to') IS NULL) AND
    ("status" = ANY(sqlc.slice('status')) OR sqlc.slice('status') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("email" = ANY(sqlc.slice('email')) OR sqlc.slice('email') IS NULL) AND
    ("username" = ANY(sqlc.slice('username')) OR sqlc.slice('username') IS NULL) AND
    ("password" = ANY(sqlc.slice('password')) OR sqlc.slice('password') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("default_contact_id" = ANY(sqlc.slice('default_contact_id')) OR sqlc.slice('default_contact_id') IS NULL) AND
    ("default_wallet_id" = ANY(sqlc.slice('default_wallet_id')) OR sqlc.slice('default_wallet_id') IS NULL)
);

-- ========================================
-- Queries for table: account.contact
-- ========================================

-- name: GetContact :one
SELECT *
FROM "account"."contact"
WHERE ("id" = sqlc.narg('id'));

-- name: CountContact :one
SELECT COUNT(*)
FROM "account"."contact"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("full_name" = ANY(sqlc.slice('full_name')) OR sqlc.slice('full_name') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("address_type" = ANY(sqlc.slice('address_type')) OR sqlc.slice('address_type') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("address" = ANY(sqlc.slice('address')) OR sqlc.slice('address') IS NULL) AND
    ("latitude" = ANY(sqlc.slice('latitude')) OR sqlc.slice('latitude') IS NULL) AND
    ("latitude" >= sqlc.narg('latitude_from') OR sqlc.narg('latitude_from') IS NULL) AND
    ("latitude" <= sqlc.narg('latitude_to') OR sqlc.narg('latitude_to') IS NULL) AND
    ("longitude" = ANY(sqlc.slice('longitude')) OR sqlc.slice('longitude') IS NULL) AND
    ("longitude" >= sqlc.narg('longitude_from') OR sqlc.narg('longitude_from') IS NULL) AND
    ("longitude" <= sqlc.narg('longitude_to') OR sqlc.narg('longitude_to') IS NULL)
);

-- name: ListContact :many
SELECT *
FROM "account"."contact"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("full_name" = ANY(sqlc.slice('full_name')) OR sqlc.slice('full_name') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("address_type" = ANY(sqlc.slice('address_type')) OR sqlc.slice('address_type') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("address" = ANY(sqlc.slice('address')) OR sqlc.slice('address') IS NULL) AND
    ("latitude" = ANY(sqlc.slice('latitude')) OR sqlc.slice('latitude') IS NULL) AND
    ("latitude" >= sqlc.narg('latitude_from') OR sqlc.narg('latitude_from') IS NULL) AND
    ("latitude" <= sqlc.narg('latitude_to') OR sqlc.narg('latitude_to') IS NULL) AND
    ("longitude" = ANY(sqlc.slice('longitude')) OR sqlc.slice('longitude') IS NULL) AND
    ("longitude" >= sqlc.narg('longitude_from') OR sqlc.narg('longitude_from') IS NULL) AND
    ("longitude" <= sqlc.narg('longitude_to') OR sqlc.narg('longitude_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountContact :many
SELECT sqlc.embed(embed_contact), COUNT(*) OVER() as total_count
FROM "account"."contact" embed_contact
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("full_name" = ANY(sqlc.slice('full_name')) OR sqlc.slice('full_name') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("address_type" = ANY(sqlc.slice('address_type')) OR sqlc.slice('address_type') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("address" = ANY(sqlc.slice('address')) OR sqlc.slice('address') IS NULL) AND
    ("latitude" = ANY(sqlc.slice('latitude')) OR sqlc.slice('latitude') IS NULL) AND
    ("latitude" >= sqlc.narg('latitude_from') OR sqlc.narg('latitude_from') IS NULL) AND
    ("latitude" <= sqlc.narg('latitude_to') OR sqlc.narg('latitude_to') IS NULL) AND
    ("longitude" = ANY(sqlc.slice('longitude')) OR sqlc.slice('longitude') IS NULL) AND
    ("longitude" >= sqlc.narg('longitude_from') OR sqlc.narg('longitude_from') IS NULL) AND
    ("longitude" <= sqlc.narg('longitude_to') OR sqlc.narg('longitude_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateContact :one
INSERT INTO "account"."contact" ("id", "account_id", "full_name", "phone", "phone_verified", "address_type", "date_created", "address", "latitude", "longitude")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING *;

-- name: CreateBatchContact :batchone
INSERT INTO "account"."contact" ("id", "account_id", "full_name", "phone", "phone_verified", "address_type", "date_created", "address", "latitude", "longitude")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING *;

-- name: CreateCopyContact :copyfrom
INSERT INTO "account"."contact" ("id", "account_id", "full_name", "phone", "phone_verified", "address_type", "date_created", "address", "latitude", "longitude")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10);

-- name: CreateDefaultContact :one
INSERT INTO "account"."contact" ("account_id", "full_name", "phone", "address_type", "address", "latitude", "longitude")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING *;

-- name: CreateCopyDefaultContact :copyfrom
INSERT INTO "account"."contact" ("account_id", "full_name", "phone", "address_type", "address", "latitude", "longitude")
VALUES ($1, $2, $3, $4, $5, $6, $7);

-- name: UpdateContact :one
UPDATE "account"."contact"
SET "account_id" = COALESCE(sqlc.narg('account_id'), "account_id"),
    "full_name" = COALESCE(sqlc.narg('full_name'), "full_name"),
    "phone" = COALESCE(sqlc.narg('phone'), "phone"),
    "phone_verified" = COALESCE(sqlc.narg('phone_verified'), "phone_verified"),
    "address_type" = COALESCE(sqlc.narg('address_type'), "address_type"),
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created"),
    "address" = COALESCE(sqlc.narg('address'), "address"),
    "latitude" = COALESCE(sqlc.narg('latitude'), "latitude"),
    "longitude" = COALESCE(sqlc.narg('longitude'), "longitude")
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteContact :exec
DELETE FROM "account"."contact"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("full_name" = ANY(sqlc.slice('full_name')) OR sqlc.slice('full_name') IS NULL) AND
    ("phone" = ANY(sqlc.slice('phone')) OR sqlc.slice('phone') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("address_type" = ANY(sqlc.slice('address_type')) OR sqlc.slice('address_type') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("address" = ANY(sqlc.slice('address')) OR sqlc.slice('address') IS NULL) AND
    ("latitude" = ANY(sqlc.slice('latitude')) OR sqlc.slice('latitude') IS NULL) AND
    ("latitude" >= sqlc.narg('latitude_from') OR sqlc.narg('latitude_from') IS NULL) AND
    ("latitude" <= sqlc.narg('latitude_to') OR sqlc.narg('latitude_to') IS NULL) AND
    ("longitude" = ANY(sqlc.slice('longitude')) OR sqlc.slice('longitude') IS NULL) AND
    ("longitude" >= sqlc.narg('longitude_from') OR sqlc.narg('longitude_from') IS NULL) AND
    ("longitude" <= sqlc.narg('longitude_to') OR sqlc.narg('longitude_to') IS NULL)
);

-- ========================================
-- Queries for table: account.profile
-- ========================================

-- name: GetProfile :one
SELECT *
FROM "account"."profile"
WHERE ("id" = sqlc.narg('id')) OR ("avatar_rs_id" = sqlc.narg('avatar_rs_id'));

-- name: CountProfile :one
SELECT COUNT(*)
FROM "account"."profile"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("gender" = ANY(sqlc.slice('gender')) OR sqlc.slice('gender') IS NULL) AND
    ("name" = ANY(sqlc.slice('name')) OR sqlc.slice('name') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL) AND
    ("date_of_birth" = ANY(sqlc.slice('date_of_birth')) OR sqlc.slice('date_of_birth') IS NULL) AND
    ("date_of_birth" >= sqlc.narg('date_of_birth_from') OR sqlc.narg('date_of_birth_from') IS NULL) AND
    ("date_of_birth" <= sqlc.narg('date_of_birth_to') OR sqlc.narg('date_of_birth_to') IS NULL) AND
    ("avatar_rs_id" = ANY(sqlc.slice('avatar_rs_id')) OR sqlc.slice('avatar_rs_id') IS NULL) AND
    ("email_verified" = ANY(sqlc.slice('email_verified')) OR sqlc.slice('email_verified') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("balance" = ANY(sqlc.slice('balance')) OR sqlc.slice('balance') IS NULL) AND
    ("balance" >= sqlc.narg('balance_from') OR sqlc.narg('balance_from') IS NULL) AND
    ("balance" <= sqlc.narg('balance_to') OR sqlc.narg('balance_to') IS NULL) AND
    ("country" = ANY(sqlc.slice('country')) OR sqlc.slice('country') IS NULL)
);

-- name: ListProfile :many
SELECT *
FROM "account"."profile"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("gender" = ANY(sqlc.slice('gender')) OR sqlc.slice('gender') IS NULL) AND
    ("name" = ANY(sqlc.slice('name')) OR sqlc.slice('name') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL) AND
    ("date_of_birth" = ANY(sqlc.slice('date_of_birth')) OR sqlc.slice('date_of_birth') IS NULL) AND
    ("date_of_birth" >= sqlc.narg('date_of_birth_from') OR sqlc.narg('date_of_birth_from') IS NULL) AND
    ("date_of_birth" <= sqlc.narg('date_of_birth_to') OR sqlc.narg('date_of_birth_to') IS NULL) AND
    ("avatar_rs_id" = ANY(sqlc.slice('avatar_rs_id')) OR sqlc.slice('avatar_rs_id') IS NULL) AND
    ("email_verified" = ANY(sqlc.slice('email_verified')) OR sqlc.slice('email_verified') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("balance" = ANY(sqlc.slice('balance')) OR sqlc.slice('balance') IS NULL) AND
    ("balance" >= sqlc.narg('balance_from') OR sqlc.narg('balance_from') IS NULL) AND
    ("balance" <= sqlc.narg('balance_to') OR sqlc.narg('balance_to') IS NULL) AND
    ("country" = ANY(sqlc.slice('country')) OR sqlc.slice('country') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountProfile :many
SELECT sqlc.embed(embed_profile), COUNT(*) OVER() as total_count
FROM "account"."profile" embed_profile
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("gender" = ANY(sqlc.slice('gender')) OR sqlc.slice('gender') IS NULL) AND
    ("name" = ANY(sqlc.slice('name')) OR sqlc.slice('name') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL) AND
    ("date_of_birth" = ANY(sqlc.slice('date_of_birth')) OR sqlc.slice('date_of_birth') IS NULL) AND
    ("date_of_birth" >= sqlc.narg('date_of_birth_from') OR sqlc.narg('date_of_birth_from') IS NULL) AND
    ("date_of_birth" <= sqlc.narg('date_of_birth_to') OR sqlc.narg('date_of_birth_to') IS NULL) AND
    ("avatar_rs_id" = ANY(sqlc.slice('avatar_rs_id')) OR sqlc.slice('avatar_rs_id') IS NULL) AND
    ("email_verified" = ANY(sqlc.slice('email_verified')) OR sqlc.slice('email_verified') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("balance" = ANY(sqlc.slice('balance')) OR sqlc.slice('balance') IS NULL) AND
    ("balance" >= sqlc.narg('balance_from') OR sqlc.narg('balance_from') IS NULL) AND
    ("balance" <= sqlc.narg('balance_to') OR sqlc.narg('balance_to') IS NULL) AND
    ("country" = ANY(sqlc.slice('country')) OR sqlc.slice('country') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateProfile :one
INSERT INTO "account"."profile" ("id", "gender", "name", "description", "date_of_birth", "avatar_rs_id", "email_verified", "phone_verified", "date_created", "balance", "country")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING *;

-- name: CreateBatchProfile :batchone
INSERT INTO "account"."profile" ("id", "gender", "name", "description", "date_of_birth", "avatar_rs_id", "email_verified", "phone_verified", "date_created", "balance", "country")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING *;

-- name: CreateCopyProfile :copyfrom
INSERT INTO "account"."profile" ("id", "gender", "name", "description", "date_of_birth", "avatar_rs_id", "email_verified", "phone_verified", "date_created", "balance", "country")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11);

-- name: CreateDefaultProfile :one
INSERT INTO "account"."profile" ("id", "gender", "name", "date_of_birth", "avatar_rs_id", "country")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: CreateCopyDefaultProfile :copyfrom
INSERT INTO "account"."profile" ("id", "gender", "name", "date_of_birth", "avatar_rs_id", "country")
VALUES ($1, $2, $3, $4, $5, $6);

-- name: UpdateProfile :one
UPDATE "account"."profile"
SET "gender" = CASE WHEN sqlc.arg('null_gender')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('gender'), "gender") END,
    "name" = COALESCE(sqlc.narg('name'), "name"),
    "description" = COALESCE(sqlc.narg('description'), "description"),
    "date_of_birth" = CASE WHEN sqlc.arg('null_date_of_birth')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('date_of_birth'), "date_of_birth") END,
    "avatar_rs_id" = CASE WHEN sqlc.arg('null_avatar_rs_id')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('avatar_rs_id'), "avatar_rs_id") END,
    "email_verified" = COALESCE(sqlc.narg('email_verified'), "email_verified"),
    "phone_verified" = COALESCE(sqlc.narg('phone_verified'), "phone_verified"),
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created"),
    "balance" = COALESCE(sqlc.narg('balance'), "balance"),
    "country" = COALESCE(sqlc.narg('country'), "country")
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteProfile :exec
DELETE FROM "account"."profile"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("gender" = ANY(sqlc.slice('gender')) OR sqlc.slice('gender') IS NULL) AND
    ("name" = ANY(sqlc.slice('name')) OR sqlc.slice('name') IS NULL) AND
    ("description" = ANY(sqlc.slice('description')) OR sqlc.slice('description') IS NULL) AND
    ("date_of_birth" = ANY(sqlc.slice('date_of_birth')) OR sqlc.slice('date_of_birth') IS NULL) AND
    ("date_of_birth" >= sqlc.narg('date_of_birth_from') OR sqlc.narg('date_of_birth_from') IS NULL) AND
    ("date_of_birth" <= sqlc.narg('date_of_birth_to') OR sqlc.narg('date_of_birth_to') IS NULL) AND
    ("avatar_rs_id" = ANY(sqlc.slice('avatar_rs_id')) OR sqlc.slice('avatar_rs_id') IS NULL) AND
    ("email_verified" = ANY(sqlc.slice('email_verified')) OR sqlc.slice('email_verified') IS NULL) AND
    ("phone_verified" = ANY(sqlc.slice('phone_verified')) OR sqlc.slice('phone_verified') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("balance" = ANY(sqlc.slice('balance')) OR sqlc.slice('balance') IS NULL) AND
    ("balance" >= sqlc.narg('balance_from') OR sqlc.narg('balance_from') IS NULL) AND
    ("balance" <= sqlc.narg('balance_to') OR sqlc.narg('balance_to') IS NULL) AND
    ("country" = ANY(sqlc.slice('country')) OR sqlc.slice('country') IS NULL)
);

-- ========================================
-- Queries for table: account.notification
-- ========================================

-- name: GetNotification :one
SELECT *
FROM "account"."notification"
WHERE ("id" = sqlc.narg('id'));

-- name: CountNotification :one
SELECT COUNT(*)
FROM "account"."notification"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("type" = ANY(sqlc.slice('type')) OR sqlc.slice('type') IS NULL) AND
    ("channel" = ANY(sqlc.slice('channel')) OR sqlc.slice('channel') IS NULL) AND
    ("title" = ANY(sqlc.slice('title')) OR sqlc.slice('title') IS NULL) AND
    ("is_read" = ANY(sqlc.slice('is_read')) OR sqlc.slice('is_read') IS NULL) AND
    ("content" = ANY(sqlc.slice('content')) OR sqlc.slice('content') IS NULL) AND
    ("metadata" = ANY(sqlc.slice('metadata')) OR sqlc.slice('metadata') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("date_sent" = ANY(sqlc.slice('date_sent')) OR sqlc.slice('date_sent') IS NULL) AND
    ("date_sent" >= sqlc.narg('date_sent_from') OR sqlc.narg('date_sent_from') IS NULL) AND
    ("date_sent" <= sqlc.narg('date_sent_to') OR sqlc.narg('date_sent_to') IS NULL) AND
    ("date_scheduled" = ANY(sqlc.slice('date_scheduled')) OR sqlc.slice('date_scheduled') IS NULL) AND
    ("date_scheduled" >= sqlc.narg('date_scheduled_from') OR sqlc.narg('date_scheduled_from') IS NULL) AND
    ("date_scheduled" <= sqlc.narg('date_scheduled_to') OR sqlc.narg('date_scheduled_to') IS NULL)
);

-- name: ListNotification :many
SELECT *
FROM "account"."notification"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("type" = ANY(sqlc.slice('type')) OR sqlc.slice('type') IS NULL) AND
    ("channel" = ANY(sqlc.slice('channel')) OR sqlc.slice('channel') IS NULL) AND
    ("title" = ANY(sqlc.slice('title')) OR sqlc.slice('title') IS NULL) AND
    ("is_read" = ANY(sqlc.slice('is_read')) OR sqlc.slice('is_read') IS NULL) AND
    ("content" = ANY(sqlc.slice('content')) OR sqlc.slice('content') IS NULL) AND
    ("metadata" = ANY(sqlc.slice('metadata')) OR sqlc.slice('metadata') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("date_sent" = ANY(sqlc.slice('date_sent')) OR sqlc.slice('date_sent') IS NULL) AND
    ("date_sent" >= sqlc.narg('date_sent_from') OR sqlc.narg('date_sent_from') IS NULL) AND
    ("date_sent" <= sqlc.narg('date_sent_to') OR sqlc.narg('date_sent_to') IS NULL) AND
    ("date_scheduled" = ANY(sqlc.slice('date_scheduled')) OR sqlc.slice('date_scheduled') IS NULL) AND
    ("date_scheduled" >= sqlc.narg('date_scheduled_from') OR sqlc.narg('date_scheduled_from') IS NULL) AND
    ("date_scheduled" <= sqlc.narg('date_scheduled_to') OR sqlc.narg('date_scheduled_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountNotification :many
SELECT sqlc.embed(embed_notification), COUNT(*) OVER() as total_count
FROM "account"."notification" embed_notification
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("type" = ANY(sqlc.slice('type')) OR sqlc.slice('type') IS NULL) AND
    ("channel" = ANY(sqlc.slice('channel')) OR sqlc.slice('channel') IS NULL) AND
    ("title" = ANY(sqlc.slice('title')) OR sqlc.slice('title') IS NULL) AND
    ("is_read" = ANY(sqlc.slice('is_read')) OR sqlc.slice('is_read') IS NULL) AND
    ("content" = ANY(sqlc.slice('content')) OR sqlc.slice('content') IS NULL) AND
    ("metadata" = ANY(sqlc.slice('metadata')) OR sqlc.slice('metadata') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("date_sent" = ANY(sqlc.slice('date_sent')) OR sqlc.slice('date_sent') IS NULL) AND
    ("date_sent" >= sqlc.narg('date_sent_from') OR sqlc.narg('date_sent_from') IS NULL) AND
    ("date_sent" <= sqlc.narg('date_sent_to') OR sqlc.narg('date_sent_to') IS NULL) AND
    ("date_scheduled" = ANY(sqlc.slice('date_scheduled')) OR sqlc.slice('date_scheduled') IS NULL) AND
    ("date_scheduled" >= sqlc.narg('date_scheduled_from') OR sqlc.narg('date_scheduled_from') IS NULL) AND
    ("date_scheduled" <= sqlc.narg('date_scheduled_to') OR sqlc.narg('date_scheduled_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateNotification :one
INSERT INTO "account"."notification" ("account_id", "type", "channel", "title", "is_read", "content", "metadata", "date_created", "date_sent", "date_scheduled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING *;

-- name: CreateBatchNotification :batchone
INSERT INTO "account"."notification" ("account_id", "type", "channel", "title", "is_read", "content", "metadata", "date_created", "date_sent", "date_scheduled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING *;

-- name: CreateCopyNotification :copyfrom
INSERT INTO "account"."notification" ("account_id", "type", "channel", "title", "is_read", "content", "metadata", "date_created", "date_sent", "date_scheduled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10);

-- name: CreateDefaultNotification :one
INSERT INTO "account"."notification" ("account_id", "type", "channel", "title", "content", "metadata", "date_sent", "date_scheduled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING *;

-- name: CreateCopyDefaultNotification :copyfrom
INSERT INTO "account"."notification" ("account_id", "type", "channel", "title", "content", "metadata", "date_sent", "date_scheduled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8);

-- name: UpdateNotification :one
UPDATE "account"."notification"
SET "account_id" = COALESCE(sqlc.narg('account_id'), "account_id"),
    "type" = COALESCE(sqlc.narg('type'), "type"),
    "channel" = COALESCE(sqlc.narg('channel'), "channel"),
    "title" = COALESCE(sqlc.narg('title'), "title"),
    "is_read" = COALESCE(sqlc.narg('is_read'), "is_read"),
    "content" = COALESCE(sqlc.narg('content'), "content"),
    "metadata" = CASE WHEN sqlc.arg('null_metadata')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('metadata'), "metadata") END,
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created"),
    "date_sent" = CASE WHEN sqlc.arg('null_date_sent')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('date_sent'), "date_sent") END,
    "date_scheduled" = CASE WHEN sqlc.arg('null_date_scheduled')::bool = TRUE THEN NULL ELSE COALESCE(sqlc.narg('date_scheduled'), "date_scheduled") END
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteNotification :exec
DELETE FROM "account"."notification"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("type" = ANY(sqlc.slice('type')) OR sqlc.slice('type') IS NULL) AND
    ("channel" = ANY(sqlc.slice('channel')) OR sqlc.slice('channel') IS NULL) AND
    ("title" = ANY(sqlc.slice('title')) OR sqlc.slice('title') IS NULL) AND
    ("is_read" = ANY(sqlc.slice('is_read')) OR sqlc.slice('is_read') IS NULL) AND
    ("content" = ANY(sqlc.slice('content')) OR sqlc.slice('content') IS NULL) AND
    ("metadata" = ANY(sqlc.slice('metadata')) OR sqlc.slice('metadata') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL) AND
    ("date_sent" = ANY(sqlc.slice('date_sent')) OR sqlc.slice('date_sent') IS NULL) AND
    ("date_sent" >= sqlc.narg('date_sent_from') OR sqlc.narg('date_sent_from') IS NULL) AND
    ("date_sent" <= sqlc.narg('date_sent_to') OR sqlc.narg('date_sent_to') IS NULL) AND
    ("date_scheduled" = ANY(sqlc.slice('date_scheduled')) OR sqlc.slice('date_scheduled') IS NULL) AND
    ("date_scheduled" >= sqlc.narg('date_scheduled_from') OR sqlc.narg('date_scheduled_from') IS NULL) AND
    ("date_scheduled" <= sqlc.narg('date_scheduled_to') OR sqlc.narg('date_scheduled_to') IS NULL)
);

-- ========================================
-- Queries for table: account.favorite
-- ========================================

-- name: GetFavorite :one
SELECT *
FROM "account"."favorite"
WHERE ("id" = sqlc.narg('id')) OR ("account_id" = sqlc.narg('account_id') AND "spu_id" = sqlc.narg('spu_id'));

-- name: CountFavorite :one
SELECT COUNT(*)
FROM "account"."favorite"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("spu_id" = ANY(sqlc.slice('spu_id')) OR sqlc.slice('spu_id') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
);

-- name: ListFavorite :many
SELECT *
FROM "account"."favorite"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("spu_id" = ANY(sqlc.slice('spu_id')) OR sqlc.slice('spu_id') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountFavorite :many
SELECT sqlc.embed(embed_favorite), COUNT(*) OVER() as total_count
FROM "account"."favorite" embed_favorite
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("spu_id" = ANY(sqlc.slice('spu_id')) OR sqlc.slice('spu_id') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateFavorite :one
INSERT INTO "account"."favorite" ("account_id", "spu_id", "date_created")
VALUES ($1, $2, $3)
RETURNING *;

-- name: CreateBatchFavorite :batchone
INSERT INTO "account"."favorite" ("account_id", "spu_id", "date_created")
VALUES ($1, $2, $3)
RETURNING *;

-- name: CreateCopyFavorite :copyfrom
INSERT INTO "account"."favorite" ("account_id", "spu_id", "date_created")
VALUES ($1, $2, $3);

-- name: CreateDefaultFavorite :one
INSERT INTO "account"."favorite" ("account_id", "spu_id")
VALUES ($1, $2)
RETURNING *;

-- name: CreateCopyDefaultFavorite :copyfrom
INSERT INTO "account"."favorite" ("account_id", "spu_id")
VALUES ($1, $2);

-- name: UpdateFavorite :one
UPDATE "account"."favorite"
SET "account_id" = COALESCE(sqlc.narg('account_id'), "account_id"),
    "spu_id" = COALESCE(sqlc.narg('spu_id'), "spu_id"),
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created")
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteFavorite :exec
DELETE FROM "account"."favorite"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("spu_id" = ANY(sqlc.slice('spu_id')) OR sqlc.slice('spu_id') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
);

-- ========================================
-- Queries for table: account.wallet
-- ========================================

-- name: GetWallet :one
SELECT *
FROM "account"."wallet"
WHERE ("id" = sqlc.narg('id'));

-- name: CountWallet :one
SELECT COUNT(*)
FROM "account"."wallet"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("option" = ANY(sqlc.slice('option')) OR sqlc.slice('option') IS NULL) AND
    ("label" = ANY(sqlc.slice('label')) OR sqlc.slice('label') IS NULL) AND
    ("data" = ANY(sqlc.slice('data')) OR sqlc.slice('data') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
);

-- name: ListWallet :many
SELECT *
FROM "account"."wallet"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("option" = ANY(sqlc.slice('option')) OR sqlc.slice('option') IS NULL) AND
    ("label" = ANY(sqlc.slice('label')) OR sqlc.slice('label') IS NULL) AND
    ("data" = ANY(sqlc.slice('data')) OR sqlc.slice('data') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: ListCountWallet :many
SELECT sqlc.embed(embed_wallet), COUNT(*) OVER() as total_count
FROM "account"."wallet" embed_wallet
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("option" = ANY(sqlc.slice('option')) OR sqlc.slice('option') IS NULL) AND
    ("label" = ANY(sqlc.slice('label')) OR sqlc.slice('label') IS NULL) AND
    ("data" = ANY(sqlc.slice('data')) OR sqlc.slice('data') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
)
ORDER BY "id"
LIMIT sqlc.narg('limit')::int
OFFSET sqlc.narg('offset')::int;

-- name: CreateWallet :one
INSERT INTO "account"."wallet" ("id", "account_id", "option", "label", "data", "date_created")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: CreateBatchWallet :batchone
INSERT INTO "account"."wallet" ("id", "account_id", "option", "label", "data", "date_created")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: CreateCopyWallet :copyfrom
INSERT INTO "account"."wallet" ("id", "account_id", "option", "label", "data", "date_created")
VALUES ($1, $2, $3, $4, $5, $6);

-- name: CreateDefaultWallet :one
INSERT INTO "account"."wallet" ("account_id", "option", "label", "data")
VALUES ($1, $2, $3, $4)
RETURNING *;

-- name: CreateCopyDefaultWallet :copyfrom
INSERT INTO "account"."wallet" ("account_id", "option", "label", "data")
VALUES ($1, $2, $3, $4);

-- name: UpdateWallet :one
UPDATE "account"."wallet"
SET "account_id" = COALESCE(sqlc.narg('account_id'), "account_id"),
    "option" = COALESCE(sqlc.narg('option'), "option"),
    "label" = COALESCE(sqlc.narg('label'), "label"),
    "data" = COALESCE(sqlc.narg('data'), "data"),
    "date_created" = COALESCE(sqlc.narg('date_created'), "date_created")
WHERE id = sqlc.arg('id')
RETURNING *;

-- name: DeleteWallet :exec
DELETE FROM "account"."wallet"
WHERE (
    ("id" = ANY(sqlc.slice('id')) OR sqlc.slice('id') IS NULL) AND
    ("account_id" = ANY(sqlc.slice('account_id')) OR sqlc.slice('account_id') IS NULL) AND
    ("option" = ANY(sqlc.slice('option')) OR sqlc.slice('option') IS NULL) AND
    ("label" = ANY(sqlc.slice('label')) OR sqlc.slice('label') IS NULL) AND
    ("data" = ANY(sqlc.slice('data')) OR sqlc.slice('data') IS NULL) AND
    ("date_created" = ANY(sqlc.slice('date_created')) OR sqlc.slice('date_created') IS NULL) AND
    ("date_created" >= sqlc.narg('date_created_from') OR sqlc.narg('date_created_from') IS NULL) AND
    ("date_created" <= sqlc.narg('date_created_to') OR sqlc.narg('date_created_to') IS NULL)
);