// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderRefundMethod string

const (
	OrderRefundMethodPickUp  OrderRefundMethod = "PickUp"
	OrderRefundMethodDropOff OrderRefundMethod = "DropOff"
)

func (e *OrderRefundMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderRefundMethod(s)
	case string:
		*e = OrderRefundMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderRefundMethod: %T", src)
	}
	return nil
}

type NullOrderRefundMethod struct {
	OrderRefundMethod OrderRefundMethod `json:"order_refund_method"`
	Valid             bool              `json:"valid"` // Valid is true if OrderRefundMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderRefundMethod) Scan(value interface{}) error {
	if value == nil {
		ns.OrderRefundMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderRefundMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderRefundMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderRefundMethod), nil
}

func (e OrderRefundMethod) Valid() bool {
	switch e {
	case OrderRefundMethodPickUp,
		OrderRefundMethodDropOff:
		return true
	}
	return false
}

func AllOrderRefundMethodValues() []OrderRefundMethod {
	return []OrderRefundMethod{
		OrderRefundMethodPickUp,
		OrderRefundMethodDropOff,
	}
}

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "Pending"
	OrderStatusProcessing OrderStatus = "Processing"
	OrderStatusSuccess    OrderStatus = "Success"
	OrderStatusCancelled  OrderStatus = "Cancelled"
	OrderStatusFailed     OrderStatus = "Failed"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusPending,
		OrderStatusProcessing,
		OrderStatusSuccess,
		OrderStatusCancelled,
		OrderStatusFailed:
		return true
	}
	return false
}

func AllOrderStatusValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPending,
		OrderStatusProcessing,
		OrderStatusSuccess,
		OrderStatusCancelled,
		OrderStatusFailed,
	}
}

type OrderCartItem struct {
	ID        int64     `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int64     `json:"quantity"`
}

type OrderItem struct {
	ID              int64           `json:"id"`
	OrderID         uuid.NullUUID   `json:"order_id"`
	AccountID       uuid.UUID       `json:"account_id"`
	SellerID        uuid.UUID       `json:"seller_id"`
	SkuID           uuid.UUID       `json:"sku_id"`
	SpuID           uuid.UUID       `json:"spu_id"`
	SkuName         string          `json:"sku_name"`
	Address         string          `json:"address"`
	Note            null.String     `json:"note"`
	SerialIds       json.RawMessage `json:"serial_ids"`
	Quantity        int64           `json:"quantity"`
	TransportOption string          `json:"transport_option"`
	SubtotalAmount  int64           `json:"subtotal_amount"`
	PaidAmount      int64           `json:"paid_amount"`
	PaymentTxID     int64           `json:"payment_tx_id"`
	DateCreated     time.Time       `json:"date_created"`
	DateCancelled   null.Time       `json:"date_cancelled"`
	CancelledByID   uuid.NullUUID   `json:"cancelled_by_id"`
	RefundTxID      null.Int        `json:"refund_tx_id"`
}

type OrderOrder struct {
	ID            uuid.UUID   `json:"id"`
	BuyerID       uuid.UUID   `json:"buyer_id"`
	SellerID      uuid.UUID   `json:"seller_id"`
	TransportID   int64       `json:"transport_id"`
	Address       string      `json:"address"`
	DateCreated   time.Time   `json:"date_created"`
	ConfirmedByID uuid.UUID   `json:"confirmed_by_id"`
	SellerTxID    int64       `json:"seller_tx_id"`
	Note          null.String `json:"note"`
}

type OrderRefund struct {
	ID            uuid.UUID         `json:"id"`
	AccountID     uuid.UUID         `json:"account_id"`
	OrderItemID   int64             `json:"order_item_id"`
	TransportID   int64             `json:"transport_id"`
	Method        OrderRefundMethod `json:"method"`
	Reason        string            `json:"reason"`
	Address       null.String       `json:"address"`
	DateCreated   time.Time         `json:"date_created"`
	Status        OrderStatus       `json:"status"`
	AcceptedByID  uuid.NullUUID     `json:"accepted_by_id"`
	DateAccepted  null.Time         `json:"date_accepted"`
	RejectionNote null.String       `json:"rejection_note"`
	ApprovedByID  uuid.NullUUID     `json:"approved_by_id"`
	DateApproved  null.Time         `json:"date_approved"`
	RefundTxID    null.Int          `json:"refund_tx_id"`
}

type OrderRefundDispute struct {
	ID           uuid.UUID     `json:"id"`
	AccountID    uuid.UUID     `json:"account_id"`
	RefundID     uuid.UUID     `json:"refund_id"`
	Reason       string        `json:"reason"`
	Status       OrderStatus   `json:"status"`
	Note         string        `json:"note"`
	DateCreated  time.Time     `json:"date_created"`
	ResolvedByID uuid.NullUUID `json:"resolved_by_id"`
	DateResolved null.Time     `json:"date_resolved"`
}

type OrderTransaction struct {
	ID            int64           `json:"id"`
	FromID        uuid.NullUUID   `json:"from_id"`
	ToID          uuid.NullUUID   `json:"to_id"`
	Type          string          `json:"type"`
	Status        OrderStatus     `json:"status"`
	Note          string          `json:"note"`
	PaymentOption null.String     `json:"payment_option"`
	WalletID      uuid.NullUUID   `json:"wallet_id"`
	Data          json.RawMessage `json:"data"`
	Amount        int64           `json:"amount"`
	FromCurrency  string          `json:"from_currency"`
	ToCurrency    string          `json:"to_currency"`
	ExchangeRate  pgtype.Numeric  `json:"exchange_rate"`
	DateCreated   time.Time       `json:"date_created"`
	DatePaid      null.Time       `json:"date_paid"`
	DateExpired   time.Time       `json:"date_expired"`
}

type OrderTransport struct {
	ID          int64           `json:"id"`
	Option      string          `json:"option"`
	Status      NullOrderStatus `json:"status"`
	Data        json.RawMessage `json:"data"`
	DateCreated time.Time       `json:"date_created"`
}
