// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const hasPurchasedSku = `-- name: HasPurchasedSku :one
SELECT EXISTS(
    SELECT 1 FROM "order".item i
    WHERE i.account_id = $1
      AND i.order_id IS NOT NULL
      AND i.date_cancelled IS NULL
      AND i.sku_id = ANY($2::UUID[])
) AS has_purchased
`

type HasPurchasedSkuParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	SkuIds    []uuid.UUID `json:"sku_ids"`
}

func (q *Queries) HasPurchasedSku(ctx context.Context, arg HasPurchasedSkuParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPurchasedSku, arg.AccountID, arg.SkuIds)
	var has_purchased bool
	err := row.Scan(&has_purchased)
	return has_purchased, err
}

const listCountBuyerOrder = `-- name: ListCountBuyerOrder :many

SELECT embed_order.id, embed_order.buyer_id, embed_order.seller_id, embed_order.transport_id, embed_order.confirmed_by_id, embed_order.address, embed_order.product_cost, embed_order.product_discount, embed_order.transport_cost, embed_order.total, embed_order.note, embed_order.data, embed_order.date_created, COUNT(*) OVER() as total_count
FROM "order"."order" embed_order
WHERE embed_order."buyer_id" = $1
    AND (embed_order."id"::text ILIKE '%' || $2::text || '%' OR $2 IS NULL)
ORDER BY embed_order."date_created" DESC
LIMIT $4::int
OFFSET $3::int
`

type ListCountBuyerOrderParams struct {
	BuyerID uuid.UUID   `json:"buyer_id"`
	Search  null.String `json:"search"`
	Offset  null.Int32  `json:"offset"`
	Limit   null.Int32  `json:"limit"`
}

type ListCountBuyerOrderRow struct {
	OrderOrder OrderOrder `json:"order_order"`
	TotalCount int64      `json:"total_count"`
}

// Custom order queries
func (q *Queries) ListCountBuyerOrder(ctx context.Context, arg ListCountBuyerOrderParams) ([]ListCountBuyerOrderRow, error) {
	rows, err := q.db.Query(ctx, listCountBuyerOrder,
		arg.BuyerID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountBuyerOrderRow{}
	for rows.Next() {
		var i ListCountBuyerOrderRow
		if err := rows.Scan(
			&i.OrderOrder.ID,
			&i.OrderOrder.BuyerID,
			&i.OrderOrder.SellerID,
			&i.OrderOrder.TransportID,
			&i.OrderOrder.ConfirmedByID,
			&i.OrderOrder.Address,
			&i.OrderOrder.ProductCost,
			&i.OrderOrder.ProductDiscount,
			&i.OrderOrder.TransportCost,
			&i.OrderOrder.Total,
			&i.OrderOrder.Note,
			&i.OrderOrder.Data,
			&i.OrderOrder.DateCreated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountSellerOrder = `-- name: ListCountSellerOrder :many
SELECT embed_order.id, embed_order.buyer_id, embed_order.seller_id, embed_order.transport_id, embed_order.confirmed_by_id, embed_order.address, embed_order.product_cost, embed_order.product_discount, embed_order.transport_cost, embed_order.total, embed_order.note, embed_order.data, embed_order.date_created, COUNT(*) OVER() as total_count
FROM "order"."order" embed_order
WHERE embed_order."seller_id" = $1
    AND (embed_order."id"::text ILIKE '%' || $2::text || '%' OR $2 IS NULL)
ORDER BY embed_order."date_created" DESC
LIMIT $4::int
OFFSET $3::int
`

type ListCountSellerOrderParams struct {
	SellerID uuid.UUID   `json:"seller_id"`
	Search   null.String `json:"search"`
	Offset   null.Int32  `json:"offset"`
	Limit    null.Int32  `json:"limit"`
}

type ListCountSellerOrderRow struct {
	OrderOrder OrderOrder `json:"order_order"`
	TotalCount int64      `json:"total_count"`
}

func (q *Queries) ListCountSellerOrder(ctx context.Context, arg ListCountSellerOrderParams) ([]ListCountSellerOrderRow, error) {
	rows, err := q.db.Query(ctx, listCountSellerOrder,
		arg.SellerID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountSellerOrderRow{}
	for rows.Next() {
		var i ListCountSellerOrderRow
		if err := rows.Scan(
			&i.OrderOrder.ID,
			&i.OrderOrder.BuyerID,
			&i.OrderOrder.SellerID,
			&i.OrderOrder.TransportID,
			&i.OrderOrder.ConfirmedByID,
			&i.OrderOrder.Address,
			&i.OrderOrder.ProductCost,
			&i.OrderOrder.ProductDiscount,
			&i.OrderOrder.TransportCost,
			&i.OrderOrder.Total,
			&i.OrderOrder.Note,
			&i.OrderOrder.Data,
			&i.OrderOrder.DateCreated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuccessOrdersBySkus = `-- name: ListSuccessOrdersBySkus :many
SELECT DISTINCT o.id, o.buyer_id, o.seller_id, o.transport_id, o.confirmed_by_id, o.address, o.product_cost, o.product_discount, o.transport_cost, o.total, o.note, o.data, o.date_created FROM "order"."order" o
JOIN "order".item i ON i.order_id = o.id
WHERE o.buyer_id = $1
  AND i.sku_id = ANY($2::UUID[])
  AND i.date_cancelled IS NULL
ORDER BY o.date_created DESC
`

type ListSuccessOrdersBySkusParams struct {
	BuyerID uuid.UUID   `json:"buyer_id"`
	SkuIds  []uuid.UUID `json:"sku_ids"`
}

func (q *Queries) ListSuccessOrdersBySkus(ctx context.Context, arg ListSuccessOrdersBySkusParams) ([]OrderOrder, error) {
	rows, err := q.db.Query(ctx, listSuccessOrdersBySkus, arg.BuyerID, arg.SkuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderOrder{}
	for rows.Next() {
		var i OrderOrder
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.SellerID,
			&i.TransportID,
			&i.ConfirmedByID,
			&i.Address,
			&i.ProductCost,
			&i.ProductDiscount,
			&i.TransportCost,
			&i.Total,
			&i.Note,
			&i.Data,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateOrderForReview = `-- name: ValidateOrderForReview :one
SELECT EXISTS(
    SELECT 1 FROM "order"."order" o
    JOIN "order".item i ON i.order_id = o.id
    WHERE o.id = $1
      AND o.buyer_id = $2
      AND i.sku_id = ANY($3::UUID[])
      AND i.date_cancelled IS NULL
) AS is_valid
`

type ValidateOrderForReviewParams struct {
	OrderID uuid.UUID   `json:"order_id"`
	BuyerID uuid.UUID   `json:"buyer_id"`
	SkuIds  []uuid.UUID `json:"sku_ids"`
}

func (q *Queries) ValidateOrderForReview(ctx context.Context, arg ValidateOrderForReviewParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateOrderForReview, arg.OrderID, arg.BuyerID, arg.SkuIds)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
