// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_cart_item.sql

package orderdb

import (
	"context"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCartItem = `-- name: CountCartItem :one
SELECT COUNT(*)
FROM "order"."cart_item"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("sku_id" = ANY($3) OR $3 IS NULL) AND
    ("quantity" = ANY($4) OR $4 IS NULL) AND
    ("quantity" > $5 OR $5 IS NULL) AND
    ("quantity" < $6 OR $6 IS NULL)
)
`

type CountCartItemParams struct {
	ID           []int64     `json:"id"`
	AccountID    []uuid.UUID `json:"account_id"`
	SkuID        []uuid.UUID `json:"sku_id"`
	Quantity     []int64     `json:"quantity"`
	QuantityFrom null.Int    `json:"quantity_from"`
	QuantityTo   null.Int    `json:"quantity_to"`
}

func (q *Queries) CountCartItem(ctx context.Context, arg CountCartItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItem,
		arg.ID,
		arg.AccountID,
		arg.SkuID,
		arg.Quantity,
		arg.QuantityFrom,
		arg.QuantityTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO "order"."cart_item" ("account_id", "sku_id", "quantity")
VALUES ($1, $2, $3)
RETURNING id, account_id, sku_id, quantity
`

type CreateCartItemParams struct {
	AccountID uuid.UUID `json:"account_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int64     `json:"quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (OrderCartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem, arg.AccountID, arg.SkuID, arg.Quantity)
	var i OrderCartItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SkuID,
		&i.Quantity,
	)
	return i, err
}

type CreateCopyCartItemParams struct {
	AccountID uuid.UUID `json:"account_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int64     `json:"quantity"`
}

type CreateCopyDefaultCartItemParams struct {
	AccountID uuid.UUID `json:"account_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int64     `json:"quantity"`
}

const createDefaultCartItem = `-- name: CreateDefaultCartItem :one
INSERT INTO "order"."cart_item" ("account_id", "sku_id", "quantity")
VALUES ($1, $2, $3)
RETURNING id, account_id, sku_id, quantity
`

type CreateDefaultCartItemParams struct {
	AccountID uuid.UUID `json:"account_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int64     `json:"quantity"`
}

func (q *Queries) CreateDefaultCartItem(ctx context.Context, arg CreateDefaultCartItemParams) (OrderCartItem, error) {
	row := q.db.QueryRow(ctx, createDefaultCartItem, arg.AccountID, arg.SkuID, arg.Quantity)
	var i OrderCartItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SkuID,
		&i.Quantity,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM "order"."cart_item"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("sku_id" = ANY($3) OR $3 IS NULL) AND
    ("quantity" = ANY($4) OR $4 IS NULL) AND
    ("quantity" > $5 OR $5 IS NULL) AND
    ("quantity" < $6 OR $6 IS NULL)
)
`

type DeleteCartItemParams struct {
	ID           []int64     `json:"id"`
	AccountID    []uuid.UUID `json:"account_id"`
	SkuID        []uuid.UUID `json:"sku_id"`
	Quantity     []int64     `json:"quantity"`
	QuantityFrom null.Int    `json:"quantity_from"`
	QuantityTo   null.Int    `json:"quantity_to"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem,
		arg.ID,
		arg.AccountID,
		arg.SkuID,
		arg.Quantity,
		arg.QuantityFrom,
		arg.QuantityTo,
	)
	return err
}

const getCartItem = `-- name: GetCartItem :one

SELECT id, account_id, sku_id, quantity
FROM "order"."cart_item"
WHERE ("id" = $1) OR ("account_id" = $2 AND "sku_id" = $3)
`

type GetCartItemParams struct {
	ID        pgtype.Int8   `json:"id"`
	AccountID uuid.NullUUID `json:"account_id"`
	SkuID     uuid.NullUUID `json:"sku_id"`
}

// Code generated by pgtempl. DO NOT EDIT.
// Queries for table: order.cart_item
func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (OrderCartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.ID, arg.AccountID, arg.SkuID)
	var i OrderCartItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SkuID,
		&i.Quantity,
	)
	return i, err
}

const listCartItem = `-- name: ListCartItem :many
SELECT id, account_id, sku_id, quantity
FROM "order"."cart_item"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("sku_id" = ANY($3) OR $3 IS NULL) AND
    ("quantity" = ANY($4) OR $4 IS NULL) AND
    ("quantity" > $5 OR $5 IS NULL) AND
    ("quantity" < $6 OR $6 IS NULL)
)
ORDER BY "id"
LIMIT $8::int
OFFSET $7::int
`

type ListCartItemParams struct {
	ID           []int64     `json:"id"`
	AccountID    []uuid.UUID `json:"account_id"`
	SkuID        []uuid.UUID `json:"sku_id"`
	Quantity     []int64     `json:"quantity"`
	QuantityFrom null.Int    `json:"quantity_from"`
	QuantityTo   null.Int    `json:"quantity_to"`
	Offset       null.Int32  `json:"offset"`
	Limit        null.Int32  `json:"limit"`
}

func (q *Queries) ListCartItem(ctx context.Context, arg ListCartItemParams) ([]OrderCartItem, error) {
	rows, err := q.db.Query(ctx, listCartItem,
		arg.ID,
		arg.AccountID,
		arg.SkuID,
		arg.Quantity,
		arg.QuantityFrom,
		arg.QuantityTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderCartItem{}
	for rows.Next() {
		var i OrderCartItem
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.SkuID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountCartItem = `-- name: ListCountCartItem :many
SELECT embed_cart_item.id, embed_cart_item.account_id, embed_cart_item.sku_id, embed_cart_item.quantity, COUNT(*) OVER() as total_count
FROM "order"."cart_item" embed_cart_item
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("sku_id" = ANY($3) OR $3 IS NULL) AND
    ("quantity" = ANY($4) OR $4 IS NULL) AND
    ("quantity" > $5 OR $5 IS NULL) AND
    ("quantity" < $6 OR $6 IS NULL)
)
ORDER BY "id"
LIMIT $8::int
OFFSET $7::int
`

type ListCountCartItemParams struct {
	ID           []int64     `json:"id"`
	AccountID    []uuid.UUID `json:"account_id"`
	SkuID        []uuid.UUID `json:"sku_id"`
	Quantity     []int64     `json:"quantity"`
	QuantityFrom null.Int    `json:"quantity_from"`
	QuantityTo   null.Int    `json:"quantity_to"`
	Offset       null.Int32  `json:"offset"`
	Limit        null.Int32  `json:"limit"`
}

type ListCountCartItemRow struct {
	OrderCartItem OrderCartItem `json:"order_cart_item"`
	TotalCount    int64         `json:"total_count"`
}

func (q *Queries) ListCountCartItem(ctx context.Context, arg ListCountCartItemParams) ([]ListCountCartItemRow, error) {
	rows, err := q.db.Query(ctx, listCountCartItem,
		arg.ID,
		arg.AccountID,
		arg.SkuID,
		arg.Quantity,
		arg.QuantityFrom,
		arg.QuantityTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountCartItemRow{}
	for rows.Next() {
		var i ListCountCartItemRow
		if err := rows.Scan(
			&i.OrderCartItem.ID,
			&i.OrderCartItem.AccountID,
			&i.OrderCartItem.SkuID,
			&i.OrderCartItem.Quantity,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE "order"."cart_item"
SET "account_id" = COALESCE($1, "account_id"),
    "sku_id" = COALESCE($2, "sku_id"),
    "quantity" = COALESCE($3, "quantity")
WHERE id = $4
RETURNING id, account_id, sku_id, quantity
`

type UpdateCartItemParams struct {
	AccountID uuid.NullUUID `json:"account_id"`
	SkuID     uuid.NullUUID `json:"sku_id"`
	Quantity  null.Int      `json:"quantity"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (OrderCartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem,
		arg.AccountID,
		arg.SkuID,
		arg.Quantity,
		arg.ID,
	)
	var i OrderCartItem
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SkuID,
		&i.Quantity,
	)
	return i, err
}
