// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_shipment.sql

package orderdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countShipment = `-- name: CountShipment :one
SELECT COUNT(*)
FROM "order"."shipment"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("option" = ANY($2) OR $2 IS NULL) AND
    ("tracking_code" = ANY($3) OR $3 IS NULL) AND
    ("status" = ANY($4) OR $4 IS NULL) AND
    ("label_url" = ANY($5) OR $5 IS NULL) AND
    ("cost" = ANY($6) OR $6 IS NULL) AND
    ("cost" > $7 OR $7 IS NULL) AND
    ("cost" < $8 OR $8 IS NULL) AND
    ("new_cost" = ANY($9) OR $9 IS NULL) AND
    ("new_cost" > $10 OR $10 IS NULL) AND
    ("new_cost" < $11 OR $11 IS NULL) AND
    ("date_eta" = ANY($12) OR $12 IS NULL) AND
    ("date_eta" > $13 OR $13 IS NULL) AND
    ("date_eta" < $14 OR $14 IS NULL) AND
    ("from_address" = ANY($15) OR $15 IS NULL) AND
    ("to_address" = ANY($16) OR $16 IS NULL) AND
    ("weight_grams" = ANY($17) OR $17 IS NULL) AND
    ("weight_grams" > $18 OR $18 IS NULL) AND
    ("weight_grams" < $19 OR $19 IS NULL) AND
    ("length_cm" = ANY($20) OR $20 IS NULL) AND
    ("length_cm" > $21 OR $21 IS NULL) AND
    ("length_cm" < $22 OR $22 IS NULL) AND
    ("width_cm" = ANY($23) OR $23 IS NULL) AND
    ("height_cm" = ANY($24) OR $24 IS NULL) AND
    ("height_cm" > $25 OR $25 IS NULL) AND
    ("height_cm" < $26 OR $26 IS NULL) AND
    ("date_created" = ANY($27) OR $27 IS NULL) AND
    ("date_created" > $28 OR $28 IS NULL) AND
    ("date_created" < $29 OR $29 IS NULL)
)
`

type CountShipmentParams struct {
	ID              []uuid.UUID           `json:"id"`
	Option          []string              `json:"option"`
	TrackingCode    []null.String         `json:"tracking_code"`
	Status          []OrderShipmentStatus `json:"status"`
	LabelUrl        []null.String         `json:"label_url"`
	Cost            []int64               `json:"cost"`
	CostFrom        null.Int              `json:"cost_from"`
	CostTo          null.Int              `json:"cost_to"`
	NewCost         []int64               `json:"new_cost"`
	NewCostFrom     null.Int              `json:"new_cost_from"`
	NewCostTo       null.Int              `json:"new_cost_to"`
	DateEta         []time.Time           `json:"date_eta"`
	DateEtaFrom     null.Time             `json:"date_eta_from"`
	DateEtaTo       null.Time             `json:"date_eta_to"`
	FromAddress     []string              `json:"from_address"`
	ToAddress       []string              `json:"to_address"`
	WeightGrams     []int32               `json:"weight_grams"`
	WeightGramsFrom null.Int32            `json:"weight_grams_from"`
	WeightGramsTo   null.Int32            `json:"weight_grams_to"`
	LengthCm        []int32               `json:"length_cm"`
	LengthCmFrom    null.Int32            `json:"length_cm_from"`
	LengthCmTo      null.Int32            `json:"length_cm_to"`
	WidthCm         []int32               `json:"width_cm"`
	HeightCm        []int32               `json:"height_cm"`
	HeightCmFrom    null.Int32            `json:"height_cm_from"`
	HeightCmTo      null.Int32            `json:"height_cm_to"`
	DateCreated     []time.Time           `json:"date_created"`
	DateCreatedFrom null.Time             `json:"date_created_from"`
	DateCreatedTo   null.Time             `json:"date_created_to"`
}

func (q *Queries) CountShipment(ctx context.Context, arg CountShipmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShipment,
		arg.ID,
		arg.Option,
		arg.TrackingCode,
		arg.Status,
		arg.LabelUrl,
		arg.Cost,
		arg.CostFrom,
		arg.CostTo,
		arg.NewCost,
		arg.NewCostFrom,
		arg.NewCostTo,
		arg.DateEta,
		arg.DateEtaFrom,
		arg.DateEtaTo,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.WeightGramsFrom,
		arg.WeightGramsTo,
		arg.LengthCm,
		arg.LengthCmFrom,
		arg.LengthCmTo,
		arg.WidthCm,
		arg.HeightCm,
		arg.HeightCmFrom,
		arg.HeightCmTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateCopyDefaultShipmentParams struct {
	Option       string      `json:"option"`
	TrackingCode null.String `json:"tracking_code"`
	LabelUrl     null.String `json:"label_url"`
	Cost         int64       `json:"cost"`
	NewCost      int64       `json:"new_cost"`
	DateEta      time.Time   `json:"date_eta"`
	FromAddress  string      `json:"from_address"`
	ToAddress    string      `json:"to_address"`
	WeightGrams  int32       `json:"weight_grams"`
	LengthCm     int32       `json:"length_cm"`
	WidthCm      int32       `json:"width_cm"`
	HeightCm     int32       `json:"height_cm"`
}

type CreateCopyShipmentParams struct {
	ID           uuid.UUID           `json:"id"`
	Option       string              `json:"option"`
	TrackingCode null.String         `json:"tracking_code"`
	Status       OrderShipmentStatus `json:"status"`
	LabelUrl     null.String         `json:"label_url"`
	Cost         int64               `json:"cost"`
	NewCost      int64               `json:"new_cost"`
	DateEta      time.Time           `json:"date_eta"`
	FromAddress  string              `json:"from_address"`
	ToAddress    string              `json:"to_address"`
	WeightGrams  int32               `json:"weight_grams"`
	LengthCm     int32               `json:"length_cm"`
	WidthCm      int32               `json:"width_cm"`
	HeightCm     int32               `json:"height_cm"`
	DateCreated  time.Time           `json:"date_created"`
}

const createDefaultShipment = `-- name: CreateDefaultShipment :one
INSERT INTO "order"."shipment" ("option", "tracking_code", "label_url", "cost", "new_cost", "date_eta", "from_address", "to_address", "weight_grams", "length_cm", "width_cm", "height_cm")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, option, tracking_code, status, label_url, cost, new_cost, date_eta, from_address, to_address, weight_grams, length_cm, width_cm, height_cm, date_created
`

type CreateDefaultShipmentParams struct {
	Option       string      `json:"option"`
	TrackingCode null.String `json:"tracking_code"`
	LabelUrl     null.String `json:"label_url"`
	Cost         int64       `json:"cost"`
	NewCost      int64       `json:"new_cost"`
	DateEta      time.Time   `json:"date_eta"`
	FromAddress  string      `json:"from_address"`
	ToAddress    string      `json:"to_address"`
	WeightGrams  int32       `json:"weight_grams"`
	LengthCm     int32       `json:"length_cm"`
	WidthCm      int32       `json:"width_cm"`
	HeightCm     int32       `json:"height_cm"`
}

func (q *Queries) CreateDefaultShipment(ctx context.Context, arg CreateDefaultShipmentParams) (OrderShipment, error) {
	row := q.db.QueryRow(ctx, createDefaultShipment,
		arg.Option,
		arg.TrackingCode,
		arg.LabelUrl,
		arg.Cost,
		arg.NewCost,
		arg.DateEta,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
	)
	var i OrderShipment
	err := row.Scan(
		&i.ID,
		&i.Option,
		&i.TrackingCode,
		&i.Status,
		&i.LabelUrl,
		&i.Cost,
		&i.NewCost,
		&i.DateEta,
		&i.FromAddress,
		&i.ToAddress,
		&i.WeightGrams,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.DateCreated,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO "order"."shipment" ("id", "option", "tracking_code", "status", "label_url", "cost", "new_cost", "date_eta", "from_address", "to_address", "weight_grams", "length_cm", "width_cm", "height_cm", "date_created")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, option, tracking_code, status, label_url, cost, new_cost, date_eta, from_address, to_address, weight_grams, length_cm, width_cm, height_cm, date_created
`

type CreateShipmentParams struct {
	ID           uuid.UUID           `json:"id"`
	Option       string              `json:"option"`
	TrackingCode null.String         `json:"tracking_code"`
	Status       OrderShipmentStatus `json:"status"`
	LabelUrl     null.String         `json:"label_url"`
	Cost         int64               `json:"cost"`
	NewCost      int64               `json:"new_cost"`
	DateEta      time.Time           `json:"date_eta"`
	FromAddress  string              `json:"from_address"`
	ToAddress    string              `json:"to_address"`
	WeightGrams  int32               `json:"weight_grams"`
	LengthCm     int32               `json:"length_cm"`
	WidthCm      int32               `json:"width_cm"`
	HeightCm     int32               `json:"height_cm"`
	DateCreated  time.Time           `json:"date_created"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (OrderShipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.ID,
		arg.Option,
		arg.TrackingCode,
		arg.Status,
		arg.LabelUrl,
		arg.Cost,
		arg.NewCost,
		arg.DateEta,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
		arg.DateCreated,
	)
	var i OrderShipment
	err := row.Scan(
		&i.ID,
		&i.Option,
		&i.TrackingCode,
		&i.Status,
		&i.LabelUrl,
		&i.Cost,
		&i.NewCost,
		&i.DateEta,
		&i.FromAddress,
		&i.ToAddress,
		&i.WeightGrams,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.DateCreated,
	)
	return i, err
}

const deleteShipment = `-- name: DeleteShipment :exec
DELETE FROM "order"."shipment"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("option" = ANY($2) OR $2 IS NULL) AND
    ("tracking_code" = ANY($3) OR $3 IS NULL) AND
    ("status" = ANY($4) OR $4 IS NULL) AND
    ("label_url" = ANY($5) OR $5 IS NULL) AND
    ("cost" = ANY($6) OR $6 IS NULL) AND
    ("cost" > $7 OR $7 IS NULL) AND
    ("cost" < $8 OR $8 IS NULL) AND
    ("new_cost" = ANY($9) OR $9 IS NULL) AND
    ("new_cost" > $10 OR $10 IS NULL) AND
    ("new_cost" < $11 OR $11 IS NULL) AND
    ("date_eta" = ANY($12) OR $12 IS NULL) AND
    ("date_eta" > $13 OR $13 IS NULL) AND
    ("date_eta" < $14 OR $14 IS NULL) AND
    ("from_address" = ANY($15) OR $15 IS NULL) AND
    ("to_address" = ANY($16) OR $16 IS NULL) AND
    ("weight_grams" = ANY($17) OR $17 IS NULL) AND
    ("weight_grams" > $18 OR $18 IS NULL) AND
    ("weight_grams" < $19 OR $19 IS NULL) AND
    ("length_cm" = ANY($20) OR $20 IS NULL) AND
    ("length_cm" > $21 OR $21 IS NULL) AND
    ("length_cm" < $22 OR $22 IS NULL) AND
    ("width_cm" = ANY($23) OR $23 IS NULL) AND
    ("height_cm" = ANY($24) OR $24 IS NULL) AND
    ("height_cm" > $25 OR $25 IS NULL) AND
    ("height_cm" < $26 OR $26 IS NULL) AND
    ("date_created" = ANY($27) OR $27 IS NULL) AND
    ("date_created" > $28 OR $28 IS NULL) AND
    ("date_created" < $29 OR $29 IS NULL)
)
`

type DeleteShipmentParams struct {
	ID              []uuid.UUID           `json:"id"`
	Option          []string              `json:"option"`
	TrackingCode    []null.String         `json:"tracking_code"`
	Status          []OrderShipmentStatus `json:"status"`
	LabelUrl        []null.String         `json:"label_url"`
	Cost            []int64               `json:"cost"`
	CostFrom        null.Int              `json:"cost_from"`
	CostTo          null.Int              `json:"cost_to"`
	NewCost         []int64               `json:"new_cost"`
	NewCostFrom     null.Int              `json:"new_cost_from"`
	NewCostTo       null.Int              `json:"new_cost_to"`
	DateEta         []time.Time           `json:"date_eta"`
	DateEtaFrom     null.Time             `json:"date_eta_from"`
	DateEtaTo       null.Time             `json:"date_eta_to"`
	FromAddress     []string              `json:"from_address"`
	ToAddress       []string              `json:"to_address"`
	WeightGrams     []int32               `json:"weight_grams"`
	WeightGramsFrom null.Int32            `json:"weight_grams_from"`
	WeightGramsTo   null.Int32            `json:"weight_grams_to"`
	LengthCm        []int32               `json:"length_cm"`
	LengthCmFrom    null.Int32            `json:"length_cm_from"`
	LengthCmTo      null.Int32            `json:"length_cm_to"`
	WidthCm         []int32               `json:"width_cm"`
	HeightCm        []int32               `json:"height_cm"`
	HeightCmFrom    null.Int32            `json:"height_cm_from"`
	HeightCmTo      null.Int32            `json:"height_cm_to"`
	DateCreated     []time.Time           `json:"date_created"`
	DateCreatedFrom null.Time             `json:"date_created_from"`
	DateCreatedTo   null.Time             `json:"date_created_to"`
}

func (q *Queries) DeleteShipment(ctx context.Context, arg DeleteShipmentParams) error {
	_, err := q.db.Exec(ctx, deleteShipment,
		arg.ID,
		arg.Option,
		arg.TrackingCode,
		arg.Status,
		arg.LabelUrl,
		arg.Cost,
		arg.CostFrom,
		arg.CostTo,
		arg.NewCost,
		arg.NewCostFrom,
		arg.NewCostTo,
		arg.DateEta,
		arg.DateEtaFrom,
		arg.DateEtaTo,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.WeightGramsFrom,
		arg.WeightGramsTo,
		arg.LengthCm,
		arg.LengthCmFrom,
		arg.LengthCmTo,
		arg.WidthCm,
		arg.HeightCm,
		arg.HeightCmFrom,
		arg.HeightCmTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
	)
	return err
}

const getShipment = `-- name: GetShipment :one
SELECT id, option, tracking_code, status, label_url, cost, new_cost, date_eta, from_address, to_address, weight_grams, length_cm, width_cm, height_cm, date_created
FROM "order"."shipment"
WHERE ("id" = $1)
`

func (q *Queries) GetShipment(ctx context.Context, id uuid.NullUUID) (OrderShipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i OrderShipment
	err := row.Scan(
		&i.ID,
		&i.Option,
		&i.TrackingCode,
		&i.Status,
		&i.LabelUrl,
		&i.Cost,
		&i.NewCost,
		&i.DateEta,
		&i.FromAddress,
		&i.ToAddress,
		&i.WeightGrams,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.DateCreated,
	)
	return i, err
}

const listCountShipment = `-- name: ListCountShipment :many
SELECT embed_shipment.id, embed_shipment.option, embed_shipment.tracking_code, embed_shipment.status, embed_shipment.label_url, embed_shipment.cost, embed_shipment.new_cost, embed_shipment.date_eta, embed_shipment.from_address, embed_shipment.to_address, embed_shipment.weight_grams, embed_shipment.length_cm, embed_shipment.width_cm, embed_shipment.height_cm, embed_shipment.date_created, COUNT(*) OVER() as total_count
FROM "order"."shipment" embed_shipment
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("option" = ANY($2) OR $2 IS NULL) AND
    ("tracking_code" = ANY($3) OR $3 IS NULL) AND
    ("status" = ANY($4) OR $4 IS NULL) AND
    ("label_url" = ANY($5) OR $5 IS NULL) AND
    ("cost" = ANY($6) OR $6 IS NULL) AND
    ("cost" > $7 OR $7 IS NULL) AND
    ("cost" < $8 OR $8 IS NULL) AND
    ("new_cost" = ANY($9) OR $9 IS NULL) AND
    ("new_cost" > $10 OR $10 IS NULL) AND
    ("new_cost" < $11 OR $11 IS NULL) AND
    ("date_eta" = ANY($12) OR $12 IS NULL) AND
    ("date_eta" > $13 OR $13 IS NULL) AND
    ("date_eta" < $14 OR $14 IS NULL) AND
    ("from_address" = ANY($15) OR $15 IS NULL) AND
    ("to_address" = ANY($16) OR $16 IS NULL) AND
    ("weight_grams" = ANY($17) OR $17 IS NULL) AND
    ("weight_grams" > $18 OR $18 IS NULL) AND
    ("weight_grams" < $19 OR $19 IS NULL) AND
    ("length_cm" = ANY($20) OR $20 IS NULL) AND
    ("length_cm" > $21 OR $21 IS NULL) AND
    ("length_cm" < $22 OR $22 IS NULL) AND
    ("width_cm" = ANY($23) OR $23 IS NULL) AND
    ("height_cm" = ANY($24) OR $24 IS NULL) AND
    ("height_cm" > $25 OR $25 IS NULL) AND
    ("height_cm" < $26 OR $26 IS NULL) AND
    ("date_created" = ANY($27) OR $27 IS NULL) AND
    ("date_created" > $28 OR $28 IS NULL) AND
    ("date_created" < $29 OR $29 IS NULL)
)
ORDER BY "id"
LIMIT $31::int
OFFSET $30::int
`

type ListCountShipmentParams struct {
	ID              []uuid.UUID           `json:"id"`
	Option          []string              `json:"option"`
	TrackingCode    []null.String         `json:"tracking_code"`
	Status          []OrderShipmentStatus `json:"status"`
	LabelUrl        []null.String         `json:"label_url"`
	Cost            []int64               `json:"cost"`
	CostFrom        null.Int              `json:"cost_from"`
	CostTo          null.Int              `json:"cost_to"`
	NewCost         []int64               `json:"new_cost"`
	NewCostFrom     null.Int              `json:"new_cost_from"`
	NewCostTo       null.Int              `json:"new_cost_to"`
	DateEta         []time.Time           `json:"date_eta"`
	DateEtaFrom     null.Time             `json:"date_eta_from"`
	DateEtaTo       null.Time             `json:"date_eta_to"`
	FromAddress     []string              `json:"from_address"`
	ToAddress       []string              `json:"to_address"`
	WeightGrams     []int32               `json:"weight_grams"`
	WeightGramsFrom null.Int32            `json:"weight_grams_from"`
	WeightGramsTo   null.Int32            `json:"weight_grams_to"`
	LengthCm        []int32               `json:"length_cm"`
	LengthCmFrom    null.Int32            `json:"length_cm_from"`
	LengthCmTo      null.Int32            `json:"length_cm_to"`
	WidthCm         []int32               `json:"width_cm"`
	HeightCm        []int32               `json:"height_cm"`
	HeightCmFrom    null.Int32            `json:"height_cm_from"`
	HeightCmTo      null.Int32            `json:"height_cm_to"`
	DateCreated     []time.Time           `json:"date_created"`
	DateCreatedFrom null.Time             `json:"date_created_from"`
	DateCreatedTo   null.Time             `json:"date_created_to"`
	Offset          null.Int32            `json:"offset"`
	Limit           null.Int32            `json:"limit"`
}

type ListCountShipmentRow struct {
	OrderShipment OrderShipment `json:"order_shipment"`
	TotalCount    int64         `json:"total_count"`
}

func (q *Queries) ListCountShipment(ctx context.Context, arg ListCountShipmentParams) ([]ListCountShipmentRow, error) {
	rows, err := q.db.Query(ctx, listCountShipment,
		arg.ID,
		arg.Option,
		arg.TrackingCode,
		arg.Status,
		arg.LabelUrl,
		arg.Cost,
		arg.CostFrom,
		arg.CostTo,
		arg.NewCost,
		arg.NewCostFrom,
		arg.NewCostTo,
		arg.DateEta,
		arg.DateEtaFrom,
		arg.DateEtaTo,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.WeightGramsFrom,
		arg.WeightGramsTo,
		arg.LengthCm,
		arg.LengthCmFrom,
		arg.LengthCmTo,
		arg.WidthCm,
		arg.HeightCm,
		arg.HeightCmFrom,
		arg.HeightCmTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountShipmentRow{}
	for rows.Next() {
		var i ListCountShipmentRow
		if err := rows.Scan(
			&i.OrderShipment.ID,
			&i.OrderShipment.Option,
			&i.OrderShipment.TrackingCode,
			&i.OrderShipment.Status,
			&i.OrderShipment.LabelUrl,
			&i.OrderShipment.Cost,
			&i.OrderShipment.NewCost,
			&i.OrderShipment.DateEta,
			&i.OrderShipment.FromAddress,
			&i.OrderShipment.ToAddress,
			&i.OrderShipment.WeightGrams,
			&i.OrderShipment.LengthCm,
			&i.OrderShipment.WidthCm,
			&i.OrderShipment.HeightCm,
			&i.OrderShipment.DateCreated,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipment = `-- name: ListShipment :many
SELECT id, option, tracking_code, status, label_url, cost, new_cost, date_eta, from_address, to_address, weight_grams, length_cm, width_cm, height_cm, date_created
FROM "order"."shipment"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("option" = ANY($2) OR $2 IS NULL) AND
    ("tracking_code" = ANY($3) OR $3 IS NULL) AND
    ("status" = ANY($4) OR $4 IS NULL) AND
    ("label_url" = ANY($5) OR $5 IS NULL) AND
    ("cost" = ANY($6) OR $6 IS NULL) AND
    ("cost" > $7 OR $7 IS NULL) AND
    ("cost" < $8 OR $8 IS NULL) AND
    ("new_cost" = ANY($9) OR $9 IS NULL) AND
    ("new_cost" > $10 OR $10 IS NULL) AND
    ("new_cost" < $11 OR $11 IS NULL) AND
    ("date_eta" = ANY($12) OR $12 IS NULL) AND
    ("date_eta" > $13 OR $13 IS NULL) AND
    ("date_eta" < $14 OR $14 IS NULL) AND
    ("from_address" = ANY($15) OR $15 IS NULL) AND
    ("to_address" = ANY($16) OR $16 IS NULL) AND
    ("weight_grams" = ANY($17) OR $17 IS NULL) AND
    ("weight_grams" > $18 OR $18 IS NULL) AND
    ("weight_grams" < $19 OR $19 IS NULL) AND
    ("length_cm" = ANY($20) OR $20 IS NULL) AND
    ("length_cm" > $21 OR $21 IS NULL) AND
    ("length_cm" < $22 OR $22 IS NULL) AND
    ("width_cm" = ANY($23) OR $23 IS NULL) AND
    ("height_cm" = ANY($24) OR $24 IS NULL) AND
    ("height_cm" > $25 OR $25 IS NULL) AND
    ("height_cm" < $26 OR $26 IS NULL) AND
    ("date_created" = ANY($27) OR $27 IS NULL) AND
    ("date_created" > $28 OR $28 IS NULL) AND
    ("date_created" < $29 OR $29 IS NULL)
)
ORDER BY "id"
LIMIT $31::int
OFFSET $30::int
`

type ListShipmentParams struct {
	ID              []uuid.UUID           `json:"id"`
	Option          []string              `json:"option"`
	TrackingCode    []null.String         `json:"tracking_code"`
	Status          []OrderShipmentStatus `json:"status"`
	LabelUrl        []null.String         `json:"label_url"`
	Cost            []int64               `json:"cost"`
	CostFrom        null.Int              `json:"cost_from"`
	CostTo          null.Int              `json:"cost_to"`
	NewCost         []int64               `json:"new_cost"`
	NewCostFrom     null.Int              `json:"new_cost_from"`
	NewCostTo       null.Int              `json:"new_cost_to"`
	DateEta         []time.Time           `json:"date_eta"`
	DateEtaFrom     null.Time             `json:"date_eta_from"`
	DateEtaTo       null.Time             `json:"date_eta_to"`
	FromAddress     []string              `json:"from_address"`
	ToAddress       []string              `json:"to_address"`
	WeightGrams     []int32               `json:"weight_grams"`
	WeightGramsFrom null.Int32            `json:"weight_grams_from"`
	WeightGramsTo   null.Int32            `json:"weight_grams_to"`
	LengthCm        []int32               `json:"length_cm"`
	LengthCmFrom    null.Int32            `json:"length_cm_from"`
	LengthCmTo      null.Int32            `json:"length_cm_to"`
	WidthCm         []int32               `json:"width_cm"`
	HeightCm        []int32               `json:"height_cm"`
	HeightCmFrom    null.Int32            `json:"height_cm_from"`
	HeightCmTo      null.Int32            `json:"height_cm_to"`
	DateCreated     []time.Time           `json:"date_created"`
	DateCreatedFrom null.Time             `json:"date_created_from"`
	DateCreatedTo   null.Time             `json:"date_created_to"`
	Offset          null.Int32            `json:"offset"`
	Limit           null.Int32            `json:"limit"`
}

func (q *Queries) ListShipment(ctx context.Context, arg ListShipmentParams) ([]OrderShipment, error) {
	rows, err := q.db.Query(ctx, listShipment,
		arg.ID,
		arg.Option,
		arg.TrackingCode,
		arg.Status,
		arg.LabelUrl,
		arg.Cost,
		arg.CostFrom,
		arg.CostTo,
		arg.NewCost,
		arg.NewCostFrom,
		arg.NewCostTo,
		arg.DateEta,
		arg.DateEtaFrom,
		arg.DateEtaTo,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.WeightGramsFrom,
		arg.WeightGramsTo,
		arg.LengthCm,
		arg.LengthCmFrom,
		arg.LengthCmTo,
		arg.WidthCm,
		arg.HeightCm,
		arg.HeightCmFrom,
		arg.HeightCmTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderShipment{}
	for rows.Next() {
		var i OrderShipment
		if err := rows.Scan(
			&i.ID,
			&i.Option,
			&i.TrackingCode,
			&i.Status,
			&i.LabelUrl,
			&i.Cost,
			&i.NewCost,
			&i.DateEta,
			&i.FromAddress,
			&i.ToAddress,
			&i.WeightGrams,
			&i.LengthCm,
			&i.WidthCm,
			&i.HeightCm,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipment = `-- name: UpdateShipment :one
UPDATE "order"."shipment"
SET "option" = COALESCE($1, "option"),
    "tracking_code" = CASE WHEN $2::bool = TRUE THEN NULL ELSE COALESCE($3, "tracking_code") END,
    "status" = COALESCE($4, "status"),
    "label_url" = CASE WHEN $5::bool = TRUE THEN NULL ELSE COALESCE($6, "label_url") END,
    "cost" = COALESCE($7, "cost"),
    "new_cost" = COALESCE($8, "new_cost"),
    "date_eta" = COALESCE($9, "date_eta"),
    "from_address" = COALESCE($10, "from_address"),
    "to_address" = COALESCE($11, "to_address"),
    "weight_grams" = COALESCE($12, "weight_grams"),
    "length_cm" = COALESCE($13, "length_cm"),
    "width_cm" = COALESCE($14, "width_cm"),
    "height_cm" = COALESCE($15, "height_cm"),
    "date_created" = COALESCE($16, "date_created")
WHERE id = $17
RETURNING id, option, tracking_code, status, label_url, cost, new_cost, date_eta, from_address, to_address, weight_grams, length_cm, width_cm, height_cm, date_created
`

type UpdateShipmentParams struct {
	Option           null.String             `json:"option"`
	NullTrackingCode bool                    `json:"null_tracking_code"`
	TrackingCode     null.String             `json:"tracking_code"`
	Status           NullOrderShipmentStatus `json:"status"`
	NullLabelUrl     bool                    `json:"null_label_url"`
	LabelUrl         null.String             `json:"label_url"`
	Cost             null.Int                `json:"cost"`
	NewCost          null.Int                `json:"new_cost"`
	DateEta          null.Time               `json:"date_eta"`
	FromAddress      null.String             `json:"from_address"`
	ToAddress        null.String             `json:"to_address"`
	WeightGrams      null.Int32              `json:"weight_grams"`
	LengthCm         null.Int32              `json:"length_cm"`
	WidthCm          null.Int32              `json:"width_cm"`
	HeightCm         null.Int32              `json:"height_cm"`
	DateCreated      null.Time               `json:"date_created"`
	ID               uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) (OrderShipment, error) {
	row := q.db.QueryRow(ctx, updateShipment,
		arg.Option,
		arg.NullTrackingCode,
		arg.TrackingCode,
		arg.Status,
		arg.NullLabelUrl,
		arg.LabelUrl,
		arg.Cost,
		arg.NewCost,
		arg.DateEta,
		arg.FromAddress,
		arg.ToAddress,
		arg.WeightGrams,
		arg.LengthCm,
		arg.WidthCm,
		arg.HeightCm,
		arg.DateCreated,
		arg.ID,
	)
	var i OrderShipment
	err := row.Scan(
		&i.ID,
		&i.Option,
		&i.TrackingCode,
		&i.Status,
		&i.LabelUrl,
		&i.Cost,
		&i.NewCost,
		&i.DateEta,
		&i.FromAddress,
		&i.ToAddress,
		&i.WeightGrams,
		&i.LengthCm,
		&i.WidthCm,
		&i.HeightCm,
		&i.DateCreated,
	)
	return i, err
}
