// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package orderdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const listTransactionsByIDs = `-- name: ListTransactionsByIDs :many
SELECT id, session_id, status, note, error, payment_option, wallet_id, data, amount, from_currency, to_currency, exchange_rate, reverses_id, date_created, date_settled, date_expired FROM "order"."transaction" WHERE "id" = ANY($1::BIGINT[])
`

func (q *Queries) ListTransactionsByIDs(ctx context.Context, ids []int64) ([]OrderTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTransaction{}
	for rows.Next() {
		var i OrderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.Error,
			&i.PaymentOption,
			&i.WalletID,
			&i.Data,
			&i.Amount,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.ReversesID,
			&i.DateCreated,
			&i.DateSettled,
			&i.DateExpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByItem = `-- name: ListTransactionsByItem :many
SELECT t.id, t.session_id, t.status, t.note, t.error, t.payment_option, t.wallet_id, t.data, t.amount, t.from_currency, t.to_currency, t.exchange_rate, t.reverses_id, t.date_created, t.date_settled, t.date_expired FROM "order"."transaction" t
WHERE t."session_id" = (SELECT i."payment_session_id" FROM "order"."item" i WHERE i."id" = $1)
ORDER BY t."date_created"
`

func (q *Queries) ListTransactionsByItem(ctx context.Context, itemID int64) ([]OrderTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTransaction{}
	for rows.Next() {
		var i OrderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.Error,
			&i.PaymentOption,
			&i.WalletID,
			&i.Data,
			&i.Amount,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.ReversesID,
			&i.DateCreated,
			&i.DateSettled,
			&i.DateExpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByOrder = `-- name: ListTransactionsByOrder :many
SELECT t.id, t.session_id, t.status, t.note, t.error, t.payment_option, t.wallet_id, t.data, t.amount, t.from_currency, t.to_currency, t.exchange_rate, t.reverses_id, t.date_created, t.date_settled, t.date_expired FROM "order"."transaction" t
WHERE t."session_id" IN (
    SELECT o."confirm_session_id" FROM "order"."order" o WHERE o."id" = $1
    UNION
    SELECT i."payment_session_id" FROM "order"."item" i WHERE i."order_id" = $1
)
ORDER BY t."date_created"
`

func (q *Queries) ListTransactionsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTransaction{}
	for rows.Next() {
		var i OrderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.Error,
			&i.PaymentOption,
			&i.WalletID,
			&i.Data,
			&i.Amount,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.ReversesID,
			&i.DateCreated,
			&i.DateSettled,
			&i.DateExpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySession = `-- name: ListTransactionsBySession :many
SELECT id, session_id, status, note, error, payment_option, wallet_id, data, amount, from_currency, to_currency, exchange_rate, reverses_id, date_created, date_settled, date_expired FROM "order"."transaction"
WHERE "session_id" = $1
ORDER BY "date_created"
`

func (q *Queries) ListTransactionsBySession(ctx context.Context, sessionID int64) ([]OrderTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTransaction{}
	for rows.Next() {
		var i OrderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.Error,
			&i.PaymentOption,
			&i.WalletID,
			&i.Data,
			&i.Amount,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.ReversesID,
			&i.DateCreated,
			&i.DateSettled,
			&i.DateExpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionCancelled = `-- name: MarkTransactionCancelled :one
UPDATE "order"."transaction"
SET "status" = 'Cancelled'
WHERE "id" = $1 AND "status" = 'Pending'
RETURNING id, session_id, status, note, error, payment_option, wallet_id, data, amount, from_currency, to_currency, exchange_rate, reverses_id, date_created, date_settled, date_expired
`

func (q *Queries) MarkTransactionCancelled(ctx context.Context, id int64) (OrderTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionCancelled, id)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.Error,
		&i.PaymentOption,
		&i.WalletID,
		&i.Data,
		&i.Amount,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.ExchangeRate,
		&i.ReversesID,
		&i.DateCreated,
		&i.DateSettled,
		&i.DateExpired,
	)
	return i, err
}

const markTransactionFailed = `-- name: MarkTransactionFailed :one
UPDATE "order"."transaction"
SET "status" = 'Failed',
    "error" = $1
WHERE "id" = $2 AND "status" = 'Pending'
RETURNING id, session_id, status, note, error, payment_option, wallet_id, data, amount, from_currency, to_currency, exchange_rate, reverses_id, date_created, date_settled, date_expired
`

type MarkTransactionFailedParams struct {
	Error null.String `json:"error"`
	ID    int64       `json:"id"`
}

func (q *Queries) MarkTransactionFailed(ctx context.Context, arg MarkTransactionFailedParams) (OrderTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionFailed, arg.Error, arg.ID)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.Error,
		&i.PaymentOption,
		&i.WalletID,
		&i.Data,
		&i.Amount,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.ExchangeRate,
		&i.ReversesID,
		&i.DateCreated,
		&i.DateSettled,
		&i.DateExpired,
	)
	return i, err
}

const markTransactionSuccess = `-- name: MarkTransactionSuccess :one
UPDATE "order"."transaction"
SET "status" = 'Success',
    "date_settled" = COALESCE($1::TIMESTAMPTZ, CURRENT_TIMESTAMP)
WHERE "id" = $2 AND "status" = 'Pending'
RETURNING id, session_id, status, note, error, payment_option, wallet_id, data, amount, from_currency, to_currency, exchange_rate, reverses_id, date_created, date_settled, date_expired
`

type MarkTransactionSuccessParams struct {
	DateSettled time.Time `json:"date_settled"`
	ID          int64     `json:"id"`
}

func (q *Queries) MarkTransactionSuccess(ctx context.Context, arg MarkTransactionSuccessParams) (OrderTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionSuccess, arg.DateSettled, arg.ID)
	var i OrderTransaction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.Error,
		&i.PaymentOption,
		&i.WalletID,
		&i.Data,
		&i.Amount,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.ExchangeRate,
		&i.ReversesID,
		&i.DateCreated,
		&i.DateSettled,
		&i.DateExpired,
	)
	return i, err
}

const setTransactionData = `-- name: SetTransactionData :exec


UPDATE "order"."transaction" SET "data" = $1 WHERE "id" = $2
`

type SetTransactionDataParams struct {
	Data json.RawMessage `json:"data"`
	ID   int64           `json:"id"`
}

// =============================================
// Module:      order
// File:        transaction.sql
// Purpose:     Append-only ledger leg per payment_session rail movement. Status
//
//	transitions Pending -> Success/Failed; Success is terminal.
//	Reversals are NEW rows (negative amount + reverses_id) within the
//	SAME session as the original — convention, not DB-enforced.
//
// =============================================
// Create/Get are auto-generated by pgtempl (CreateDefaultTransaction / GetTransaction).
func (q *Queries) SetTransactionData(ctx context.Context, arg SetTransactionDataParams) error {
	_, err := q.db.Exec(ctx, setTransactionData, arg.Data, arg.ID)
	return err
}
