// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateCopyAccountAddress implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountAddress struct {
	rows                 []CreateCopyAccountAddressParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountAddress) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountAddress) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].Type,
		r.rows[0].FullName,
		r.rows[0].Phone,
		r.rows[0].PhoneVerified,
		r.rows[0].AddressLine,
		r.rows[0].City,
		r.rows[0].StateProvince,
		r.rows[0].Country,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyAccountAddress) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountAddress(ctx context.Context, arg []CreateCopyAccountAddressParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "address"}, []string{"account_id", "type", "full_name", "phone", "phone_verified", "address_line", "city", "state_province", "country", "date_created", "date_updated"}, &iteratorForCreateCopyAccountAddress{rows: arg})
}

// iteratorForCreateCopyAccountBase implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountBase struct {
	rows                 []CreateCopyAccountBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Type,
		r.rows[0].Status,
		r.rows[0].Phone,
		r.rows[0].Email,
		r.rows[0].Username,
		r.rows[0].Password,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyAccountBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountBase(ctx context.Context, arg []CreateCopyAccountBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "base"}, []string{"type", "status", "phone", "email", "username", "password", "date_created", "date_updated"}, &iteratorForCreateCopyAccountBase{rows: arg})
}

// iteratorForCreateCopyAccountCartItem implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountCartItem struct {
	rows                 []CreateCopyAccountCartItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountCartItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountCartItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CartID,
		r.rows[0].SkuID,
		r.rows[0].Quantity,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyAccountCartItem) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountCartItem(ctx context.Context, arg []CreateCopyAccountCartItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "cart_item"}, []string{"cart_id", "sku_id", "quantity", "date_created", "date_updated"}, &iteratorForCreateCopyAccountCartItem{rows: arg})
}

// iteratorForCreateCopyAccountCustomer implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountCustomer struct {
	rows                 []CreateCopyAccountCustomerParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountCustomer) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountCustomer) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].DefaultAddressID,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyAccountCustomer) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountCustomer(ctx context.Context, arg []CreateCopyAccountCustomerParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "customer"}, []string{"id", "default_address_id", "date_created", "date_updated"}, &iteratorForCreateCopyAccountCustomer{rows: arg})
}

// iteratorForCreateCopyAccountIncomeHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountIncomeHistory struct {
	rows                 []CreateCopyAccountIncomeHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountIncomeHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountIncomeHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].Type,
		r.rows[0].Income,
		r.rows[0].CurrentBalance,
		r.rows[0].Note,
		r.rows[0].DateCreated,
		r.rows[0].Hash,
		r.rows[0].PrevHash,
	}, nil
}

func (r iteratorForCreateCopyAccountIncomeHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountIncomeHistory(ctx context.Context, arg []CreateCopyAccountIncomeHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "income_history"}, []string{"account_id", "type", "income", "current_balance", "note", "date_created", "hash", "prev_hash"}, &iteratorForCreateCopyAccountIncomeHistory{rows: arg})
}

// iteratorForCreateCopyAccountNotification implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountNotification struct {
	rows                 []CreateCopyAccountNotificationParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountNotification) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountNotification) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].Type,
		r.rows[0].Channel,
		r.rows[0].IsRead,
		r.rows[0].Content,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
		r.rows[0].DateSent,
		r.rows[0].DateScheduled,
	}, nil
}

func (r iteratorForCreateCopyAccountNotification) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountNotification(ctx context.Context, arg []CreateCopyAccountNotificationParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "notification"}, []string{"account_id", "type", "channel", "is_read", "content", "date_created", "date_updated", "date_sent", "date_scheduled"}, &iteratorForCreateCopyAccountNotification{rows: arg})
}

// iteratorForCreateCopyAccountProfile implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountProfile struct {
	rows                 []CreateCopyAccountProfileParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountProfile) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountProfile) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Gender,
		r.rows[0].Name,
		r.rows[0].DateOfBirth,
		r.rows[0].AvatarRsID,
		r.rows[0].EmailVerified,
		r.rows[0].PhoneVerified,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyAccountProfile) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountProfile(ctx context.Context, arg []CreateCopyAccountProfileParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "profile"}, []string{"id", "gender", "name", "date_of_birth", "avatar_rs_id", "email_verified", "phone_verified", "date_created", "date_updated"}, &iteratorForCreateCopyAccountProfile{rows: arg})
}

// iteratorForCreateCopyAccountVendor implements pgx.CopyFromSource.
type iteratorForCreateCopyAccountVendor struct {
	rows                 []CreateCopyAccountVendorParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyAccountVendor) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyAccountVendor) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreateCopyAccountVendor) Err() error {
	return nil
}

func (q *Queries) CreateCopyAccountVendor(ctx context.Context, arg []CreateCopyAccountVendorParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "vendor"}, []string{"id", "description"}, &iteratorForCreateCopyAccountVendor{rows: arg})
}

// iteratorForCreateCopyCatalogBrand implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogBrand struct {
	rows                 []CreateCopyCatalogBrandParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogBrand) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogBrand) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].Name,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreateCopyCatalogBrand) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogBrand(ctx context.Context, arg []CreateCopyCatalogBrandParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "brand"}, []string{"code", "name", "description"}, &iteratorForCreateCopyCatalogBrand{rows: arg})
}

// iteratorForCreateCopyCatalogCategory implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogCategory struct {
	rows                 []CreateCopyCatalogCategoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogCategory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogCategory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].ParentID,
	}, nil
}

func (r iteratorForCreateCopyCatalogCategory) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogCategory(ctx context.Context, arg []CreateCopyCatalogCategoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "category"}, []string{"name", "description", "parent_id"}, &iteratorForCreateCopyCatalogCategory{rows: arg})
}

// iteratorForCreateCopyCatalogComment implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogComment struct {
	rows                 []CreateCopyCatalogCommentParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogComment) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogComment) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Body,
		r.rows[0].Upvote,
		r.rows[0].Downvote,
		r.rows[0].Score,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyCatalogComment) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogComment(ctx context.Context, arg []CreateCopyCatalogCommentParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "comment"}, []string{"account_id", "ref_type", "ref_id", "body", "upvote", "downvote", "score", "date_created", "date_updated"}, &iteratorForCreateCopyCatalogComment{rows: arg})
}

// iteratorForCreateCopyCatalogProductSku implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogProductSku struct {
	rows                 []CreateCopyCatalogProductSkuParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogProductSku) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogProductSku) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SpuID,
		r.rows[0].Price,
		r.rows[0].CanCombine,
		r.rows[0].DateCreated,
		r.rows[0].DateDeleted,
	}, nil
}

func (r iteratorForCreateCopyCatalogProductSku) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogProductSku(ctx context.Context, arg []CreateCopyCatalogProductSkuParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_sku"}, []string{"spu_id", "price", "can_combine", "date_created", "date_deleted"}, &iteratorForCreateCopyCatalogProductSku{rows: arg})
}

// iteratorForCreateCopyCatalogProductSkuAttribute implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogProductSkuAttribute struct {
	rows                 []CreateCopyCatalogProductSkuAttributeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogProductSkuAttribute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogProductSkuAttribute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SkuID,
		r.rows[0].Name,
		r.rows[0].Value,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyCatalogProductSkuAttribute) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogProductSkuAttribute(ctx context.Context, arg []CreateCopyCatalogProductSkuAttributeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_sku_attribute"}, []string{"sku_id", "name", "value", "date_created", "date_updated"}, &iteratorForCreateCopyCatalogProductSkuAttribute{rows: arg})
}

// iteratorForCreateCopyCatalogProductSpu implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogProductSpu struct {
	rows                 []CreateCopyCatalogProductSpuParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogProductSpu) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogProductSpu) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].AccountID,
		r.rows[0].CategoryID,
		r.rows[0].BrandID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].IsActive,
		r.rows[0].DateManufactured,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
		r.rows[0].DateDeleted,
	}, nil
}

func (r iteratorForCreateCopyCatalogProductSpu) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogProductSpu(ctx context.Context, arg []CreateCopyCatalogProductSpuParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_spu"}, []string{"code", "account_id", "category_id", "brand_id", "name", "description", "is_active", "date_manufactured", "date_created", "date_updated", "date_deleted"}, &iteratorForCreateCopyCatalogProductSpu{rows: arg})
}

// iteratorForCreateCopyCatalogProductSpuTag implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogProductSpuTag struct {
	rows                 []CreateCopyCatalogProductSpuTagParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogProductSpuTag) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogProductSpuTag) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SpuID,
		r.rows[0].TagID,
	}, nil
}

func (r iteratorForCreateCopyCatalogProductSpuTag) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogProductSpuTag(ctx context.Context, arg []CreateCopyCatalogProductSpuTagParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_spu_tag"}, []string{"spu_id", "tag_id"}, &iteratorForCreateCopyCatalogProductSpuTag{rows: arg})
}

// iteratorForCreateCopyCatalogTag implements pgx.CopyFromSource.
type iteratorForCreateCopyCatalogTag struct {
	rows                 []CreateCopyCatalogTagParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyCatalogTag) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyCatalogTag) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Tag,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreateCopyCatalogTag) Err() error {
	return nil
}

func (q *Queries) CreateCopyCatalogTag(ctx context.Context, arg []CreateCopyCatalogTagParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "tag"}, []string{"tag", "description"}, &iteratorForCreateCopyCatalogTag{rows: arg})
}

// iteratorForCreateCopyDefaultAccountAddress implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountAddress struct {
	rows                 []CreateCopyDefaultAccountAddressParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountAddress) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountAddress) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].FullName,
		r.rows[0].Phone,
		r.rows[0].AddressLine,
		r.rows[0].City,
		r.rows[0].StateProvince,
		r.rows[0].Country,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountAddress) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountAddress(ctx context.Context, arg []CreateCopyDefaultAccountAddressParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "address"}, []string{"account_id", "full_name", "phone", "address_line", "city", "state_province", "country"}, &iteratorForCreateCopyDefaultAccountAddress{rows: arg})
}

// iteratorForCreateCopyDefaultAccountBase implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountBase struct {
	rows                 []CreateCopyDefaultAccountBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Type,
		r.rows[0].Phone,
		r.rows[0].Email,
		r.rows[0].Username,
		r.rows[0].Password,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountBase(ctx context.Context, arg []CreateCopyDefaultAccountBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "base"}, []string{"type", "phone", "email", "username", "password"}, &iteratorForCreateCopyDefaultAccountBase{rows: arg})
}

// iteratorForCreateCopyDefaultAccountCartItem implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountCartItem struct {
	rows                 []CreateCopyDefaultAccountCartItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountCartItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountCartItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CartID,
		r.rows[0].SkuID,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountCartItem) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountCartItem(ctx context.Context, arg []CreateCopyDefaultAccountCartItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "cart_item"}, []string{"cart_id", "sku_id", "quantity"}, &iteratorForCreateCopyDefaultAccountCartItem{rows: arg})
}

// iteratorForCreateCopyDefaultAccountCustomer implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountCustomer struct {
	rows                 []CreateCopyDefaultAccountCustomerParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountCustomer) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountCustomer) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].DefaultAddressID,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountCustomer) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountCustomer(ctx context.Context, arg []CreateCopyDefaultAccountCustomerParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "customer"}, []string{"id", "default_address_id"}, &iteratorForCreateCopyDefaultAccountCustomer{rows: arg})
}

// iteratorForCreateCopyDefaultAccountIncomeHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountIncomeHistory struct {
	rows                 []CreateCopyDefaultAccountIncomeHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountIncomeHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountIncomeHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].Type,
		r.rows[0].Income,
		r.rows[0].CurrentBalance,
		r.rows[0].Note,
		r.rows[0].Hash,
		r.rows[0].PrevHash,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountIncomeHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountIncomeHistory(ctx context.Context, arg []CreateCopyDefaultAccountIncomeHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "income_history"}, []string{"account_id", "type", "income", "current_balance", "note", "hash", "prev_hash"}, &iteratorForCreateCopyDefaultAccountIncomeHistory{rows: arg})
}

// iteratorForCreateCopyDefaultAccountNotification implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountNotification struct {
	rows                 []CreateCopyDefaultAccountNotificationParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountNotification) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountNotification) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].Type,
		r.rows[0].Channel,
		r.rows[0].Content,
		r.rows[0].DateSent,
		r.rows[0].DateScheduled,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountNotification) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountNotification(ctx context.Context, arg []CreateCopyDefaultAccountNotificationParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "notification"}, []string{"account_id", "type", "channel", "content", "date_sent", "date_scheduled"}, &iteratorForCreateCopyDefaultAccountNotification{rows: arg})
}

// iteratorForCreateCopyDefaultAccountProfile implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountProfile struct {
	rows                 []CreateCopyDefaultAccountProfileParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountProfile) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountProfile) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Gender,
		r.rows[0].Name,
		r.rows[0].DateOfBirth,
		r.rows[0].AvatarRsID,
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountProfile) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountProfile(ctx context.Context, arg []CreateCopyDefaultAccountProfileParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "profile"}, []string{"id", "gender", "name", "date_of_birth", "avatar_rs_id"}, &iteratorForCreateCopyDefaultAccountProfile{rows: arg})
}

// iteratorForCreateCopyDefaultAccountVendor implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultAccountVendor struct {
	rows                 []int64
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultAccountVendor) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultAccountVendor) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateCopyDefaultAccountVendor) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultAccountVendor(ctx context.Context, id []int64) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"account", "vendor"}, []string{"id"}, &iteratorForCreateCopyDefaultAccountVendor{rows: id})
}

// iteratorForCreateCopyDefaultCatalogBrand implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogBrand struct {
	rows                 []CreateCopyDefaultCatalogBrandParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogBrand) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogBrand) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].Name,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogBrand) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogBrand(ctx context.Context, arg []CreateCopyDefaultCatalogBrandParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "brand"}, []string{"code", "name", "description"}, &iteratorForCreateCopyDefaultCatalogBrand{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogCategory implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogCategory struct {
	rows                 []CreateCopyDefaultCatalogCategoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogCategory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogCategory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].ParentID,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogCategory) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogCategory(ctx context.Context, arg []CreateCopyDefaultCatalogCategoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "category"}, []string{"name", "parent_id"}, &iteratorForCreateCopyDefaultCatalogCategory{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogComment implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogComment struct {
	rows                 []CreateCopyDefaultCatalogCommentParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogComment) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogComment) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Body,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogComment) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogComment(ctx context.Context, arg []CreateCopyDefaultCatalogCommentParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "comment"}, []string{"account_id", "ref_type", "ref_id", "body"}, &iteratorForCreateCopyDefaultCatalogComment{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogProductSku implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogProductSku struct {
	rows                 []CreateCopyDefaultCatalogProductSkuParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogProductSku) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogProductSku) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SpuID,
		r.rows[0].Price,
		r.rows[0].DateDeleted,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogProductSku) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogProductSku(ctx context.Context, arg []CreateCopyDefaultCatalogProductSkuParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_sku"}, []string{"spu_id", "price", "date_deleted"}, &iteratorForCreateCopyDefaultCatalogProductSku{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogProductSkuAttribute implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogProductSkuAttribute struct {
	rows                 []CreateCopyDefaultCatalogProductSkuAttributeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogProductSkuAttribute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogProductSkuAttribute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SkuID,
		r.rows[0].Name,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogProductSkuAttribute) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogProductSkuAttribute(ctx context.Context, arg []CreateCopyDefaultCatalogProductSkuAttributeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_sku_attribute"}, []string{"sku_id", "name", "value"}, &iteratorForCreateCopyDefaultCatalogProductSkuAttribute{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogProductSpu implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogProductSpu struct {
	rows                 []CreateCopyDefaultCatalogProductSpuParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogProductSpu) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogProductSpu) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].AccountID,
		r.rows[0].CategoryID,
		r.rows[0].BrandID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].DateManufactured,
		r.rows[0].DateDeleted,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogProductSpu) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogProductSpu(ctx context.Context, arg []CreateCopyDefaultCatalogProductSpuParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_spu"}, []string{"code", "account_id", "category_id", "brand_id", "name", "description", "date_manufactured", "date_deleted"}, &iteratorForCreateCopyDefaultCatalogProductSpu{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogProductSpuTag implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogProductSpuTag struct {
	rows                 []CreateCopyDefaultCatalogProductSpuTagParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogProductSpuTag) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogProductSpuTag) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SpuID,
		r.rows[0].TagID,
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogProductSpuTag) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogProductSpuTag(ctx context.Context, arg []CreateCopyDefaultCatalogProductSpuTagParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "product_spu_tag"}, []string{"spu_id", "tag_id"}, &iteratorForCreateCopyDefaultCatalogProductSpuTag{rows: arg})
}

// iteratorForCreateCopyDefaultCatalogTag implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultCatalogTag struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultCatalogTag) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultCatalogTag) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateCopyDefaultCatalogTag) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultCatalogTag(ctx context.Context, tag []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"catalog", "tag"}, []string{"tag"}, &iteratorForCreateCopyDefaultCatalogTag{rows: tag})
}

// iteratorForCreateCopyDefaultInventorySkuSerial implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultInventorySkuSerial struct {
	rows                 []CreateCopyDefaultInventorySkuSerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultInventorySkuSerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultInventorySkuSerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SerialNumber,
		r.rows[0].SkuID,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForCreateCopyDefaultInventorySkuSerial) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultInventorySkuSerial(ctx context.Context, arg []CreateCopyDefaultInventorySkuSerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "sku_serial"}, []string{"serial_number", "sku_id", "status"}, &iteratorForCreateCopyDefaultInventorySkuSerial{rows: arg})
}

// iteratorForCreateCopyDefaultInventoryStock implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultInventoryStock struct {
	rows                 []CreateCopyDefaultInventoryStockParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultInventoryStock) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultInventoryStock) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefType,
		r.rows[0].RefID,
	}, nil
}

func (r iteratorForCreateCopyDefaultInventoryStock) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultInventoryStock(ctx context.Context, arg []CreateCopyDefaultInventoryStockParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock"}, []string{"ref_type", "ref_id"}, &iteratorForCreateCopyDefaultInventoryStock{rows: arg})
}

// iteratorForCreateCopyDefaultInventoryStockHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultInventoryStockHistory struct {
	rows                 []CreateCopyDefaultInventoryStockHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultInventoryStockHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultInventoryStockHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StockID,
		r.rows[0].Change,
	}, nil
}

func (r iteratorForCreateCopyDefaultInventoryStockHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultInventoryStockHistory(ctx context.Context, arg []CreateCopyDefaultInventoryStockHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock_history"}, []string{"stock_id", "change"}, &iteratorForCreateCopyDefaultInventoryStockHistory{rows: arg})
}

// iteratorForCreateCopyDefaultOrderBase implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderBase struct {
	rows                 []CreateCopyDefaultOrderBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].PaymentMethod,
		r.rows[0].Status,
		r.rows[0].Address,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderBase(ctx context.Context, arg []CreateCopyDefaultOrderBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "base"}, []string{"account_id", "payment_method", "status", "address"}, &iteratorForCreateCopyDefaultOrderBase{rows: arg})
}

// iteratorForCreateCopyDefaultOrderInvoice implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderInvoice struct {
	rows                 []CreateCopyDefaultOrderInvoiceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderInvoice) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderInvoice) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Type,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].IssuerID,
		r.rows[0].ReceiverID,
		r.rows[0].Status,
		r.rows[0].PaymentMethod,
		r.rows[0].Address,
		r.rows[0].Phone,
		r.rows[0].Note,
		r.rows[0].Metadata,
		r.rows[0].Subtotal,
		r.rows[0].Total,
		r.rows[0].FileRsID,
		r.rows[0].Hash,
		r.rows[0].PrevHash,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderInvoice) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderInvoice(ctx context.Context, arg []CreateCopyDefaultOrderInvoiceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "invoice"}, []string{"type", "ref_type", "ref_id", "issuer_id", "receiver_id", "status", "payment_method", "address", "phone", "note", "metadata", "subtotal", "total", "file_rs_id", "hash", "prev_hash"}, &iteratorForCreateCopyDefaultOrderInvoice{rows: arg})
}

// iteratorForCreateCopyDefaultOrderItem implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderItem struct {
	rows                 []CreateCopyDefaultOrderItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].SkuID,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderItem) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderItem(ctx context.Context, arg []CreateCopyDefaultOrderItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "item"}, []string{"order_id", "sku_id", "quantity"}, &iteratorForCreateCopyDefaultOrderItem{rows: arg})
}

// iteratorForCreateCopyDefaultOrderItemSerial implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderItemSerial struct {
	rows                 []CreateCopyDefaultOrderItemSerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderItemSerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderItemSerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderItemID,
		r.rows[0].ProductSerialID,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderItemSerial) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderItemSerial(ctx context.Context, arg []CreateCopyDefaultOrderItemSerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "item_serial"}, []string{"order_item_id", "product_serial_id"}, &iteratorForCreateCopyDefaultOrderItemSerial{rows: arg})
}

// iteratorForCreateCopyDefaultOrderRefund implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderRefund struct {
	rows                 []CreateCopyDefaultOrderRefundParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderRefund) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderRefund) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderItemID,
		r.rows[0].ReviewedByID,
		r.rows[0].Method,
		r.rows[0].Status,
		r.rows[0].Reason,
		r.rows[0].Address,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderRefund) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderRefund(ctx context.Context, arg []CreateCopyDefaultOrderRefundParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "refund"}, []string{"order_item_id", "reviewed_by_id", "method", "status", "reason", "address"}, &iteratorForCreateCopyDefaultOrderRefund{rows: arg})
}

// iteratorForCreateCopyDefaultOrderRefundDispute implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderRefundDispute struct {
	rows                 []CreateCopyDefaultOrderRefundDisputeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderRefundDispute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderRefundDispute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefundID,
		r.rows[0].IssuedByID,
		r.rows[0].Reason,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderRefundDispute) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderRefundDispute(ctx context.Context, arg []CreateCopyDefaultOrderRefundDisputeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "refund_dispute"}, []string{"refund_id", "issued_by_id", "reason", "date_updated"}, &iteratorForCreateCopyDefaultOrderRefundDispute{rows: arg})
}

// iteratorForCreateCopyDefaultOrderVnpay implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultOrderVnpay struct {
	rows                 []CreateCopyDefaultOrderVnpayParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultOrderVnpay) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultOrderVnpay) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].VnpAmount,
		r.rows[0].VnpBankCode,
		r.rows[0].VnpCardType,
		r.rows[0].VnpOrderInfo,
		r.rows[0].VnpPayDate,
		r.rows[0].VnpResponseCode,
		r.rows[0].VnpSecureHash,
		r.rows[0].VnpTmnCode,
		r.rows[0].VnpTransactionNo,
		r.rows[0].VnpTransactionStatus,
		r.rows[0].VnpTxnRef,
	}, nil
}

func (r iteratorForCreateCopyDefaultOrderVnpay) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultOrderVnpay(ctx context.Context, arg []CreateCopyDefaultOrderVnpayParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "vnpay"}, []string{"id", "vnp_Amount", "vnp_BankCode", "vnp_CardType", "vnp_OrderInfo", "vnp_PayDate", "vnp_ResponseCode", "vnp_SecureHash", "vnp_TmnCode", "vnp_TransactionNo", "vnp_TransactionStatus", "vnp_TxnRef"}, &iteratorForCreateCopyDefaultOrderVnpay{rows: arg})
}

// iteratorForCreateCopyDefaultPromotionBase implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultPromotionBase struct {
	rows                 []CreateCopyDefaultPromotionBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultPromotionBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultPromotionBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].OwnerID,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Type,
		r.rows[0].Title,
		r.rows[0].Description,
		r.rows[0].DateEnded,
		r.rows[0].ScheduleTz,
		r.rows[0].ScheduleStart,
		r.rows[0].ScheduleDuration,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyDefaultPromotionBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultPromotionBase(ctx context.Context, arg []CreateCopyDefaultPromotionBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"promotion", "base"}, []string{"code", "owner_id", "ref_type", "ref_id", "type", "title", "description", "date_ended", "schedule_tz", "schedule_start", "schedule_duration", "date_updated"}, &iteratorForCreateCopyDefaultPromotionBase{rows: arg})
}

// iteratorForCreateCopyDefaultPromotionDiscount implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultPromotionDiscount struct {
	rows                 []CreateCopyDefaultPromotionDiscountParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultPromotionDiscount) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultPromotionDiscount) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OrderWide,
		r.rows[0].DiscountPercent,
		r.rows[0].DiscountPrice,
	}, nil
}

func (r iteratorForCreateCopyDefaultPromotionDiscount) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultPromotionDiscount(ctx context.Context, arg []CreateCopyDefaultPromotionDiscountParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"promotion", "discount"}, []string{"id", "order_wide", "discount_percent", "discount_price"}, &iteratorForCreateCopyDefaultPromotionDiscount{rows: arg})
}

// iteratorForCreateCopyDefaultSharedResource implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultSharedResource struct {
	rows                 []CreateCopyDefaultSharedResourceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultSharedResource) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultSharedResource) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MimeType,
		r.rows[0].OwnerID,
		r.rows[0].OwnerType,
		r.rows[0].Url,
		r.rows[0].Order,
	}, nil
}

func (r iteratorForCreateCopyDefaultSharedResource) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultSharedResource(ctx context.Context, arg []CreateCopyDefaultSharedResourceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"shared", "resource"}, []string{"mime_type", "owner_id", "owner_type", "url", "order"}, &iteratorForCreateCopyDefaultSharedResource{rows: arg})
}

// iteratorForCreateCopyDefaultSystemEvent implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultSystemEvent struct {
	rows                 []CreateCopyDefaultSystemEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultSystemEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultSystemEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].AggregateID,
		r.rows[0].AggregateType,
		r.rows[0].EventType,
		r.rows[0].Payload,
		r.rows[0].Version,
	}, nil
}

func (r iteratorForCreateCopyDefaultSystemEvent) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultSystemEvent(ctx context.Context, arg []CreateCopyDefaultSystemEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "event"}, []string{"account_id", "aggregate_id", "aggregate_type", "event_type", "payload", "version"}, &iteratorForCreateCopyDefaultSystemEvent{rows: arg})
}

// iteratorForCreateCopyDefaultSystemSearchSync implements pgx.CopyFromSource.
type iteratorForCreateCopyDefaultSystemSearchSync struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyDefaultSystemSearchSync) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyDefaultSystemSearchSync) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateCopyDefaultSystemSearchSync) Err() error {
	return nil
}

func (q *Queries) CreateCopyDefaultSystemSearchSync(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "search_sync"}, []string{"name"}, &iteratorForCreateCopyDefaultSystemSearchSync{rows: name})
}

// iteratorForCreateCopyInventorySkuSerial implements pgx.CopyFromSource.
type iteratorForCreateCopyInventorySkuSerial struct {
	rows                 []CreateCopyInventorySkuSerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyInventorySkuSerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyInventorySkuSerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SerialNumber,
		r.rows[0].SkuID,
		r.rows[0].Status,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyInventorySkuSerial) Err() error {
	return nil
}

func (q *Queries) CreateCopyInventorySkuSerial(ctx context.Context, arg []CreateCopyInventorySkuSerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "sku_serial"}, []string{"serial_number", "sku_id", "status", "date_created"}, &iteratorForCreateCopyInventorySkuSerial{rows: arg})
}

// iteratorForCreateCopyInventoryStock implements pgx.CopyFromSource.
type iteratorForCreateCopyInventoryStock struct {
	rows                 []CreateCopyInventoryStockParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyInventoryStock) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyInventoryStock) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].CurrentStock,
		r.rows[0].Sold,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyInventoryStock) Err() error {
	return nil
}

func (q *Queries) CreateCopyInventoryStock(ctx context.Context, arg []CreateCopyInventoryStockParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock"}, []string{"ref_type", "ref_id", "current_stock", "sold", "date_created"}, &iteratorForCreateCopyInventoryStock{rows: arg})
}

// iteratorForCreateCopyInventoryStockHistory implements pgx.CopyFromSource.
type iteratorForCreateCopyInventoryStockHistory struct {
	rows                 []CreateCopyInventoryStockHistoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyInventoryStockHistory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyInventoryStockHistory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StockID,
		r.rows[0].Change,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyInventoryStockHistory) Err() error {
	return nil
}

func (q *Queries) CreateCopyInventoryStockHistory(ctx context.Context, arg []CreateCopyInventoryStockHistoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "stock_history"}, []string{"stock_id", "change", "date_created"}, &iteratorForCreateCopyInventoryStockHistory{rows: arg})
}

// iteratorForCreateCopyOrderBase implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderBase struct {
	rows                 []CreateCopyOrderBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].PaymentMethod,
		r.rows[0].Status,
		r.rows[0].Address,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyOrderBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderBase(ctx context.Context, arg []CreateCopyOrderBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "base"}, []string{"account_id", "payment_method", "status", "address", "date_created", "date_updated"}, &iteratorForCreateCopyOrderBase{rows: arg})
}

// iteratorForCreateCopyOrderInvoice implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderInvoice struct {
	rows                 []CreateCopyOrderInvoiceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderInvoice) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderInvoice) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Type,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].IssuerID,
		r.rows[0].ReceiverID,
		r.rows[0].Status,
		r.rows[0].PaymentMethod,
		r.rows[0].Address,
		r.rows[0].Phone,
		r.rows[0].Note,
		r.rows[0].Metadata,
		r.rows[0].Subtotal,
		r.rows[0].Total,
		r.rows[0].FileRsID,
		r.rows[0].DateCreated,
		r.rows[0].Hash,
		r.rows[0].PrevHash,
	}, nil
}

func (r iteratorForCreateCopyOrderInvoice) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderInvoice(ctx context.Context, arg []CreateCopyOrderInvoiceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "invoice"}, []string{"type", "ref_type", "ref_id", "issuer_id", "receiver_id", "status", "payment_method", "address", "phone", "note", "metadata", "subtotal", "total", "file_rs_id", "date_created", "hash", "prev_hash"}, &iteratorForCreateCopyOrderInvoice{rows: arg})
}

// iteratorForCreateCopyOrderItem implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderItem struct {
	rows                 []CreateCopyOrderItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].SkuID,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForCreateCopyOrderItem) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderItem(ctx context.Context, arg []CreateCopyOrderItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "item"}, []string{"order_id", "sku_id", "quantity"}, &iteratorForCreateCopyOrderItem{rows: arg})
}

// iteratorForCreateCopyOrderItemSerial implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderItemSerial struct {
	rows                 []CreateCopyOrderItemSerialParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderItemSerial) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderItemSerial) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderItemID,
		r.rows[0].ProductSerialID,
	}, nil
}

func (r iteratorForCreateCopyOrderItemSerial) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderItemSerial(ctx context.Context, arg []CreateCopyOrderItemSerialParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "item_serial"}, []string{"order_item_id", "product_serial_id"}, &iteratorForCreateCopyOrderItemSerial{rows: arg})
}

// iteratorForCreateCopyOrderRefund implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderRefund struct {
	rows                 []CreateCopyOrderRefundParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderRefund) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderRefund) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderItemID,
		r.rows[0].ReviewedByID,
		r.rows[0].Method,
		r.rows[0].Status,
		r.rows[0].Reason,
		r.rows[0].Address,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopyOrderRefund) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderRefund(ctx context.Context, arg []CreateCopyOrderRefundParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "refund"}, []string{"order_item_id", "reviewed_by_id", "method", "status", "reason", "address", "date_created"}, &iteratorForCreateCopyOrderRefund{rows: arg})
}

// iteratorForCreateCopyOrderRefundDispute implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderRefundDispute struct {
	rows                 []CreateCopyOrderRefundDisputeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderRefundDispute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderRefundDispute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RefundID,
		r.rows[0].IssuedByID,
		r.rows[0].Reason,
		r.rows[0].Status,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyOrderRefundDispute) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderRefundDispute(ctx context.Context, arg []CreateCopyOrderRefundDisputeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "refund_dispute"}, []string{"refund_id", "issued_by_id", "reason", "status", "date_created", "date_updated"}, &iteratorForCreateCopyOrderRefundDispute{rows: arg})
}

// iteratorForCreateCopyOrderVnpay implements pgx.CopyFromSource.
type iteratorForCreateCopyOrderVnpay struct {
	rows                 []CreateCopyOrderVnpayParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyOrderVnpay) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyOrderVnpay) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].VnpAmount,
		r.rows[0].VnpBankCode,
		r.rows[0].VnpCardType,
		r.rows[0].VnpOrderInfo,
		r.rows[0].VnpPayDate,
		r.rows[0].VnpResponseCode,
		r.rows[0].VnpSecureHash,
		r.rows[0].VnpTmnCode,
		r.rows[0].VnpTransactionNo,
		r.rows[0].VnpTransactionStatus,
		r.rows[0].VnpTxnRef,
	}, nil
}

func (r iteratorForCreateCopyOrderVnpay) Err() error {
	return nil
}

func (q *Queries) CreateCopyOrderVnpay(ctx context.Context, arg []CreateCopyOrderVnpayParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order", "vnpay"}, []string{"id", "vnp_Amount", "vnp_BankCode", "vnp_CardType", "vnp_OrderInfo", "vnp_PayDate", "vnp_ResponseCode", "vnp_SecureHash", "vnp_TmnCode", "vnp_TransactionNo", "vnp_TransactionStatus", "vnp_TxnRef"}, &iteratorForCreateCopyOrderVnpay{rows: arg})
}

// iteratorForCreateCopyPromotionBase implements pgx.CopyFromSource.
type iteratorForCreateCopyPromotionBase struct {
	rows                 []CreateCopyPromotionBaseParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyPromotionBase) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyPromotionBase) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].OwnerID,
		r.rows[0].RefType,
		r.rows[0].RefID,
		r.rows[0].Type,
		r.rows[0].Title,
		r.rows[0].Description,
		r.rows[0].IsActive,
		r.rows[0].DateStarted,
		r.rows[0].DateEnded,
		r.rows[0].ScheduleTz,
		r.rows[0].ScheduleStart,
		r.rows[0].ScheduleDuration,
		r.rows[0].DateCreated,
		r.rows[0].DateUpdated,
	}, nil
}

func (r iteratorForCreateCopyPromotionBase) Err() error {
	return nil
}

func (q *Queries) CreateCopyPromotionBase(ctx context.Context, arg []CreateCopyPromotionBaseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"promotion", "base"}, []string{"code", "owner_id", "ref_type", "ref_id", "type", "title", "description", "is_active", "date_started", "date_ended", "schedule_tz", "schedule_start", "schedule_duration", "date_created", "date_updated"}, &iteratorForCreateCopyPromotionBase{rows: arg})
}

// iteratorForCreateCopyPromotionDiscount implements pgx.CopyFromSource.
type iteratorForCreateCopyPromotionDiscount struct {
	rows                 []CreateCopyPromotionDiscountParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopyPromotionDiscount) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopyPromotionDiscount) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OrderWide,
		r.rows[0].MinSpend,
		r.rows[0].MaxDiscount,
		r.rows[0].DiscountPercent,
		r.rows[0].DiscountPrice,
	}, nil
}

func (r iteratorForCreateCopyPromotionDiscount) Err() error {
	return nil
}

func (q *Queries) CreateCopyPromotionDiscount(ctx context.Context, arg []CreateCopyPromotionDiscountParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"promotion", "discount"}, []string{"id", "order_wide", "min_spend", "max_discount", "discount_percent", "discount_price"}, &iteratorForCreateCopyPromotionDiscount{rows: arg})
}

// iteratorForCreateCopySharedResource implements pgx.CopyFromSource.
type iteratorForCreateCopySharedResource struct {
	rows                 []CreateCopySharedResourceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopySharedResource) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopySharedResource) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MimeType,
		r.rows[0].OwnerID,
		r.rows[0].OwnerType,
		r.rows[0].Url,
		r.rows[0].Order,
	}, nil
}

func (r iteratorForCreateCopySharedResource) Err() error {
	return nil
}

func (q *Queries) CreateCopySharedResource(ctx context.Context, arg []CreateCopySharedResourceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"shared", "resource"}, []string{"mime_type", "owner_id", "owner_type", "url", "order"}, &iteratorForCreateCopySharedResource{rows: arg})
}

// iteratorForCreateCopySystemEvent implements pgx.CopyFromSource.
type iteratorForCreateCopySystemEvent struct {
	rows                 []CreateCopySystemEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopySystemEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopySystemEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AccountID,
		r.rows[0].AggregateID,
		r.rows[0].AggregateType,
		r.rows[0].EventType,
		r.rows[0].Payload,
		r.rows[0].Version,
		r.rows[0].DateCreated,
	}, nil
}

func (r iteratorForCreateCopySystemEvent) Err() error {
	return nil
}

func (q *Queries) CreateCopySystemEvent(ctx context.Context, arg []CreateCopySystemEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "event"}, []string{"account_id", "aggregate_id", "aggregate_type", "event_type", "payload", "version", "date_created"}, &iteratorForCreateCopySystemEvent{rows: arg})
}

// iteratorForCreateCopySystemSearchSync implements pgx.CopyFromSource.
type iteratorForCreateCopySystemSearchSync struct {
	rows                 []CreateCopySystemSearchSyncParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCopySystemSearchSync) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCopySystemSearchSync) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].LastSynced,
	}, nil
}

func (r iteratorForCreateCopySystemSearchSync) Err() error {
	return nil
}

func (q *Queries) CreateCopySystemSearchSync(ctx context.Context, arg []CreateCopySystemSearchSyncParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"system", "search_sync"}, []string{"name", "last_synced"}, &iteratorForCreateCopySystemSearchSync{rows: arg})
}
