// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventory.sql

package db

import (
	"context"
)

const updateCurrentStock = `-- name: UpdateCurrentStock :exec
UPDATE "inventory"."stock"
SET "current_stock" = current_stock + $1
WHERE id = $2
`

type UpdateCurrentStockParams struct {
	Change int64 `json:"change"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateCurrentStock(ctx context.Context, arg UpdateCurrentStockParams) error {
	_, err := q.db.Exec(ctx, updateCurrentStock, arg.Change, arg.ID)
	return err
}

const updateSerialStatus = `-- name: UpdateSerialStatus :exec
UPDATE inventory.sku_serial
SET status = $1
WHERE id = ANY($2) OR serial_id = ANY($3)
`

type UpdateSerialStatusParams struct {
	Status   InventoryProductStatus `json:"status"`
	ID       []int64                `json:"id"`
	SerialID []string               `json:"serial_id"`
}

func (q *Queries) UpdateSerialStatus(ctx context.Context, arg UpdateSerialStatusParams) error {
	_, err := q.db.Exec(ctx, updateSerialStatus, arg.Status, arg.ID, arg.SerialID)
	return err
}
