// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invoice.sql

package db

import (
	"context"
)

const getLastInvoice = `-- name: GetLastInvoice :one
SELECT id, ref_type, ref_id, type, receiver_id, note, data, date_created
FROM "order".invoice
ORDER BY date_created DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLastInvoice(ctx context.Context) (OrderInvoice, error) {
	row := q.db.QueryRow(ctx, getLastInvoice)
	var i OrderInvoice
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.Type,
		&i.ReceiverID,
		&i.Note,
		&i.Data,
		&i.DateCreated,
	)
	return i, err
}
